import {randomBytes,randomUUID,createHash} from 'node:crypto';import type {Pool,PoolClient} from 'pg';
import {withTransaction,recordAudit,SecurityApiError} from '../auth/security-core';import {notFound,conflict} from '../supply/supply-util';
import {assertControlledWithdrawalResource,applyWithdrawalResultInTransaction} from './controlled-withdrawal-store';import {claimControlledWithdrawal,type ControlledWithdrawalIntent} from './controlled-withdrawal';
import {requireVerifiedControlledNotice,type VerifiedControlledNotice} from './controlled-withdrawal-notice';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
async function conclusion(c:PoolClient,notice:VerifiedControlledNotice,state:string,version:string,result:string,proof:{resultKey:string;providerFactId:string}|null){
 const prior=(await c.query("SELECT details FROM zzsh_iam.audit_event WHERE action='controlled.withdrawal.notice.processed' AND object_id=$1",[notice.noticeId])).rows[0];if(prior){if(prior.details.sourceDigest!==notice.sourceDigest)throw conflict('Original notice conclusion digest changed');return;}
 await recordAudit(c,{actorType:'system',actorId:'local-controlled-notice-receiver',requestId:'req_notice_processed_'+randomUUID(),action:'controlled.withdrawal.notice.processed',objectType:'controlled_payout_notice',objectId:notice.noticeId,outcome:'SUCCESS',details:{sourceDigest:notice.sourceDigest,intentId:notice.evidence.intentId,originalOperationId:notice.originalOperationId,operationVersion:version,state,conclusion:result,resultKey:proof?.resultKey??null,providerFactId:proof?.providerFactId??null}});
}
/** No HTTP mount. A declared source capability is mandatory even for a replay. */
export async function receiveTerminalControlledNotice(pool:Pool,notice:VerifiedControlledNotice){
 requireVerifiedControlledNotice(notice,820148);const resultKey='controlled-notice-'+sha(notice.noticeId).slice(0,48),token=randomBytes(24).toString('hex');
 return withTransaction(pool,async c=>{
  const resource=await assertControlledWithdrawalResource(c);requireVerifiedControlledNotice(notice,resource.oid);const hint=(await c.query('SELECT user_id FROM zzsh_order.withdrawal_intent WHERE id=$1',[notice.evidence.intentId])).rows[0];if(!hint)throw notFound();await c.query('SELECT id FROM zzsh_auth_user."user" WHERE id=$1 FOR UPDATE',[hint.user_id]);const row=(await c.query('SELECT * FROM zzsh_order.withdrawal_intent WHERE id=$1 FOR UPDATE',[notice.evidence.intentId])).rows[0];
  if(row.payout_key!==notice.evidence.payoutKey||!row.terminal||!['PAYOUT_POSTED','RELEASE_POSTED'].includes(row.funds_disposition))throw conflict('Notice reception requires the original posted terminal');
  const processed=(await c.query("SELECT details FROM zzsh_iam.audit_event WHERE action='controlled.withdrawal.notice.processed' AND object_id=$1",[notice.noticeId])).rows[0];if(processed){if(processed.details.sourceDigest!==notice.sourceDigest)throw conflict('Original processed notice digest changed');return{action:'REPLAY' as const,state:processed.details.state,operationVersion:processed.details.operationVersion};}
  const prior=(await c.query('SELECT evidence_digest FROM zzsh_order.withdrawal_provider_fact WHERE intent_id=$1 AND result_key=$2',[row.id,resultKey])).rows[0];if(prior)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Original notice fact has no atomic processing conclusion; retain it for reconciliation');
  // Its immutable declared source row remains recorded; reconciliation cannot be auto-cleared.
  if(row.state==='RECONCILIATION_REQUIRED'){await conclusion(c,notice,row.state,String(row.operation_version),'ALREADY_FROZEN',null);await c.query('SET CONSTRAINTS ALL IMMEDIATE');return{action:'ALREADY_FROZEN' as const,state:row.state,operationVersion:String(row.operation_version)};}
  const now=new Date((await c.query("SELECT date_trunc('milliseconds',clock_timestamp()) AS now")).rows[0].now).toISOString(),until=new Date(new Date(now).getTime()+30000).toISOString();
  const intent:ControlledWithdrawalIntent={id:row.id,userId:row.user_id,destinationId:row.destination_id,mode:'LOCAL_CONTROLLED',policyVersion:row.policy_version,ledgerRevision:String(row.expected_ledger_revision),acceptedAt:new Date(row.accepted_at).toISOString(),currency:'CNY',grossCents:String(row.gross_cents),netCents:String(row.net_cents),feeCents:String(row.fee_cents),payoutKey:row.payout_key,state:row.state,operationVersion:String(row.operation_version),fundsDisposition:row.funds_disposition,terminal:row.terminal,conflictDigest:row.conflict_digest,lease:row.lease_token_hash?{tokenHash:row.lease_token_hash,until:new Date(row.lease_until).toISOString()}:null};
  const next=claimControlledWithdrawal(intent,intent.operationVersion,token,until,now);if(next.command!=='QUERY')throw conflict('A terminal notice cannot submit another payout');await c.query("SELECT set_config('zzsh.withdrawal_lease_hash',$1,true)",[sha(token)]);await c.query('UPDATE zzsh_order.withdrawal_intent SET state=$2,operation_version=$3,lease_token_hash=$4,lease_until=$5 WHERE id=$1 AND operation_version=$6',[row.id,next.intent.state,next.intent.operationVersion,next.intent.lease?.tokenHash,until,row.operation_version]);await recordAudit(c,{actorType:'system',actorId:'local-controlled-notice-receiver',requestId:'req_notice_'+randomUUID(),action:'controlled.withdrawal.notice.claimed',objectType:'withdrawal_intent',objectId:row.id,outcome:'SUCCESS',details:{noticeId:notice.noticeId,sourceDigest:notice.sourceDigest,command:'QUERY'}});
  // Claim, result and conclusion commit together under the same stable locks.
  const applied=await applyWithdrawalResultInTransaction(c,row.id,next.intent.operationVersion,token,resultKey,notice.evidence);
  const fact=(await c.query('SELECT id,evidence_digest FROM zzsh_order.withdrawal_provider_fact WHERE intent_id=$1 AND result_key=$2',[row.id,resultKey])).rows[0];if(!fact||fact.evidence_digest!==notice.sourceDigest)throw conflict('Atomic notice result source differs');
  const kind=applied.intent.state==='RECONCILIATION_REQUIRED'?'CONFLICT_TERMINAL':['TIMEOUT','ACKNOWLEDGED'].includes(notice.evidence.outcome)?'IGNORED_NONTERMINAL':'SAME_TERMINAL';
  await conclusion(c,notice,applied.intent.state,applied.intent.operationVersion,kind,{resultKey,providerFactId:fact.id});await c.query('SET CONSTRAINTS ALL IMMEDIATE');return{action:'OBSERVED' as const,...applied};
 });
}
export async function readControlledNoticeConclusion(pool:Pool,notice:VerifiedControlledNotice){requireVerifiedControlledNotice(notice,820148);return withTransaction(pool,async c=>{const r=await assertControlledWithdrawalResource(c);requireVerifiedControlledNotice(notice,r.oid);const row=(await c.query("SELECT details FROM zzsh_iam.audit_event WHERE action='controlled.withdrawal.notice.processed' AND object_id=$1",[notice.noticeId])).rows[0];return row?{knowledge:'KNOWN' as const,noticeId:notice.noticeId,...row.details}:{knowledge:'UNKNOWN' as const,noticeId:notice.noticeId};});}
