import type {Pool} from 'pg';import {createHash,randomBytes} from 'node:crypto';import {withTransaction} from '../auth/security-core';import {canonicalize} from '../supply/content-hash';import {conflict,notFound} from '../supply/supply-util';
import {assertControlledWithdrawalResource,claimWithdrawal,applyWithdrawalResult} from './controlled-withdrawal-store';import type {ControlledPayoutEvidence} from './controlled-withdrawal';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
/** SQL-backed local channel, never a bank/QR provider. Outcome is a maintenance-owned
 * declared destination scenario, not a public body or an in-memory success default. */
export async function submitDeclaredControlledPayout(pool:Pool,id:string,token:string,version:string){return withTransaction(pool,async c=>{
 await assertControlledWithdrawalResource(c);const hint=(await c.query('SELECT user_id FROM zzsh_order.withdrawal_intent WHERE id=$1',[id])).rows[0];if(!hint)throw notFound();await c.query('SELECT id FROM zzsh_auth_user."user" WHERE id=$1 FOR UPDATE',[hint.user_id]);
 const row=(await c.query('SELECT i.*,d.scenario FROM zzsh_order.withdrawal_intent i JOIN zzsh_order.withdrawal_destination d ON d.id=i.destination_id WHERE i.id=$1 FOR UPDATE OF i',[id])).rows[0];
 if(!['FAIL_UNPAID','TIMEOUT_THEN_SUCCEED'].includes(row.scenario))throw conflict('Unreviewed controlled channel scenario');
 const old=(await c.query('SELECT * FROM zzsh_order.controlled_payout_operation WHERE intent_id=$1',[id])).rows[0];if(old){if(old.payout_key!==row.payout_key)throw conflict('Original controlled key differs');return{evidence:JSON.parse(old.final_evidence_canonical) as ControlledPayoutEvidence,resultKey:old.id+'_final',operationReplayed:true};}
 if(row.state!=='SUBMITTING'||String(row.operation_version)!==version||row.lease_token_hash!==sha(token)||new Date(row.lease_until).getTime()<=Date.now())throw conflict('Current submit lease required');
 await c.query("SELECT set_config('zzsh.withdrawal_lease_hash',$1,true)",[sha(token)]);const operationId='ctrl_operation_'+sha(id).slice(0,40),common={mode:'LOCAL_CONTROLLED' as const,intentId:id,payoutKey:row.payout_key};
 const final:ControlledPayoutEvidence=row.scenario==='FAIL_UNPAID'?{...common,outcome:'FAILED',reference:operationId,unpaidConfirmed:true,transferredCents:'0',chargedFeeCents:'0'}:{...common,outcome:'SUCCEEDED',reference:operationId,netCents:String(row.net_cents),feeCents:String(row.fee_cents)};
 const bytes=canonicalize(final);await c.query(`INSERT INTO zzsh_order.controlled_payout_operation(id,intent_id,payout_key,mode,scenario,final_evidence_canonical,final_evidence_digest,original_lease_hash) VALUES($1,$2,$3,'LOCAL_CONTROLLED',$4,$5,$6,$7)`,[operationId,id,row.payout_key,row.scenario,bytes,sha(bytes),sha(token)]);
 return{evidence:row.scenario==='TIMEOUT_THEN_SUCCEED'?{...common,outcome:'TIMEOUT' as const}:final,resultKey:operationId+(row.scenario==='TIMEOUT_THEN_SUCCEED'?'_ack_lost':'_final'),operationReplayed:false};
});}
export async function queryOriginalControlledPayout(pool:Pool,id:string,payoutKey:string,operationVersion:string){return withTransaction(pool,async c=>{await assertControlledWithdrawalResource(c);const i=(await c.query('SELECT payout_key,operation_version::text AS version FROM zzsh_order.withdrawal_intent WHERE id=$1',[id])).rows[0];if(!i||i.payout_key!==payoutKey)throw notFound();if(i.version!==operationVersion)throw conflict('Query lease was replaced');const op=(await c.query('SELECT * FROM zzsh_order.controlled_payout_operation WHERE intent_id=$1 AND payout_key=$2',[id,payoutKey])).rows[0];return op?{evidence:JSON.parse(op.final_evidence_canonical) as ControlledPayoutEvidence,resultKey:op.id+'_final'}:{evidence:{mode:'LOCAL_CONTROLLED' as const,intentId:id,payoutKey,outcome:'TIMEOUT' as const},resultKey:'no_original_result_'+sha(payoutKey).slice(0,32)+'_'+operationVersion};});}
/** One bounded maintenance step, no startup loop or public outcome-selection endpoint. */
export async function runControlledWithdrawalStep(pool:Pool,id:string){const token=randomBytes(24).toString('hex'),until=new Date(Date.now()+30000).toISOString(),claimed=await claimWithdrawal(pool,id,token,until);if(claimed.command==='NONE')return{action:'NONE',intent:claimed.intent};const intent=claimed.intent;
 const observation=claimed.command==='SUBMIT'?await submitDeclaredControlledPayout(pool,id,token,intent.operationVersion):await queryOriginalControlledPayout(pool,id,intent.payoutKey,intent.operationVersion);
 return{action:claimed.command,...await applyWithdrawalResult(pool,id,intent.operationVersion,token,observation.resultKey,observation.evidence)};
}
