import type { Pool, PoolClient } from 'pg';
import {createHash,randomUUID} from 'node:crypto';
import {assertUserContextInTransaction,type UserContext} from '../auth/user-identity';
import {recordAudit,SecurityApiError,withTransaction} from '../auth/security-core';
import {canonicalize} from '../supply/content-hash';
import {conflict,forbidden,notFound,withIdempotency,fingerprintRequest} from '../supply/supply-util';
import {readPersonalWallet} from './personal-finance-read';
import {quoteControlledWithdrawal,ownerLocalWithdrawalPolicy,countLocalWithdrawalQuota,reserveControlledWithdrawal,claimControlledWithdrawal,finishControlledWithdrawal,localWithdrawalRequestKey,type ControlledWithdrawalIntent,type ControlledPayoutEvidence,type WithdrawalLedgerPlan} from './controlled-withdrawal';
const sha=(v:string)=>createHash('sha256').update(v).digest('hex');
const unavailable=(reason:string)=>new SecurityApiError(503,'EVIDENCE_UNAVAILABLE',reason);
type Row=Record<string,any>;type Actor=UserContext & {requestId:string};
export async function assertControlledWithdrawalResource(client:PoolClient){
 const r=(await client.query(`SELECT current_database() AS name,current_user AS role,d.oid,shobj_description(d.oid,'pg_database') AS marker,
  to_regclass('zzsh_order.withdrawal_intent') IS NOT NULL AND to_regclass('zzsh_order.withdrawal_admission') IS NOT NULL AND to_regclass('zzsh_order.withdrawal_destination') IS NOT NULL AND to_regclass('zzsh_order.withdrawal_provider_fact') IS NOT NULL AND to_regclass('zzsh_order.controlled_payout_operation') IS NOT NULL AS complete FROM pg_database d WHERE d.datname=current_database()`)).rows[0];
 const identities=[['zzsh_test_m2_auth_auth_compat',820148,'zzsh_m2_auth_compat_'],['zzsh_test_m2_auth_auth_compat_ui',833000,'zzsh_m2_auth_compat_ui_']] as const;
 const expected=identities.find(([name,oid])=>r?.name===name&&Number(r.oid)===oid);
 if(!expected||r.marker!=='zzsh:m2-auth-test:v1'||![expected[2]+'r',expected[2]+'m'].includes(r.role))throw unavailable('CONTROLLED_RESOURCE_NOT_ADMITTED');
 if(!r.complete)throw unavailable('CONTROLLED_WITHDRAWAL_SCHEMA_UNAVAILABLE');return {name:r.name,oid:Number(r.oid),marker:r.marker};
}
function fromRow(r:Row):ControlledWithdrawalIntent{return{id:r.id,userId:r.user_id,destinationId:r.destination_id,mode:'LOCAL_CONTROLLED',policyVersion:r.policy_version,ledgerRevision:String(r.expected_ledger_revision),acceptedAt:new Date(r.accepted_at).toISOString(),currency:'CNY',grossCents:String(r.gross_cents),netCents:String(r.net_cents),feeCents:String(r.fee_cents),payoutKey:r.payout_key,state:r.state,operationVersion:String(r.operation_version),fundsDisposition:r.funds_disposition,terminal:r.terminal,conflictDigest:r.conflict_digest,lease:r.lease_token_hash?{tokenHash:r.lease_token_hash,until:new Date(r.lease_until).toISOString()}:null};}
function publicIntent(r:Row){const i=fromRow(r);return {id:i.id,scope:'LOCAL_CONTROLLED',userId:i.userId,state:i.state,operationVersion:i.operationVersion,fundsDisposition:i.fundsDisposition,amountCents:i.grossCents,netCents:i.netCents,feeCents:i.feeCents,destinationId:i.destinationId,policyVersion:i.policyVersion,acceptedAt:i.acceptedAt,evidenceLevel:'LOCAL_CONTROLLED',terminal:i.terminal?{state:i.terminal.state,reference:i.terminal.reference}:null};}
async function quoteInTransaction(client:PoolClient,actor:Actor,body:Record<string,unknown>){
 const resource=await assertControlledWithdrawalResource(client);await assertUserContextInTransaction(client,actor);
 const destination=(await client.query(`SELECT d.*,a.id AS cohort_id,a.revision AS cohort_revision,a.per_intent_cents::text,a.max_intents,a.max_gross_cents::text,a.expires_at,a.admitted_at,a.resource_oid,a.resource_name,a.resource_marker,a.active AS cohort_active FROM zzsh_order.withdrawal_destination d JOIN zzsh_order.withdrawal_admission a ON a.id=d.admission_id AND a.user_id=d.user_id WHERE d.id=$1 AND d.user_id=$2`,[body.destinationId,actor.userId])).rows[0];
 if(!destination)throw notFound();
 const clock=(await client.query(`SELECT date_trunc('milliseconds',clock_timestamp()) AS now`)).rows[0].now,now=new Date(clock).toISOString();
 if(!destination.cohort_active||clock<destination.admitted_at||clock>=destination.expires_at||Number(destination.resource_oid)!==resource.oid||destination.resource_name!==resource.name||destination.resource_marker!==resource.marker)throw unavailable('CONTROLLED_LOCAL_ADMISSION_UNAVAILABLE');
 const w=await readPersonalWallet(client,actor.userId),policy=ownerLocalWithdrawalPolicy(destination.kind,[actor.userId]);
 const rows=(await client.query('SELECT state,accepted_at FROM zzsh_order.withdrawal_intent WHERE user_id=$1',[actor.userId])).rows;
 const quote=quoteControlledWithdrawal(body,policy,{userId:actor.userId,active:true,localAdmissionEligible:true,coverageKnown:w.coverage.knowledge==='KNOWN',availableCents:w.buckets.available.amountCents,ledgerRevision:w.ledgerRevision,now,destination:{id:destination.id,userId:destination.user_id,mode:destination.mode,kind:destination.kind,active:destination.active},usage:countLocalWithdrawalQuota(rows.map(r=>({state:r.state,acceptedAt:new Date(r.accepted_at).toISOString()})),policy,now)});
 if((await client.query('SELECT 1 FROM zzsh_order.withdrawal_intent WHERE destination_id=$1',[destination.id])).rowCount)throw conflict('Declared local target already has its original intent');
 const total=(await client.query('SELECT count(*)::int AS n,COALESCE(sum(gross_cents),0)::text AS gross FROM zzsh_order.withdrawal_intent WHERE admission_id=$1',[destination.admission_id])).rows[0];
 if(quote.grossCents!==destination.per_intent_cents||total.n>=destination.max_intents||BigInt(total.gross)+BigInt(quote.grossCents)>BigInt(destination.max_gross_cents))throw conflict('Bounded local test allowance exhausted');
 return {quote,destination};
}
export async function readControlledWithdrawalQuote(pool:Pool,actor:Actor,body:Record<string,unknown>){return withTransaction(pool,async client=>{const {quote,destination}=await quoteInTransaction(client,actor,body);return{quote:{...quote,requestKey:localWithdrawalRequestKey(destination.admission_id,String(destination.cohort_revision),destination.id,String(destination.revision)),scope:'LOCAL_CONTROLLED',admissionRevision:String(destination.cohort_revision),identityMeaning:'EXPLICIT_LOCAL_TEST_ADMISSION_NOT_REAL_KYC',destination:{id:destination.id,kind:destination.kind,mask:destination.display_mask},globalWithdrawable:'UNKNOWN'}};});}
async function appendMoney(client:PoolClient,row:Row,plan:WithdrawalLedgerPlan){
 const revision=(await client.query('SELECT ledger_revision::text AS version FROM zzsh_order.wallet_revision WHERE user_id=$1',[row.user_id])).rows[0]?.version;if(revision===undefined)throw unavailable('WALLET_COVERAGE_UNKNOWN');
 const eventId='event_'+row.id+'_'+plan.kind.toLowerCase();
 await client.query('INSERT INTO zzsh_order.finance_event(id,economic_root_id,kind,subject_user_id,expected_ledger_revision) VALUES($1,$2,$3,$4,$5)',[eventId,row.economic_root_id,plan.kind,row.user_id,revision]);
 const details=JSON.stringify({intentId:row.id,economicRootId:row.economic_root_id,policyVersion:row.policy_version,inputDigest:row.input_digest});
 for(const [n,line]of plan.lines.entries())await client.query('INSERT INTO zzsh_order.settlement_ledger_entry(id,finance_event_id,line_no,account_code,debit_cents,credit_cents,counterparty_user_id,details) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)',[eventId+'_'+(n+1),eventId,n+1,line.accountCode,line.debitCents,line.creditCents,line.counterpartyUserId,details]);
 return eventId;
}
export async function createControlledWithdrawal(pool:Pool,actor:Actor,body:Record<string,unknown>,key:string){return withTransaction(pool,async client=>{
 await assertControlledWithdrawalResource(client);await assertUserContextInTransaction(client,actor);
 return withIdempotency(client,{realm:'user',principalId:actor.userId,operation:'controlled.withdrawal.reserve'},key,fingerprintRequest('controlled.withdrawal.reserve',undefined,body),()=>assertUserContextInTransaction(client,actor),async()=>{
  const {quote,destination}=await quoteInTransaction(client,actor,body);if(key!==localWithdrawalRequestKey(destination.admission_id,String(destination.cohort_revision),destination.id,String(destination.revision)))throw conflict('Use the original server-declared local request key');
  const id='wd_'+sha(canonicalize([actor.userId,key])).slice(0,40),rootId='withdrawal_root_'+sha(id).slice(0,40),digest=sha(canonicalize(body));
  const reserved=reserveControlledWithdrawal(id,quote);
  const row=(await client.query(`INSERT INTO zzsh_order.withdrawal_intent(id,user_id,admission_id,destination_id,destination_revision,mode,policy_version,input_digest,gross_cents,net_cents,fee_cents,expected_ledger_revision,accepted_at,payout_key,economic_root_id,state,operation_version,funds_disposition) VALUES($1,$2,$3,$4,$5,'LOCAL_CONTROLLED',$6,$7,$8,$9,$10,$11,$12,$13,$14,'RESERVED',1,'RESERVED') RETURNING *`,[id,actor.userId,destination.admission_id,destination.id,destination.revision,quote.policyVersion,digest,quote.grossCents,quote.netCents,quote.feeCents,quote.ledgerRevision,quote.acceptedAt,reserved.intent.payoutKey,rootId])).rows[0];
  await client.query(`INSERT INTO zzsh_order.finance_economic_root(id,basis_id,source_kind,source_type,source_system,source_entity,source_id,subject_user_id,beneficiary_role,policy_version,source_digest) VALUES($1,NULL,'LOCAL_CONTROLLED_WITHDRAWAL','NATIVE','zzsh-local-controlled','withdrawal_intent',$2,$3,'WALLET_HOLDER',$4,$5)`,[rootId,id,actor.userId,quote.policyVersion,digest]);
  await appendMoney(client,row,reserved.ledgerPlan);await recordAudit(client,{actorType:'user',actorId:actor.userId,sessionId:actor.sessionId,requestId:actor.requestId,action:'controlled.withdrawal.reserved',objectType:'withdrawal_intent',objectId:id,outcome:'SUCCESS',details:{scope:'LOCAL_CONTROLLED',bodyDigest:digest}});await client.query('SET CONSTRAINTS ALL IMMEDIATE');return{status:200,body:{intent:publicIntent(row)}};
 });
});}
export async function readControlledWithdrawals(pool:Pool,actor:Actor,id?:string){return withTransaction(pool,async client=>{
 await assertControlledWithdrawalResource(client);await assertUserContextInTransaction(client,actor);
 if(id){const row=(await client.query('SELECT * FROM zzsh_order.withdrawal_intent WHERE id=$1 AND user_id=$2',[id,actor.userId])).rows[0];if(!row)throw notFound();return{scope:'LOCAL_CONTROLLED',intent:publicIntent(row)};}
 const cohorts=(await client.query('SELECT id,revision::text,admitted_at,expires_at,max_intents FROM zzsh_order.withdrawal_admission WHERE user_id=$1 ORDER BY admitted_at,id',[actor.userId])).rows;
 if(!cohorts.length)throw unavailable('CONTROLLED_LOCAL_ADMISSION_UNAVAILABLE');
 const rows=(await client.query('SELECT * FROM zzsh_order.withdrawal_intent WHERE user_id=$1 ORDER BY accepted_at DESC,id',[actor.userId])).rows;
 const totals=(await client.query(`SELECT COALESCE(sum(l.credit_cents-l.debit_cents) FILTER(WHERE l.account_code='WALLET_RESERVED'),0)::text AS reserved,COALESCE(sum(l.credit_cents) FILTER(WHERE l.account_code='PAYOUT_CLEARING'),0)::text AS paid,COALESCE(sum(l.credit_cents) FILTER(WHERE l.account_code='WITHDRAW_FEE'),0)::text AS fee FROM zzsh_order.withdrawal_intent i JOIN zzsh_order.finance_event e ON e.economic_root_id=i.economic_root_id JOIN zzsh_order.settlement_ledger_entry l ON l.finance_event_id=e.id WHERE i.user_id=$1`,[actor.userId])).rows[0];
 const targets=(await client.query(`SELECT d.id,d.kind,d.display_mask AS mask,a.per_intent_cents::text,
  a.active AND clock_timestamp()>=a.admitted_at AND clock_timestamp()<a.expires_at
  AND NOT EXISTS(SELECT 1 FROM zzsh_order.withdrawal_intent i WHERE i.destination_id=d.id)
  AND (SELECT count(*) FROM zzsh_order.withdrawal_intent i WHERE i.admission_id=a.id)<a.max_intents
  AND (SELECT COALESCE(sum(i.gross_cents),0) FROM zzsh_order.withdrawal_intent i WHERE i.admission_id=a.id)+a.per_intent_cents<=a.max_gross_cents AS can_quote
  FROM zzsh_order.withdrawal_destination d JOIN zzsh_order.withdrawal_admission a ON a.id=d.admission_id AND a.user_id=d.user_id
  WHERE d.user_id=$1 AND d.active ORDER BY d.id`,[actor.userId])).rows;
 const destinations=targets.map(d=>({id:d.id,kind:d.kind,mask:d.mask,policyVersion:ownerLocalWithdrawalPolicy(d.kind,[actor.userId]).version,perIntentCents:d.per_intent_cents,canQuote:d.can_quote}));
 return{scope:'LOCAL_CONTROLLED',subjectId:actor.userId,coverage:{knowledge:'KNOWN',cohorts:cohorts.map(r=>({id:r.id,revision:r.revision,start:new Date(r.admitted_at).toISOString(),end:new Date(r.expires_at).toISOString()})),meaning:'EXPLICIT_LOCAL_INTENTS_ONLY_NOT_TOTAL_HISTORICAL_WALLET'},items:rows.map(publicIntent),destinations,totals:{reservedCents:totals.reserved,payoutCents:totals.paid,feeCents:totals.fee},globalReserved:'UNKNOWN'};
});}
export async function recoverControlledWithdrawal(pool:Pool,actor:Actor,key:string){return withTransaction(pool,async client=>{await assertControlledWithdrawalResource(client);await assertUserContextInTransaction(client,actor);const row=(await client.query('SELECT response_body AS body FROM zzsh_supply.idempotency_record WHERE scope_key=$1 AND key=$2',[JSON.stringify(['user',actor.userId,'controlled.withdrawal.reserve',null]),key])).rows[0];return row?{scope:'LOCAL_CONTROLLED',knowledge:'KNOWN',receipt:row.body}:{scope:'LOCAL_CONTROLLED',knowledge:'UNKNOWN',receipt:null};});}

/** Internal candidate worker only. No public route accepts outcome/lease tokens. */
export async function claimWithdrawal(pool:Pool,id:string,token:string,until:string){return withTransaction(pool,async client=>{
 await assertControlledWithdrawalResource(client);const hint=(await client.query('SELECT user_id FROM zzsh_order.withdrawal_intent WHERE id=$1',[id])).rows[0];if(!hint)throw notFound();await client.query('SELECT id FROM zzsh_auth_user."user" WHERE id=$1 FOR UPDATE',[hint.user_id]);const row=(await client.query('SELECT * FROM zzsh_order.withdrawal_intent WHERE id=$1 FOR UPDATE',[id])).rows[0];
 if(row.terminal||row.state==='RECONCILIATION_REQUIRED')return{command:'NONE' as const,intent:publicIntent(row)};
 const now=new Date((await client.query("SELECT date_trunc('milliseconds',clock_timestamp()) AS now")).rows[0].now).toISOString(),claimed=claimControlledWithdrawal(fromRow(row),String(row.operation_version),token,until,now);await client.query("SELECT set_config('zzsh.withdrawal_lease_hash',$1,true)",[sha(token)]);
 await client.query('UPDATE zzsh_order.withdrawal_intent SET state=$2,operation_version=$3,lease_token_hash=$4,lease_until=$5 WHERE id=$1 AND operation_version=$6',[id,claimed.intent.state,claimed.intent.operationVersion,claimed.intent.lease?.tokenHash,until,row.operation_version]);await recordAudit(client,{actorType:'system',actorId:'local-controlled-worker',requestId:'req_ctrl_claim_'+randomUUID(),action:'controlled.withdrawal.claimed',objectType:'withdrawal_intent',objectId:id,outcome:'SUCCESS',details:{command:claimed.command,operationVersion:claimed.intent.operationVersion}});return{command:claimed.command as 'SUBMIT'|'QUERY',intent:claimed.intent};
});}
export async function applyWithdrawalResult(pool:Pool,id:string,expectedVersion:string,token:string,resultKey:string,evidence:ControlledPayoutEvidence){return withTransaction(pool,async client=>{const result=await applyWithdrawalResultInTransaction(client,id,expectedVersion,token,resultKey,evidence);await client.query('SET CONSTRAINTS ALL IMMEDIATE');return result;});}
/** Shared transaction core: normal worker wrapper and terminal-notice receiver retain the same guards. */
export async function applyWithdrawalResultInTransaction(client:PoolClient,id:string,expectedVersion:string,token:string,resultKey:string,evidence:ControlledPayoutEvidence){
 await assertControlledWithdrawalResource(client);const hint=(await client.query('SELECT user_id FROM zzsh_order.withdrawal_intent WHERE id=$1',[id])).rows[0];if(!hint)throw notFound();await client.query('SELECT id FROM zzsh_auth_user."user" WHERE id=$1 FOR UPDATE',[hint.user_id]);const row=(await client.query('SELECT * FROM zzsh_order.withdrawal_intent WHERE id=$1 FOR UPDATE',[id])).rows[0],canonical=canonicalize(evidence),digest=sha(canonical);
 const prior=(await client.query('SELECT evidence_digest,producer_lease_hash FROM zzsh_order.withdrawal_provider_fact WHERE intent_id=$1 AND result_key=$2',[id,resultKey])).rows[0];if(prior){if(prior.evidence_digest!==digest)throw conflict('Original provider result key changed');if(row.lease_token_hash&&prior.producer_lease_hash!==row.lease_token_hash)throw conflict('A new lease must use its own query observation');return{intent:publicIntent(row),replayed:true};}
 const now=new Date((await client.query("SELECT date_trunc('milliseconds',clock_timestamp()) AS now")).rows[0].now).toISOString(),finished=finishControlledWithdrawal(fromRow(row),expectedVersion,token,evidence,now);
 if(finished.ledgerPlan){const operation=(await client.query('SELECT id,final_evidence_digest FROM zzsh_order.controlled_payout_operation WHERE intent_id=$1 AND payout_key=$2',[id,evidence.payoutKey])).rows[0];if(!operation||operation.final_evidence_digest!==digest||!('reference' in evidence)||operation.id!==evidence.reference)throw conflict('Monetary result has no matching durable original channel truth');}
 await client.query("SELECT set_config('zzsh.withdrawal_lease_hash',$1,true)",[sha(token)]);const factId='ctrl_fact_'+sha(canonicalize([id,resultKey])).slice(0,40);
 await client.query('INSERT INTO zzsh_order.withdrawal_provider_fact(id,intent_id,payout_key,mode,result_key,evidence_canonical,evidence_digest,producer_lease_hash) VALUES($1,$2,$3,\'LOCAL_CONTROLLED\',$4,$5,$6,$7)',[factId,id,evidence.payoutKey,resultKey,canonical,digest,sha(token)]);
 const next=finished.intent,updated=(await client.query('UPDATE zzsh_order.withdrawal_intent SET state=$2,operation_version=$3,funds_disposition=$4,terminal=$5::jsonb,conflict_digest=$6,lease_token_hash=NULL,lease_until=NULL,last_provider_fact_id=$7 WHERE id=$1 AND operation_version=$8 AND lease_token_hash=$9 AND lease_until>clock_timestamp() RETURNING *',[id,next.state,next.operationVersion,next.fundsDisposition,next.terminal===null?null:JSON.stringify(next.terminal),next.conflictDigest,factId,expectedVersion,sha(token)])).rows[0];if(!updated)throw conflict('Withdrawal lease expired or replaced');
 if(finished.ledgerPlan)await appendMoney(client,updated,finished.ledgerPlan);await recordAudit(client,{actorType:'system',actorId:'local-controlled-worker',requestId:'req_ctrl_result_'+randomUUID(),action:'controlled.withdrawal.result',objectType:'withdrawal_intent',objectId:id,outcome:'SUCCESS',details:{resultDigest:digest,outcome:evidence.outcome,ledgerAction:finished.ledgerPlan?.kind??null}});return{intent:publicIntent(updated),replayed:false};
}
