import {createHash} from 'node:crypto';import type {PoolClient} from 'pg';
import {SecurityApiError,recordAudit} from '../auth/security-core';import {conflict,invalid,notFound} from '../supply/supply-util';import {canonicalize,withoutContentHash} from '../supply/content-hash';import {sourceYuanToCents} from './personal-finance-read';
import {readDistributionPolicyRowInTransaction} from './distribution-policy-store';import {readDistributionParentInTransaction} from './invitation-store';import {freezePaymentDistributionBasis,readOriginalPaymentDistributionBasis,type PaymentDistributionBasis,type PaymentReferralFacts} from './distribution-payment-basis';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex'),ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
type Scope={resourceSet:string;resourceOid:number;approvalDigest:string;allowedOrderIds:readonly string[]};
type Prepared={orderId:string};
/** Candidate integration seam. Caller is the verified payment gate on its original transaction.
 * No route or default scope. Null means no admission; explicit composition must reject it.
 * Old payment callers that do not install this store retain their original behavior. */
export function createPaymentDistributionStore(scope:Scope){
 if(!/^[a-z][a-z0-9_]{0,20}$/.test(scope.resourceSet)||!Number.isSafeInteger(scope.resourceOid)||scope.resourceOid<=0||!/^[0-9a-f]{64}$/.test(scope.approvalDigest)||!scope.allowedOrderIds.length||scope.allowedOrderIds.some(id=>!ID.test(id)))throw invalid('Exact reviewed order resource and allowlist required');
 const allowed=new Set(scope.allowedOrderIds),name='zzsh_test_order_'+scope.resourceSet,role='zzsh_order_'+scope.resourceSet+'_r',prepared=new WeakMap<object,{client:PoolClient;transactionId:string;input:Omit<Parameters<typeof freezePaymentDistributionBasis>[0],'confirmationId'|'acceptedAt'|'paymentDigest'>}>();
 async function resource(c:PoolClient){const r=(await c.query("SELECT d.oid,current_database() AS name,current_user AS role,shobj_description(d.oid,'pg_database') AS marker FROM pg_database d WHERE datname=current_database()")).rows[0];if(!r||Number(r.oid)!==scope.resourceOid||r.name!==name||r.role!==role||r.marker!=='zzsh:order-reservation-test:v1')throw conflict('Distribution payment resource differs');}
 async function prepare(c:PoolClient,orderId:string):Promise<Prepared|null>{
  if(!allowed.has(orderId))return null;await resource(c);
  const complete=(await c.query(`SELECT to_regclass('zzsh_order.distribution_order_admission') IS NOT NULL AND to_regclass('zzsh_order.payment_distribution_basis') IS NOT NULL AND to_regclass('zzsh_order.distribution_policy_head') IS NOT NULL AND to_regclass('zzsh_order.distribution_participant') IS NOT NULL AND to_regclass('zzsh_order.invitation_relation') IS NOT NULL AS complete`)).rows[0]?.complete;if(!complete)return null;
  const admission=(await c.query(`SELECT * FROM zzsh_order.distribution_order_admission WHERE order_id=$1 AND active AND resource_oid=$2 AND resource_name=$3 AND resource_marker='zzsh:order-reservation-test:v1' AND approval_digest=$4 AND admitted_at<=clock_timestamp() AND expires_at>clock_timestamp()`,[orderId,scope.resourceOid,name,scope.approvalDigest])).rows[0];if(!admission)return null;
  await c.query("SELECT pg_advisory_xact_lock(hashtextextended('zzsh:invitation-graph:v1',0))");
  const order=(await c.query('SELECT id,renter_user_id,owner_user_id,game_id,currency,quote_snapshot FROM zzsh_order.rental_order WHERE id=$1',[orderId])).rows[0];if(!order)throw notFound();
  if(!(await c.query("SELECT id FROM zzsh_iam.audit_event WHERE id=$1 AND action='order.reservation.created' AND object_type='rental_order' AND object_id=$2 AND outcome='SUCCESS'",[admission.native_creation_audit_id,orderId])).rowCount)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Native order origin is not proved');
  const relations=(await c.query("SELECT r.*,p.leader_knowledge FROM zzsh_order.distribution_participant p LEFT JOIN zzsh_order.invitation_relation r ON r.child_user_id=p.user_id AND r.type='DISTRIBUTION_LEADER' WHERE p.user_id=ANY($1::text[])",[[order.renter_user_id,order.owner_user_id]])).rows;
  const ids=[...new Set([order.renter_user_id,order.owner_user_id,...relations.map(r=>r.parent_user_id).filter(Boolean)])];const locked=(await c.query('SELECT id FROM zzsh_auth_user."user" WHERE id=ANY($1::text[]) ORDER BY id FOR UPDATE',[ids])).rows;if(locked.length!==ids.length)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Payment party or beneficiary is missing');await c.query('SELECT user_id FROM zzsh_order.distribution_participant WHERE user_id=ANY($1::text[]) ORDER BY user_id FOR SHARE',[ids]);
  let policy:Awaited<ReturnType<typeof readDistributionPolicyRowInTransaction>>;try{policy=await readDistributionPolicyRowInTransaction(c,true);}catch(e){if(!(e instanceof SecurityApiError&&e.status===503))throw e;policy={knowledge:'UNKNOWN',policy:null,reason:'POLICY_SOURCE_NOT_CLOSED'};}
  const facts:PaymentReferralFacts[]=[];for(const[role,party]of [['RENTER_REFERRAL',order.renter_user_id],['OWNER_REFERRAL',order.owner_user_id]] as const){
   const own=(await c.query('SELECT leader_knowledge FROM zzsh_order.distribution_participant WHERE user_id=$1',[party])).rows[0],r=relations.find(r=>r.child_user_id===party),parent=r?.parent_user_id?await readDistributionParentInTransaction(c,r.parent_user_id):null;
   const knowledge=own?.leader_knowledge==='KNOWN_NONE'&&!r?'KNOWN_NONE':own?.leader_knowledge==='KNOWN_PARENT'&&r&&parent?.graphComplete?'KNOWN_PARENT':'UNKNOWN';
   facts.push({role,partyUserId:party,relation:{knowledge,id:r?.id??null,childUserId:party,parentUserId:r?.parent_user_id??null,sourceDigest:r?.source_digest??null},beneficiary:parent?.parent?{userId:parent.parent.user_id,active:parent.ownerActive,eligibility:parent.parent.eligibility,commissionFrozen:parent.parent.commission_frozen??null,levelCode:parent.parent.level_code}:null});
  }
  const mode=order.quote_snapshot?.schemaVersion===2?order.quote_snapshot?.pricingInputs?.compatibility?.rentalMode:null;let estimate:null|{baseCents:string;sourceDigest:string}=null;try{const amount=order.quote_snapshot?.platformFullProfit;if(amount?.currency==='CNY'&&amount.unit==='yuan'&&amount.scale===2)estimate={baseCents:sourceYuanToCents(amount.amount),sourceDigest:sha(canonicalize({definition:'QUOTE_PLATFORM_FULL_PROFIT_ESTIMATE_V1',quote:withoutContentHash(order.quote_snapshot),...(order.quote_snapshot.contentHash===undefined?{}:{listingHash:order.quote_snapshot.contentHash})}))};}catch(e){if(!(e instanceof SecurityApiError&&e.status===400))throw e;}
  const transactionId=(await c.query('SELECT pg_current_xact_id()::text AS id')).rows[0]?.id;if(typeof transactionId!=='string'||!/^[1-9]\d*$/.test(transactionId))throw conflict('Original payment transaction unavailable');
  const value=Object.freeze({orderId});prepared.set(value,{client:c,transactionId,input:{orderId,gameId:order.game_id,currency:order.currency,admissionId:admission.id,admissionRevision:String(admission.revision),origin:'NATIVE',accountMode:['ordinary','custom','fast'].includes(mode)?mode:null,estimate,policy:policy.policy?{versionId:policy.policy.versionId,digest:policy.policy.digest,config:policy.policy.config}:null,facts}});return value;
 }
 async function payment(c:PoolClient,orderId:string,confirmationId:string){await resource(c);const p=(await c.query(`SELECT p.id,p.order_id,p.source,p.merchant_scope_id,p.provider_transaction_id,p.merchant_order_no,p.amount_cents::text AS amount_cents,p.currency,to_char(p.provider_paid_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') AS provider_paid_at,to_char(p.accepted_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') AS accepted_at FROM zzsh_order.payment_confirmation p JOIN zzsh_order.rental_order o ON o.id=p.order_id AND o.paid_confirmation_id=p.id WHERE p.id=$1 AND p.order_id=$2 AND p.disposition='APPLIED'`,[confirmationId,orderId])).rows[0];if(!p)throw conflict('Basis requires original APPLIED payment binding');return{row:p,digest:sha(canonicalize(p))};}
 async function record(c:PoolClient,value:Prepared,confirmationId:string,requestId:string){const proof=prepared.get(value);if(!proof||proof.client!==c)throw conflict('Payment basis was not prepared on this transaction');if((await c.query('SELECT pg_current_xact_id()::text AS id')).rows[0]?.id!==proof.transactionId)throw conflict('Payment basis belongs to a previous transaction');const p=await payment(c,value.orderId,confirmationId),existing=(await c.query('SELECT canonical_basis,basis_digest FROM zzsh_order.payment_distribution_basis WHERE order_id=$1 AND payment_confirmation_id=$2',[value.orderId,confirmationId])).rows[0];if(existing)return readOriginalPaymentDistributionBasis({...JSON.parse(existing.canonical_basis),digest:existing.basis_digest},{orderId:value.orderId,confirmationId,paymentDigest:p.digest});
  const basis=freezePaymentDistributionBasis({...proof.input,confirmationId,acceptedAt:p.row.accepted_at,paymentDigest:p.digest}),{digest:_,...body}=basis,canonical=canonicalize(body);await c.query(`INSERT INTO zzsh_order.payment_distribution_basis(id,order_id,payment_confirmation_id,admission_id,admission_revision,canonical_basis,basis_digest) VALUES($1,$2,$3,$4,$5,$6,$7)`,['distribution_basis_'+sha(value.orderId).slice(0,40),value.orderId,confirmationId,basis.admissionId,basis.admissionRevision,canonical,basis.digest]);await recordAudit(c,{actorType:'system',actorId:'payment-distribution-basis',action:'distribution.payment.basis.frozen',objectType:'payment_distribution_basis',objectId:value.orderId,requestId,outcome:'SUCCESS',details:{confirmationId,basisDigest:basis.digest,policyVersion:basis.policyVersion,roles:basis.roles.map(r=>({role:r.role,status:r.status}))}});return{knowledge:'KNOWN' as const,basis};
 }
 async function readOriginal(c:PoolClient,orderId:string,confirmationId:string){const p=await payment(c,orderId,confirmationId),row=(await c.query('SELECT canonical_basis,basis_digest FROM zzsh_order.payment_distribution_basis WHERE order_id=$1 AND payment_confirmation_id=$2',[orderId,confirmationId])).rows[0];return readOriginalPaymentDistributionBasis(row?{...JSON.parse(row.canonical_basis),digest:row.basis_digest} as PaymentDistributionBasis:null,{orderId,confirmationId,paymentDigest:p.digest});}
 return{prepare,record,readOriginal};
}
export type PaymentDistributionStore=ReturnType<typeof createPaymentDistributionStore>;
