import {createHash} from 'node:crypto';import type {Pool,PoolClient} from 'pg';
import {withTransaction,recordAudit,SecurityApiError} from '../auth/security-core';import {canonicalize} from '../supply/content-hash';import {conflict,invalid,notFound} from '../supply/supply-util';
import {createPaymentDistributionStore} from './distribution-payment-store';import {prepareAccrualFromFrozenPayment,type CompletedDistributionFacts} from './distribution-accrual';import {transitionRentalEarning,earningEconomicKey,type RentalEarning,type EarningLedgerPlan} from './distribution-mechanism';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
function originalOutcome(receipt:any,root:RentalEarning,action:'SETTLE'|'REVOKE'|'RECOVER'){
 const version=String(receipt.result_version),expected=String(receipt.expected_version),event=receipt.finance_event_id;
 if(receipt.earning_id!==root.id||receipt.action!==action||!/^[1-9]\d{0,18}$/.test(version)||!/^[1-9]\d{0,18}$/.test(expected)||BigInt(version)!==BigInt(expected)+1n||BigInt(version)>BigInt(root.version)||typeof receipt.source_digest!=='string'||!/^[0-9a-f]{64}$/.test(receipt.source_digest)||event!==null&&(typeof event!=='string'||!event)||action!=='REVOKE'&&event===null)throw conflict('Original earning transition receipt is inconsistent');
 const state=action==='SETTLE'?'SETTLED':action==='REVOKE'&&event===null?'RECOVERY_REQUIRED':'REVOKED',fundsDisposition=state==='RECOVERY_REQUIRED'?'SETTLED':state,recoveryRequiredCents=state==='RECOVERY_REQUIRED'?root.amountCents:null;
 if(state==='RECOVERY_REQUIRED'&&BigInt(root.amountCents)<=0n||version===root.version&&(root.state!==state||root.fundsDisposition!==fundsDisposition||root.recoveryRequiredCents!==recoveryRequiredCents))throw conflict('Original outcome differs from the exact current transition');
 return{earningId:root.id,action,version,state,fundsDisposition,recoveryRequiredCents,financeEventId:event,sourceDigest:receipt.source_digest};
}
type Scope={resourceSet:string;resourceOid:number;approvalDigest:string;allowedOrderIds:readonly string[]};
function seed(row:any):RentalEarning{
 if(sha(row.canonical_seed)!==row.seed_digest)throw conflict('Original earning source digest differs');
 const original=JSON.parse(row.canonical_seed),source={kind:'NATIVE_RENTAL_REFERRAL',type:'NATIVE',system:'zzsh',entity:'rental_order',id:row.order_id} as const;
 const economicKey=earningEconomicKey(source,row.beneficiary_user_id,row.beneficiary_role);
 if(original.id!==row.id||row.economic_root_id!==row.id||row.economic_key!==economicKey||original.economicKey!==economicKey
  ||original.role!==row.beneficiary_role||original.beneficiaryUserId!==row.beneficiary_user_id
  ||Object.entries(source).some(([key,value])=>original.source?.[key]!==value)||original.source?.digest!==row.posting_digest
  ||original.amountCents!==String(row.amount_cents)||original.dueAt!==row.due_exact
  ||original.version!=='1'||original.state!=='PENDING'||original.fundsDisposition!=='PENDING'||original.recoveryRequiredCents!==null)
  throw conflict('Original earning seed and persisted source differ');
 return{...original,state:row.state,fundsDisposition:row.funds_disposition,version:String(row.version),recoveryRequiredCents:row.recovery_required_cents===null?null:String(row.recovery_required_cents)};
}
/** Candidate only: no HTTP outcome/amount fields, no automatic worker start. */
export function createDistributionEarningStore(scope:Scope){
 const payment=createPaymentDistributionStore(scope),allowed=new Set(scope.allowedOrderIds),name='zzsh_test_order_'+scope.resourceSet,role='zzsh_order_'+scope.resourceSet+'_r';
 async function ready(c:PoolClient){const r=(await c.query("SELECT d.oid,current_database() AS name,current_user AS role,shobj_description(d.oid,'pg_database') AS marker,to_regclass('zzsh_order.rental_referral_earning') IS NOT NULL AND to_regclass('zzsh_order.rental_referral_transition') IS NOT NULL AS complete FROM pg_database d WHERE datname=current_database()")).rows[0];if(!r||Number(r.oid)!==scope.resourceOid||r.name!==name||r.role!==role||r.marker!=='zzsh:order-reservation-test:v1'||!r.complete)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Typed earning schema/resource not installed');}
 async function orderLock(c:PoolClient,orderId:string){if(!allowed.has(orderId))throw notFound();await c.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",['zzsh:earning-order:'+orderId]);}
 async function wallet(c:PoolClient,userId:string){const covered=(await c.query('SELECT 1 FROM zzsh_order.wallet_coverage WHERE user_id=$1',[userId])).rowCount;if(!covered)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Wallet origin coverage not closed');const r=(await c.query(`SELECT ledger_revision::text AS revision,COALESCE((SELECT sum(credit_cents-debit_cents) FROM zzsh_order.settlement_ledger_entry WHERE counterparty_user_id=$1 AND account_code IN('OWNER_AVAILABLE','WALLET_AVAILABLE')),0)::text AS available FROM zzsh_order.wallet_revision WHERE user_id=$1`,[userId])).rows[0];if(!r||BigInt(r.available)<0n)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Wallet requires reconciliation');return r;}
 async function append(c:PoolClient,root:RentalEarning,plan:EarningLedgerPlan,revision:string){const eventId='earning_event_'+sha(canonicalize([root.economicKey,plan.kind])).slice(0,40);await c.query('INSERT INTO zzsh_order.finance_event(id,economic_root_id,kind,subject_user_id,expected_ledger_revision) VALUES($1,$2,$3,$4,$5)',[eventId,root.id,plan.kind,root.beneficiaryUserId,revision]);for(const[n,line]of plan.lines.entries())await c.query(`INSERT INTO zzsh_order.settlement_ledger_entry(id,finance_event_id,line_no,account_code,debit_cents,credit_cents,counterparty_user_id,source_payment_confirmation_id,details) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)`,['earning_line_'+sha(canonicalize([eventId,n+1])).slice(0,40),eventId,n+1,line.accountCode,line.debitCents,line.creditCents,line.counterpartyUserId,null,JSON.stringify({earningId:root.id,earningRole:root.role,scope:'LOCAL_CONTROLLED'})]);return eventId;}
 async function posting(c:PoolClient,orderId:string){const row=(await c.query(`SELECT p.id,p.order_id,p.payment_confirmation_id,p.version_hash,p.early,p.manual_reason,p.captured_cents::text,p.owner_net_cents::text,p.renter_refund_cents::text,p.platform_contribution_cents::text,p.compensation_fee_cents::text,to_char(p.posted_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') AS posted_at FROM zzsh_order.settlement_posting p WHERE order_id=$1`,[orderId])).rows[0];if(!row)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Original completed posting unavailable');const facts:CompletedDistributionFacts={origin:'NATIVE',orderId,confirmationId:row.payment_confirmation_id,postingId:row.id,postingDigest:sha(canonicalize(row)),postedAt:row.posted_at,classification:row.early?'EARLY':'NORMAL',calculationMode:row.manual_reason===null?'SYSTEM':'MANUAL',capturedCents:row.captured_cents,ownerNetCents:row.owner_net_cents,renterRefundCents:row.renter_refund_cents,platformContributionCents:row.platform_contribution_cents,compensationFeeCents:row.compensation_fee_cents};return{row,facts};}
 async function accrue(pool:Pool,orderId:string,requestId:string){return withTransaction(pool,async c=>{
  await ready(c);await orderLock(c,orderId);const completed=await posting(c,orderId),original=await payment.readOriginal(c,orderId,completed.facts.confirmationId),allocation=prepareAccrualFromFrozenPayment(original.basis,completed.facts);if(allocation.knowledge==='UNKNOWN')return allocation;
  await c.query('SELECT id FROM zzsh_auth_user."user" WHERE id=ANY($1::text[]) ORDER BY id FOR UPDATE',[[...new Set(allocation.items.map(i=>i.beneficiaryUserId))]]);const results=[];
  for(const item of allocation.items){const found=(await c.query(`SELECT e.*,to_char(e.due_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') AS due_exact FROM zzsh_order.rental_referral_earning e WHERE economic_key=$1 FOR UPDATE`,[item.economicKey])).rows[0];if(found){if(found.basis_digest!==item.basisDigest||found.posting_digest!==item.postingDigest||String(found.amount_cents)!==item.amountCents||found.due_exact!==item.dueAt)throw conflict('Original economic event has different frozen earning facts');results.push({root:seed(found),replayed:true});continue;}
   const w=await wallet(c,item.beneficiaryUserId),root:RentalEarning={id:'earning_'+sha(item.economicKey),economicKey:item.economicKey,source:{kind:'NATIVE_RENTAL_REFERRAL',type:'NATIVE',system:'zzsh',entity:'rental_order',id:orderId,digest:item.postingDigest,eventAt:completed.facts.postedAt},beneficiaryUserId:item.beneficiaryUserId,role:item.role,policyVersion:item.policyVersion,policyDigest:original.basis!.policyDigest!,baseDigest:allocation.digest,relationDigest:item.relationDigest,amountCents:item.amountCents,dueAt:item.dueAt,fingerprint:sha(canonicalize(item)),state:'PENDING',fundsDisposition:'PENDING',recoveryRequiredCents:null,version:'1'},canonical=canonicalize(root);
   await c.query(`INSERT INTO zzsh_order.finance_economic_root(id,basis_id,source_kind,source_type,source_system,source_entity,source_id,subject_user_id,beneficiary_role,policy_version,source_digest) VALUES($1,NULL,'NATIVE_RENTAL_REFERRAL','NATIVE','zzsh','rental_order',$2,$3,$4,$5,$6)`,[root.id,orderId,root.beneficiaryUserId,root.role,root.policyVersion,item.postingDigest]);
   await c.query(`INSERT INTO zzsh_order.rental_referral_earning(id,economic_root_id,economic_key,order_id,payment_confirmation_id,posting_id,beneficiary_user_id,beneficiary_role,amount_cents,due_at,basis_digest,posting_digest,canonical_seed,seed_digest,state,funds_disposition,version) VALUES($1,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'PENDING','PENDING',1)`,[root.id,root.economicKey,orderId,completed.facts.confirmationId,completed.facts.postingId,root.beneficiaryUserId,root.role,root.amountCents,root.dueAt,item.basisDigest,item.postingDigest,canonical,sha(canonical)]);
   const n=root.amountCents,lines=BigInt(n)===0n?[]:[{accountCode:'DISTRIBUTION_EXPENSE',debitCents:n,creditCents:'0',counterpartyUserId:null},{accountCode:'WALLET_PENDING_EARNINGS',debitCents:'0',creditCents:n,counterpartyUserId:root.beneficiaryUserId}],eventId=await append(c,root,{kind:'EARNING_PENDING',rootId:root.id,subjectUserId:root.beneficiaryUserId,lines},w.revision);await c.query(`INSERT INTO zzsh_order.rental_referral_transition(id,earning_id,action,expected_version,result_version,finance_event_id,source_digest) VALUES($1,$2,'ACCRUE',0,1,$3,$4)`,['earning_transition_'+sha(root.id+':ACCRUE').slice(0,40),root.id,eventId,item.postingDigest]);await recordAudit(c,{actorType:'system',actorId:'distribution-accrual',action:'distribution.earning.pending',objectType:'rental_referral_earning',objectId:root.id,requestId,outcome:'SUCCESS',details:{orderId,role:root.role,basisDigest:item.basisDigest,postingDigest:item.postingDigest}});results.push({root,replayed:false});
  }await c.query('SET CONSTRAINTS ALL IMMEDIATE');return{knowledge:'KNOWN' as const,items:results};
 });}
 /** Reversal source is an approved append-only fact, never arbitrary client amounts. */
 async function transition(pool:Pool,earningId:string,action:'SETTLE'|'REVOKE'|'RECOVER',expectedVersion:string,requestId:string,reversalSourceId?:string){if(!['SETTLE','REVOKE','RECOVER'].includes(action)||!/^[1-9]\d{0,18}$/.test(expectedVersion))throw invalid('Original earning action/version required');return withTransaction(pool,async c=>{
  await ready(c);const hint=(await c.query('SELECT order_id,beneficiary_user_id FROM zzsh_order.rental_referral_earning WHERE id=$1',[earningId])).rows[0];if(!hint)throw notFound();await orderLock(c,hint.order_id);await c.query('SELECT id FROM zzsh_auth_user."user" WHERE id=$1 FOR UPDATE',[hint.beneficiary_user_id]);const row=(await c.query(`SELECT e.*,to_char(e.due_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') AS due_exact FROM zzsh_order.rental_referral_earning e WHERE id=$1 FOR UPDATE`,[earningId])).rows[0],root=seed(row),receipt=(await c.query('SELECT * FROM zzsh_order.rental_referral_transition WHERE earning_id=$1 AND action=$2',[earningId,action])).rows[0];
  if(receipt){if(action!=='SETTLE'&&receipt.reversal_source_id!==reversalSourceId)throw conflict('Original reversal source changed');return{root,replayed:true,receipt,originalResult:originalOutcome(receipt,root,action)};}if(root.version!==expectedVersion)throw conflict('Earning version changed');let reversal=null;if(action!=='SETTLE'){if(!reversalSourceId)throw invalid('Original reversal source required');reversal=(await c.query('SELECT * FROM zzsh_order.rental_referral_reversal_source WHERE id=$1 AND earning_id=$2',[reversalSourceId,earningId])).rows[0];if(!reversal)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Original reversal source unavailable');if(reversal.scope!=='LOCAL_CONTROLLED'||reversal.approval_digest!==scope.approvalDigest||reversal.basis_digest!==row.basis_digest||String(reversal.amount_cents)!==root.amountCents||sha(reversal.canonical_source)!==reversal.source_digest||reversal.canonical_source!==canonicalize({schema:'rental-referral-reversal.v1',scope:'LOCAL_CONTROLLED',earningId,basisDigest:row.basis_digest,amountCents:root.amountCents}))throw conflict('Reversal source does not bind original earning');}
  const clock=(await c.query("SELECT date_trunc('milliseconds',clock_timestamp()) AS now,clock_timestamp()>=$1::timestamptz AS due",[root.dueAt])).rows[0];if(action==='SETTLE'&&root.state==='PENDING'&&!clock.due)throw conflict('Earning is not due');const w=await wallet(c,root.beneficiaryUserId);
  // PG compares the original microsecond due_at; the existing pure state machine uses milliseconds.
  let changed;
  if(action==='RECOVER'){
   if(root.state!=='RECOVERY_REQUIRED'||root.fundsDisposition!=='SETTLED'||root.recoveryRequiredCents!==root.amountCents||BigInt(root.amountCents)<=0n)throw conflict('Original settled recovery obligation required');
   const original=(await c.query("SELECT reversal_source_id,finance_event_id FROM zzsh_order.rental_referral_transition WHERE earning_id=$1 AND action='REVOKE'",[earningId])).rows[0];if(!original||original.reversal_source_id!==reversalSourceId||original.finance_event_id!==null)throw conflict('Original outstanding reversal receipt required');
   if(BigInt(w.available)<BigInt(root.amountCents))throw conflict('Original recovery still has insufficient available funds');
   changed={root:{...root,state:'REVOKED' as const,fundsDisposition:'REVOKED' as const,recoveryRequiredCents:null,version:(BigInt(root.version)+1n).toString()},replayed:false,ledgerPlan:{kind:'EARNING_REVOKED' as const,rootId:root.id,subjectUserId:root.beneficiaryUserId,lines:[{accountCode:'WALLET_AVAILABLE',debitCents:root.amountCents,creditCents:'0',counterpartyUserId:root.beneficiaryUserId},{accountCode:'DISTRIBUTION_EXPENSE',debitCents:'0',creditCents:root.amountCents,counterpartyUserId:null}]}};
  }else changed=transitionRentalEarning({...root,dueAt:new Date(root.dueAt).toISOString()},action,expectedVersion,new Date(clock.now).toISOString(),w.available);
  if(changed.replayed)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Original earning transition receipt unavailable');const next={...changed.root,dueAt:root.dueAt};const eventId=changed.ledgerPlan?await append(c,next,changed.ledgerPlan,w.revision):null;
  const updated=await c.query('UPDATE zzsh_order.rental_referral_earning SET state=$2,funds_disposition=$3,version=$4,recovery_required_cents=$5 WHERE id=$1 AND version=$6',[earningId,next.state,next.fundsDisposition,next.version,next.recoveryRequiredCents,expectedVersion]);if(updated.rowCount!==1)throw conflict('Earning CAS changed');await c.query(`INSERT INTO zzsh_order.rental_referral_transition(id,earning_id,action,expected_version,result_version,finance_event_id,reversal_source_id,source_digest) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,['earning_transition_'+sha(earningId+':'+action).slice(0,40),earningId,action,expectedVersion,next.version,eventId,reversal?.id??null,reversal?.source_digest??row.seed_digest]);await recordAudit(c,{actorType:'system',actorId:'distribution-transition',action:'distribution.earning.'+action.toLowerCase(),objectType:'rental_referral_earning',objectId:earningId,requestId,outcome:'SUCCESS',details:{before:root.state,after:next.state,version:next.version,reversalSourceId:reversal?.id??null}});await c.query('SET CONSTRAINTS ALL IMMEDIATE');return{root:next,replayed:false,originalResult:originalOutcome({earning_id:earningId,action,expected_version:expectedVersion,result_version:next.version,finance_event_id:eventId,source_digest:reversal?.source_digest??row.seed_digest},next,action)};
 });}
 return{accrue,transition};
}


