import type {Pool,PoolClient} from 'pg';import {createHash} from 'node:crypto';
import {withTransaction,recordAudit,SecurityApiError} from '../auth/security-core';import {assertAdminContextInTransaction} from '../auth/auth-security';import {loadEffectiveAdminAccess,hasPermission,requirePermission} from '../auth/admin-authorization';
import {canonicalize} from '../supply/content-hash';import {ensureOnlyFields,invalid,conflict,forbidden,withIdempotency,fingerprintRequest} from '../supply/supply-util';
import {validateDistributionPolicy,type DistributionPolicyConfig} from './distribution-policy';
export const DISTRIBUTION_POLICY_PERMISSION={read:'personal.distribution.policy.read',manage:'personal.distribution.policy.manage'} as const;
type Actor={userId:string;sessionId:string;requestId:string};const sha=(s:string)=>createHash('sha256').update(s).digest('hex'),scope='LOCAL_CONTROLLED';
async function authorize(c:PoolClient,actor:Actor,write=false){await assertAdminContextInTransaction(c,actor);const user=(await c.query('SELECT suspended FROM zzsh_auth_admin."user" WHERE id=$1',[actor.userId])).rows[0];if(!user||user.suspended)throw forbidden('Policy operator unavailable');const access=await loadEffectiveAdminAccess(c,actor.userId);if(write)requirePermission(access,DISTRIBUTION_POLICY_PERMISSION.manage);else if(!hasPermission(access,DISTRIBUTION_POLICY_PERMISSION.read)&&!hasPermission(access,DISTRIBUTION_POLICY_PERMISSION.manage))throw forbidden('Policy read permission required');}
async function resource(c:PoolClient){const r=(await c.query("SELECT d.oid,current_database() AS name,current_user AS role,shobj_description(d.oid,'pg_database') AS marker,to_regclass('zzsh_order.distribution_policy_version') IS NOT NULL AND to_regclass('zzsh_order.distribution_policy_head') IS NOT NULL AS complete FROM pg_database d WHERE d.datname=current_database()")).rows[0];
 const resources=[['zzsh_test_m2_auth_auth_compat',820148,'zzsh_m2_auth_compat_','zzsh:m2-auth-test:v1'],['zzsh_test_m2_auth_auth_compat_ui',833000,'zzsh_m2_auth_compat_ui_','zzsh:m2-auth-test:v1'],['zzsh_test_order_personal_finance',869754,'zzsh_order_personal_finance_','zzsh:order-reservation-test:v1']] as const;
 const expected=resources.find(([name,oid])=>r?.name===name&&Number(r.oid)===oid);if(!expected||r.marker!==expected[3]||![expected[2]+'r',expected[2]+'m'].includes(r.role)||!r.complete)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Distribution policy resource or schema unavailable');}

function decode(row:Record<string,any>){if(sha(row.canonical_config)!==row.config_digest)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Policy digest differs');let config:DistributionPolicyConfig;try{config=validateDistributionPolicy(JSON.parse(row.canonical_config));if(canonicalize(config)!==row.canonical_config)throw Error();}catch{throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Policy schema is not valid');}return{versionId:row.id,revision:String(row.revision),digest:row.config_digest,config,createdAt:new Date(row.created_at).toISOString()};}
/** Caller has verified its resource. Payment and relation writers may pin the immutable head. */
export async function readDistributionPolicyRowInTransaction(c:PoolClient,lockHead=false){const row=(await c.query(`SELECT v.* FROM zzsh_order.distribution_policy_head h JOIN zzsh_order.distribution_policy_version v ON v.id=h.current_version_id AND v.scope=h.scope AND v.revision=h.revision WHERE h.scope=$1${lockHead?' FOR SHARE OF h':''}`,[scope])).rows[0];return row?{knowledge:'KNOWN' as const,policy:decode(row)}:{knowledge:'UNKNOWN' as const,policy:null,reason:'POLICY_NOT_CONFIGURED'};}
const read=readDistributionPolicyRowInTransaction;
export async function readDistributionPolicy(pool:Pool,actor:Actor){return withTransaction(pool,async c=>{await authorize(c,actor);await resource(c);return read(c);});}
/** Domain-only current policy read; caller retains its own user/registration authorization. */
export async function readActiveDistributionPolicyInTransaction(c:PoolClient,lockHead=false){await resource(c);return read(c,lockHead);}
export async function configureDistributionPolicy(pool:Pool,actor:Actor,body:Record<string,unknown>,key:string){ensureOnlyFields(body,['expectedRevision','config','reason']);if(typeof body.expectedRevision!=='string'||!/^(0|[1-9]\d{0,18})$/.test(body.expectedRevision)||typeof body.reason!=='string'||body.reason.trim().length<3||body.reason.length>500||!body.config||typeof body.config!=='object'||Array.isArray(body.config))throw invalid('Exact revision, typed configuration and reason required');const config=validateDistributionPolicy(body.config as Record<string,unknown>),canonical=canonicalize(config),digest=sha(canonical);return withTransaction(pool,async c=>{
 await authorize(c,actor,true);await resource(c);return withIdempotency(c,{realm:'admin',principalId:actor.userId,operation:'distribution.policy.configure'},key,fingerprintRequest('distribution.policy.configure',scope,body),()=>authorize(c,actor,true),async()=>{
  await c.query("SELECT pg_advisory_xact_lock(hashtextextended('zzsh:distribution-policy:LOCAL_CONTROLLED',0))");const head=(await c.query('SELECT revision::text,current_version_id FROM zzsh_order.distribution_policy_head WHERE scope=$1 FOR UPDATE',[scope])).rows[0],before=head?head.revision:'0';if(before!==body.expectedRevision)throw conflict('Distribution policy changed; reload before saving');const revision=(BigInt(before)+1n).toString(),id='distribution_policy_'+sha(canonicalize([scope,revision,digest])).slice(0,40);
  await c.query(`INSERT INTO zzsh_order.distribution_policy_version(id,revision,scope,schema_version,canonical_config,config_digest,created_by_admin_id) VALUES($1,$2,$3,'distribution-policy.v1',$4,$5,$6)`,[id,revision,scope,canonical,digest,actor.userId]);if(head){const changed=await c.query('UPDATE zzsh_order.distribution_policy_head SET revision=$2,current_version_id=$3 WHERE scope=$1 AND revision=$4',[scope,revision,id,before]);if(changed.rowCount!==1)throw conflict('Policy head CAS failed');}else await c.query('INSERT INTO zzsh_order.distribution_policy_head(scope,revision,current_version_id) VALUES($1,$2,$3)',[scope,revision,id]);
  await recordAudit(c,{actorType:'admin',actorId:actor.userId,sessionId:actor.sessionId,requestId:actor.requestId,action:'distribution.policy.configured',objectType:'distribution_policy_version',objectId:id,outcome:'SUCCESS',reason:body.reason as string,details:{beforeRevision:before,revision,digest,scope}});await c.query('SET CONSTRAINTS ALL IMMEDIATE');return{status:200,body:await read(c)};
 });
});}


