import {createHash,createHmac,timingSafeEqual} from 'node:crypto';import type {Pool,PoolClient} from 'pg';import {withTransaction,recordAudit,SecurityApiError} from '../auth/security-core';
import {requireListingCursorKey,type ListingCursorKey} from '../supply/listing-cursor';
import {assertUserContextInTransaction,type UserContext} from '../auth/user-identity';import {canonicalize} from '../supply/content-hash';import {ensureOnlyFields,invalid,conflict,notFound,withIdempotency,fingerprintRequest} from '../supply/supply-util';
import {planInvitationBinding,type InvitationRelation} from './distribution-mechanism';import {readActiveDistributionPolicyInTransaction,type LocalDistributionScope} from './distribution-policy-store';
type Actor=UserContext&{requestId:string};const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
/** Caller holds the graph lock. Read only the proposed parent's ancestry, not the whole registry. */
export async function readDistributionParentInTransaction(c:PoolClient,parentId:string){
 const parent=(await c.query(`SELECT p.*,u.suspended,s.account_status FROM zzsh_order.distribution_participant p
  JOIN zzsh_auth_user."user" u ON u.id=p.user_id LEFT JOIN zzsh_iam.user_identity_state s ON s.user_id=p.user_id WHERE p.user_id=$1`,[parentId])).rows[0];
 const ancestry=(await c.query(`WITH RECURSIVE chain(user_id,path,cyclic) AS (
  SELECT $1::text,ARRAY[$1::text],false UNION ALL
  SELECT r.parent_user_id,c.path||r.parent_user_id,r.parent_user_id=ANY(c.path)
  FROM chain c JOIN zzsh_order.invitation_relation r ON r.child_user_id=c.user_id AND r.type='DISTRIBUTION_LEADER' WHERE NOT c.cyclic
 ) SELECT c.user_id,c.cyclic,p.leader_knowledge,r.parent_user_id,r.policy_version_id
 FROM chain c LEFT JOIN zzsh_order.distribution_participant p ON p.user_id=c.user_id
 LEFT JOIN zzsh_order.invitation_relation r ON r.child_user_id=c.user_id AND r.type='DISTRIBUTION_LEADER'`,[parentId])).rows;
 const graphComplete=ancestry.length>0&&ancestry.every(r=>!r.cyclic&&(r.leader_knowledge==='KNOWN_NONE'&&!r.parent_user_id||r.leader_knowledge==='KNOWN_PARENT'&&Boolean(r.parent_user_id)));
 const relations:InvitationRelation[]=ancestry.filter(r=>r.parent_user_id).map(r=>({type:'DISTRIBUTION_LEADER',childUserId:r.user_id,parentUserId:r.parent_user_id,policyVersion:r.policy_version_id}));
 return{parent,graphComplete,relations,ownerActive:parent&&parent.account_status?parent.suspended===false&&parent.account_status==='ACTIVE':null};
}
export type InviteesQuery={limit:number;cursor:string|null;type:'ALL'|'INVITER'|'DISTRIBUTION_LEADER'};
export function parseInviteesQuery(q:URLSearchParams):InviteesQuery{
 for(const field of q.keys())if(!['limit','cursor','type'].includes(field)||q.getAll(field).length!==1)throw invalid('Unsupported invitation list filter');
 const limit=q.get('limit')??'20',type=q.get('type')??'ALL';if(!/^(?:[1-9]|[1-4]\d|50)$/.test(limit)||!['ALL','INVITER','DISTRIBUTION_LEADER'].includes(type))throw invalid('Invitation list filter invalid');
 return{limit:Number(limit),type:type as InviteesQuery['type'],cursor:q.get('cursor')};
}
type InviteesBinding={userId:string;sessionHash:string;snapshotVersion:string;type:InviteesQuery['type']};
export function encodeInviteesCursor(after:string,binding:InviteesBinding,key:ListingCursorKey|undefined){
 requireListingCursorKey(key);const bytes=Buffer.from(canonicalize({audience:'zzsh:invited-relations:v1',keyId:key.keyId,...binding,after})).toString('base64url');return bytes+'.'+createHmac('sha256',key.secret).update(bytes).digest('base64url');
}
export function decodeInviteesCursor(token:string,binding:InviteesBinding,key:ListingCursorKey|undefined):string{
 requireListingCursorKey(key);try{
  if(token.length>4096||!/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]{43}$/.test(token))throw Error();const[bytes,sig]=token.split('.') as [string,string],actual=Buffer.from(sig,'base64url'),expected=createHmac('sha256',key.secret).update(bytes).digest();
  if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw Error();const value=JSON.parse(Buffer.from(bytes,'base64url').toString());
  if(value.audience!=='zzsh:invited-relations:v1'||value.keyId!==key.keyId||Object.keys(value).length!==7||typeof value.after!=='string'||!value.after||value.after.length>128)throw Error();
  for(const[k,v]of Object.entries(binding))if(value[k]!==v)throw conflict('Invitation identity or snapshot changed; reload first page');return value.after;
 }catch(e){if(e instanceof SecurityApiError&&e.status===409)throw e;throw invalid('Invalid invitation cursor');}
}
/** Counts mean relations, not unique people: INVITER and leader are distinct provenances. */
export async function readMyInvitees(pool:Pool,actor:Actor,q:InviteesQuery,key:ListingCursorKey|undefined){return withTransaction(pool,async c=>{
 await installed(c);await c.query("SELECT pg_advisory_xact_lock(hashtextextended('zzsh:invitation-graph:v1',0))");await assertUserContextInTransaction(c,actor);
 const p=(await c.query('SELECT invitees_knowledge,revision::text FROM zzsh_order.distribution_participant WHERE user_id=$1',[actor.userId])).rows[0];
 if(!p){if(q.cursor)throw conflict('Invitation identity or snapshot changed; reload first page');return{subjectId:actor.userId,knowledge:'UNKNOWN',type:q.type,snapshotVersion:null,items:[],count:null,mappedRelationCount:null,countMeaning:'RELATIONS_NOT_UNIQUE_PEOPLE',nextCursor:null,reason:'INVITEE_MAPPING_NOT_CLOSED'};}
 const aggregate=(await c.query(`SELECT count(*)::text AS count,encode(sha256(convert_to(COALESCE(string_agg(id||':'||source_digest,',' ORDER BY id),''),'UTF8')),'hex') AS digest FROM zzsh_order.invitation_relation WHERE parent_user_id=$1 AND($2='ALL' OR type=$2)`,[actor.userId,q.type])).rows[0];
 const binding={userId:actor.userId,sessionHash:sha(actor.sessionId),snapshotVersion:sha(canonicalize([p.revision,p.invitees_knowledge,aggregate.digest])),type:q.type},after=q.cursor?decodeInviteesCursor(q.cursor,binding,key):null;
 const rows=(await c.query(`SELECT r.id,r.type,u.name AS nickname,r.bound_at,r.source_type FROM zzsh_order.invitation_relation r JOIN zzsh_auth_user."user" u ON u.id=r.child_user_id WHERE r.parent_user_id=$1 AND($2='ALL' OR r.type=$2) AND($3::text IS NULL OR r.id COLLATE "C"<$3 COLLATE "C") ORDER BY r.id COLLATE "C" DESC LIMIT $4`,[actor.userId,q.type,after,q.limit+1])).rows;
 const visible=rows.slice(0,q.limit),last=visible.at(-1),complete=p.invitees_knowledge==='KNOWN';return{subjectId:actor.userId,knowledge:complete?'KNOWN':'UNKNOWN',type:q.type,snapshotVersion:binding.snapshotVersion,count:complete?aggregate.count:null,mappedRelationCount:aggregate.count,countMeaning:'RELATIONS_NOT_UNIQUE_PEOPLE',...(!complete?{reason:'INVITEE_MAPPING_NOT_CLOSED'}:{}),items:visible.map(r=>({id:r.id,type:r.type,nickname:r.nickname,boundAt:r.source_type==='LEGACY_MYSQL'?null:new Date(r.bound_at).toISOString(),boundAtKnowledge:r.source_type==='LEGACY_MYSQL'?'UNKNOWN':'KNOWN',sourceType:r.source_type})),nextCursor:rows.length>q.limit&&last?encodeInviteesCursor(last.id,binding,key):null};
});}
async function installed(c:PoolClient){if(!(await c.query(`SELECT to_regclass('zzsh_order.distribution_participant') IS NOT NULL AND to_regclass('zzsh_order.distribution_invite_code') IS NOT NULL AND to_regclass('zzsh_order.invitation_relation') IS NOT NULL AS complete`)).rows[0]?.complete)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Invitation sources are not installed');}
function relationProjection(p:Record<string,any>|undefined,rows:Record<string,any>[],type:'INVITER'|'DISTRIBUTION_LEADER'){const r=rows.find(r=>r.type===type),knowledge=p?.[type==='INVITER'?'inviter_knowledge':'leader_knowledge'];if(r&&knowledge==='KNOWN_PARENT')return{knowledge:'KNOWN_PARENT',relation:{id:r.id,parentUserId:r.parent_user_id,sourceType:r.source_type,boundAt:r.source_type==='LEGACY_MYSQL'?null:new Date(r.bound_at).toISOString(),boundAtKnowledge:r.source_type==='LEGACY_MYSQL'?'UNKNOWN':'KNOWN'}};if(!r&&knowledge==='KNOWN_NONE')return{knowledge:'KNOWN_NONE',relation:null};return{knowledge:'UNKNOWN',relation:null,reason:'RELATION_SOURCE_NOT_CLOSED'};}
export async function readMyLeaderBindingReceipt(pool:Pool,actor:Actor,key:string){
 if(!/^[A-Za-z0-9._:-]{1,128}$/.test(key))throw invalid('Original binding receipt key required');
 return withTransaction(pool,async c=>{await assertUserContextInTransaction(c,actor);await installed(c);
  const row=(await c.query('SELECT response_body AS body FROM zzsh_supply.idempotency_record WHERE scope_key=$1 AND key=$2',[JSON.stringify(['user',actor.userId,'distribution.leader.bind',null]),key])).rows[0];
  if(!row)return{subjectId:actor.userId,knowledge:'UNKNOWN',receipt:null};
  const relation=row.body?.relation;if(!relation||relation.childUserId!==actor.userId||relation.type!=='DISTRIBUTION_LEADER'||typeof relation.id!=='string')throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Original binding receipt cannot be verified');
  const source=(await c.query("SELECT id FROM zzsh_order.invitation_relation WHERE id=$1 AND child_user_id=$2 AND parent_user_id=$3 AND type='DISTRIBUTION_LEADER'",[relation.id,actor.userId,relation.parentUserId])).rows[0];
  if(!source)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Original binding relation is unavailable');
  return{subjectId:actor.userId,knowledge:'KNOWN',receipt:row.body};
 });
}
export async function readMyInvitations(pool:Pool,actor:Actor,binding?:LocalDistributionScope){return withTransaction(pool,async c=>{await assertUserContextInTransaction(c,actor);await installed(c);const policy=await readActiveDistributionPolicyInTransaction(c,false,binding),p=(await c.query('SELECT * FROM zzsh_order.distribution_participant WHERE user_id=$1',[actor.userId])).rows[0],codes=(await c.query('SELECT display_code,source_type FROM zzsh_order.distribution_invite_code WHERE user_id=$1 ORDER BY id',[actor.userId])).rows,relations=(await c.query('SELECT * FROM zzsh_order.invitation_relation WHERE child_user_id=$1 ORDER BY type',[actor.userId])).rows;return{scope:'LOCAL_CONTROLLED',subjectId:actor.userId,policyKnowledge:policy.knowledge,policyVersion:policy.policy?.versionId??null,policyEnabled:policy.policy?.config.enabled??null,participant:{knowledge:p?'KNOWN':'UNKNOWN',eligibility:p?.eligibility??'UNKNOWN',levelCode:p?.level_code??null,revision:p?String(p.revision):null},ownCode:codes.length===1?{knowledge:'KNOWN',code:codes[0].display_code,sourceType:codes[0].source_type}:{knowledge:'UNKNOWN',code:null,reason:codes.length?'AMBIGUOUS_CODE_OWNER':'CODE_MAPPING_NOT_CLOSED'},inviter:relationProjection(p,relations,'INVITER'),leader:relationProjection(p,relations,'DISTRIBUTION_LEADER')};});}
/** Public binding changes only DISTRIBUTION_LEADER. INVITER stays a registration source. */
export async function bindMyDistributionLeader(pool:Pool,actor:Actor,body:Record<string,unknown>,key:string,binding?:LocalDistributionScope){ensureOnlyFields(body,['code','policyVersion','expectedParticipantRevision']);if(typeof body.code!=='string'||!/^[A-Za-z0-9_-]{1,30}$/.test(body.code)||typeof body.policyVersion!=='string'||typeof body.expectedParticipantRevision!=='string'||!/^[1-9]\d{0,18}$/.test(body.expectedParticipantRevision))throw invalid('Invitation code and exact server versions required');const input={code:body.code as string,policyVersion:body.policyVersion as string,expectedParticipantRevision:body.expectedParticipantRevision as string};return withTransaction(pool,async c=>{
 await installed(c);await c.query("SELECT pg_advisory_xact_lock(hashtextextended('zzsh:invitation-graph:v1',0))");const resolvedCode=(await c.query('SELECT * FROM zzsh_order.distribution_invite_code WHERE match_code=$1',[input.code.toUpperCase()])).rows[0];const ids=[...new Set([actor.userId,resolvedCode?.user_id].filter(Boolean))];const locked=(await c.query('SELECT id FROM zzsh_auth_user."user" WHERE id=ANY($1::text[]) ORDER BY id FOR UPDATE',[ids])).rows;if(locked.length!==ids.length)throw notFound();await assertUserContextInTransaction(c,actor);return withIdempotency(c,{realm:'user',principalId:actor.userId,operation:'distribution.leader.bind'},key,fingerprintRequest('distribution.leader.bind',undefined,body),()=>assertUserContextInTransaction(c,actor),async()=>{
  const policy=await readActiveDistributionPolicyInTransaction(c,false,binding);if(policy.knowledge!=='KNOWN'||!policy.policy.config.enabled)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Invitation policy unavailable');if(policy.policy.versionId!==body.policyVersion)throw conflict('Invitation policy changed');const child=(await c.query('SELECT * FROM zzsh_order.distribution_participant WHERE user_id=$1',[actor.userId])).rows[0];if(!child||child.leader_knowledge==='UNKNOWN')throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Original parent source is unknown');if(String(child.revision)!==body.expectedParticipantRevision)throw conflict('Participant changed');
  const code=resolvedCode;if(!code)throw notFound();if(!code.user_id)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Legacy code owner is not mapped');
  const {parent,ownerActive,graphComplete,relations}=await readDistributionParentInTransaction(c,code.user_id);
  const original=(await c.query("SELECT id,child_user_id,parent_user_id,policy_version_id FROM zzsh_order.invitation_relation WHERE type='DISTRIBUTION_LEADER' AND child_user_id=$1",[actor.userId])).rows[0];
  if(child.leader_knowledge==='KNOWN_PARENT'&&!original||child.leader_knowledge==='KNOWN_NONE'&&original)throw new SecurityApiError(503,'EVIDENCE_UNAVAILABLE','Original parent source is inconsistent');
  const relationRows=original?[...relations,{type:'DISTRIBUTION_LEADER' as const,childUserId:original.child_user_id,parentUserId:original.parent_user_id,policyVersion:original.policy_version_id}]:relations;
  const planned=planInvitationBinding({childUserId:actor.userId,type:'DISTRIBUTION_LEADER',code:input.code,policyVersion:input.policyVersion},{mode:'LOCAL_CONTROLLED',version:policy.policy.versionId,admittedSubjectIds:[actor.userId,code.user_id],allowedTypes:['DISTRIBUTION_LEADER'],binding:'SINGLE_IMMUTABLE_PARENT',codeCase:'ASCII_UPPER'},{childActive:true,eligible:true,codes:[{code:code.display_code,userId:code.user_id,active:true,ownerActive,ownerEligible:parent?parent.eligibility==='UNKNOWN'?null:parent.eligibility==='ELIGIBLE':null,sourceType:code.source_type==='LEGACY_MYSQL'?'LEGACY_MYSQL':'NATIVE'}],relations:relationRows,graphComplete});if(planned.replayed)return{status:200,body:{relation:{id:original.id,...planned.relation},replayed:true}};
  const id='leader_relation_'+sha(canonicalize([actor.userId,code.user_id])).slice(0,40),sourceDigest=sha(canonicalize({codeId:code.id,parentUserId:code.user_id,policyVersion:policy.policy.versionId}));await c.query(`INSERT INTO zzsh_order.invitation_relation(id,type,child_user_id,parent_user_id,policy_version_id,source_type,source_ref,source_digest) VALUES($1,'DISTRIBUTION_LEADER',$2,$3,$4,'LOCAL_CONTROLLED',$5,$6)`,[id,actor.userId,code.user_id,policy.policy.versionId,'self-bind:'+key,sourceDigest]);const changed=await c.query("UPDATE zzsh_order.distribution_participant SET leader_knowledge='KNOWN_PARENT',revision=revision+1 WHERE user_id=$1 AND revision=$2",[actor.userId,body.expectedParticipantRevision]);if(changed.rowCount!==1)throw conflict('Participant CAS changed');await recordAudit(c,{actorType:'user',actorId:actor.userId,sessionId:actor.sessionId,requestId:actor.requestId,action:'distribution.leader.bound',objectType:'invitation_relation',objectId:id,outcome:'SUCCESS',details:{sourceDigest,policyVersion:policy.policy.versionId}});await c.query('SET CONSTRAINTS ALL IMMEDIATE');return{status:200,body:{relation:{id,...planned.relation},replayed:false}};
 });
});}
