import {createHash} from 'node:crypto';
import type {PoolClient} from 'pg';
import {recordAudit} from '../auth/security-core';
import {authorizeFinanceMaintenance} from './personal-finance-maintenance';
import {canonicalize} from '../supply/content-hash';
import {legacyOwnerUserId} from '../supply/legacy-user-migration';
import {ensureOnlyFields,invalid,conflict,withIdempotency,fingerprintRequest} from '../supply/supply-util';
import {validateDistributionPolicy} from './distribution-policy';

type Actor={userId:string;sessionId:string;requestId:string};
type Counts={all:number;inPlan:number};
export type LegacyInvitationSubject={userId:string;legacyId:string;identitySourceDigest:string;userSource:Record<string,unknown>;qualificationSource:Record<string,unknown>;childCounts:{INVITER:Counts;DISTRIBUTION_LEADER:Counts}};
export type LegacyInvitationInput={schema:'legacy-invitations.v1';sourceSystem:'legacy_mysql_restore';policyVersionId:string;policyConfigDigest:string;subjects:LegacyInvitationSubject[];gradeMapping:{legacyGradeId:string;levelCode:string}[];sourceCodeMultiplicity:{matchCode:string;count:number}[]};
const sha=(s:string)=>createHash('sha256').update(s).digest('hex'),digest=/^[a-f0-9]{64}$/,operation='distribution.legacy-sources.import';
const id=(v:unknown)=>{const s=String(v);if(!/^[1-9]\d{0,18}$/.test(s))throw invalid('Exact legacy source id required');return s;};
const parent=(v:unknown)=>v===0||v==='0'?null:id(v);
const bit=(v:unknown)=>{if(v!==0&&v!==1)throw invalid('Exact legacy source flag required');return v===1;};
/** Pure source closure. No guessed grade/default, missing parent, code owner or total. */
export function prepareLegacyInvitationImport(input:LegacyInvitationInput,reviewedDigest:string){
 ensureOnlyFields(input as unknown as Record<string,unknown>,['schema','sourceSystem','policyVersionId','policyConfigDigest','subjects','gradeMapping','sourceCodeMultiplicity']);
 if(input.schema!=='legacy-invitations.v1'||input.sourceSystem!=='legacy_mysql_restore'||typeof input.policyVersionId!=='string'||!input.policyVersionId||!digest.test(input.policyConfigDigest)||!Array.isArray(input.subjects)||!input.subjects.length||input.subjects.length>5000||!Array.isArray(input.gradeMapping)||!Array.isArray(input.sourceCodeMultiplicity))throw invalid('Typed frozen legacy invitation input required');
 const bodyDigest=sha(canonicalize(input));if(!digest.test(reviewedDigest)||bodyDigest!==reviewedDigest)throw invalid('Invitation body differs from reviewed source packet');
 const bySource=new Map<string,LegacyInvitationSubject>(),byUser=new Set<string>(),codes=new Set<string>();
 const levels=new Map<string,string>();for(const mapping of input.gradeMapping){ensureOnlyFields(mapping,['legacyGradeId','levelCode']);const sourceId=id(mapping.legacyGradeId);if(levels.has(sourceId)||typeof mapping.levelCode!=='string'||!/^[A-Za-z][A-Za-z0-9_-]{0,63}$/.test(mapping.levelCode))throw invalid('Ambiguous source grade mapping');levels.set(sourceId,mapping.levelCode);}
 const multiplicity=new Map<string,number>();for(const row of input.sourceCodeMultiplicity){ensureOnlyFields(row,['matchCode','count']);if(typeof row.matchCode!=='string'||multiplicity.has(row.matchCode)||row.count!==1)throw conflict('Original code source is not globally unique');multiplicity.set(row.matchCode,row.count);}
 for(const s of input.subjects){ensureOnlyFields(s as unknown as Record<string,unknown>,['userId','legacyId','identitySourceDigest','userSource','qualificationSource','childCounts']);const legacyId=id(s.legacyId);if(bySource.has(legacyId)||byUser.has(s.userId)||s.userId!==legacyOwnerUserId(input.sourceSystem,'la_user',legacyId)||!digest.test(s.identitySourceDigest))throw invalid('Legacy identity tuple is ambiguous');if(!s.userSource||!s.qualificationSource||id(s.userSource.id)!==legacyId||id(s.qualificationSource.user_id)!==legacyId)throw invalid('Original user/qualification source tuple differs');
  const code=s.userSource.code;if(typeof code!=='string'||!/^[A-Za-z0-9_-]{1,30}$/.test(code)||codes.has(code.toUpperCase())||multiplicity.get(code.toUpperCase())!==1)throw conflict('Original code owner or ASCII source is ambiguous');codes.add(code.toUpperCase());
  bit(s.userSource.is_delete);bit(s.qualificationSource.is_delete);bit(s.qualificationSource.is_distribution);bit(s.qualificationSource.is_freeze);id(s.qualificationSource.id);if(!levels.has(id(s.qualificationSource.level_id)))throw invalid('Legacy grade lacks exact policy mapping');
  ensureOnlyFields(s.childCounts,['INVITER','DISTRIBUTION_LEADER']);for(const counts of Object.values(s.childCounts)){ensureOnlyFields(counts,['all','inPlan']);if(!Number.isSafeInteger(counts.all)||!Number.isSafeInteger(counts.inPlan)||counts.inPlan<0||counts.all<counts.inPlan)throw invalid('Original child closure counts invalid');}
  bySource.set(legacyId,s);byUser.add(s.userId);
 }
 if(multiplicity.size!==codes.size)throw invalid('Code source set differs from subject set');
 const relations:Array<{id:string;type:'INVITER'|'DISTRIBUTION_LEADER';childUserId:string;parentUserId:string;sourceRef:string;sourceDigest:string}>=[];
 for(const s of input.subjects)for(const[field,type]of [['inviter_id','INVITER'],['first_leader','DISTRIBUTION_LEADER']] as const){const sourceParent=parent(s.userSource[field]);if(sourceParent){const p=bySource.get(sourceParent);if(!p)throw conflict('Original nonzero parent is not mapped');if(p.userId===s.userId)throw conflict('Original self relation rejected');relations.push({id:'legacy_relation_'+sha(canonicalize([input.sourceSystem,s.legacyId,type])).slice(0,40),type,childUserId:s.userId,parentUserId:p.userId,sourceRef:input.sourceSystem+':la_user:'+s.legacyId+':'+field,sourceDigest:sha(canonicalize(s.userSource))});}}
 for(const type of ['INVITER','DISTRIBUTION_LEADER'] as const){const edges=new Map(relations.filter(r=>r.type===type).map(r=>[r.childUserId,r.parentUserId]));for(const start of edges.keys()){const seen=new Set<string>();for(let at:string|undefined=start;at;at=edges.get(at)){if(seen.has(at))throw conflict('Original invitation ancestry is cyclic');seen.add(at);}}}
 const subjects=input.subjects.map(s=>{const d=s.qualificationSource,eligible=bit(d.is_distribution)&&!bit(d.is_delete)&&!bit(s.userSource.is_delete),originalChildren=relations.filter(r=>r.parentUserId===s.userId);for(const type of ['INVITER','DISTRIBUTION_LEADER'] as const)if(s.childCounts[type].inPlan!==originalChildren.filter(r=>r.type===type).length)throw conflict('Mapped child source count differs from original relation set');return{...s,eligibility:eligible?'ELIGIBLE':'INELIGIBLE',commissionFrozen:bit(d.is_freeze),levelCode:levels.get(id(d.level_id))!,sourceRef:input.sourceSystem+':la_distribution:'+id(d.id),sourceDigest:sha(canonicalize(d)),inviterKnowledge:parent(s.userSource.inviter_id)?'KNOWN_PARENT':'KNOWN_NONE',leaderKnowledge:parent(s.userSource.first_leader)?'KNOWN_PARENT':'KNOWN_NONE',inviteesKnowledge:Object.values(s.childCounts).every(c=>c.all===c.inPlan)?'KNOWN':'UNKNOWN',codeId:'legacy_code_'+sha(canonicalize([input.sourceSystem,'la_user',s.legacyId])).slice(0,40),codeDigest:sha(canonicalize(s.userSource))};}).sort((a,b)=>a.userId<b.userId?-1:1);
 return{bodyDigest,key:'legacy-invitations-'+sha(canonicalize([input.sourceSystem,[...bySource.keys()].sort()])).slice(0,40),subjects,relations:relations.sort((a,b)=>a.id<b.id?-1:1)};
}
async function resource(c:PoolClient){const r=(await c.query("SELECT d.oid,current_database() AS name,current_user AS role,shobj_description(d.oid,'pg_database') AS marker,to_regclass('zzsh_order.distribution_participant') IS NOT NULL AND to_regclass('zzsh_order.distribution_policy_version') IS NOT NULL AND to_regclass('zzsh_order.invitation_relation') IS NOT NULL AND to_regclass('zzsh_order.distribution_invite_code') IS NOT NULL AS complete FROM pg_database d WHERE datname=current_database()")).rows[0];const admitted=[['zzsh_test_m2_auth_auth_compat_ui',833000,'zzsh_m2_auth_compat_ui_m','zzsh:m2-auth-test:v1'],['zzsh_test_order_personal_finance',869754,'zzsh_order_personal_finance_m','zzsh:order-reservation-test:v1']];if(!r||!admitted.some(([name,oid,role,marker])=>r.name===name&&Number(r.oid)===oid&&r.role===role&&r.marker===marker)||!r.complete)throw conflict('Reviewed legacy invitation maintenance resource/schema required');}
/** Caller owns one transaction including the separately reviewed four identity migrations.
 * No HTTP endpoint, new password, existing identity update, historical financial replay or live activation. */
export async function importReviewedLegacyInvitations(c:PoolClient,actor:Actor,input:LegacyInvitationInput,reviewedDigest:string){
 const plan=prepareLegacyInvitationImport(input,reviewedDigest);await resource(c);
 await c.query('SELECT s.id FROM zzsh_auth_admin.session s JOIN zzsh_auth_admin."user" u ON u.id=s."userId" JOIN zzsh_iam.admin_security a ON a.admin_user_id=u.id WHERE s.id=$1 AND u.id=$2 FOR SHARE OF s,u,a',[actor.sessionId,actor.userId]);
 const transaction=(await c.query('SELECT pg_current_xact_id_if_assigned()::text AS xid')).rows[0]?.xid;if(!transaction)throw conflict('Legacy source import requires an existing caller-owned transaction');
 await authorizeFinanceMaintenance(c,actor);await c.query('SET CONSTRAINTS ALL DEFERRED');await c.query("SELECT pg_advisory_xact_lock(hashtextextended('zzsh:invitation-graph:v1',0))");
 return withIdempotency(c,{realm:'admin',principalId:actor.userId,operation},plan.key,fingerprintRequest(operation,undefined,input),()=>authorizeFinanceMaintenance(c,actor),async()=>{
  const policy=(await c.query('SELECT canonical_config,config_digest FROM zzsh_order.distribution_policy_version WHERE id=$1',[input.policyVersionId])).rows[0];if(!policy||policy.config_digest!==input.policyConfigDigest||sha(policy.canonical_config)!==input.policyConfigDigest)throw conflict('Original immutable policy source differs');const config=validateDistributionPolicy(JSON.parse(policy.canonical_config));if(canonicalize(config)!==policy.canonical_config)throw conflict('Original policy canonical source invalid');for(const s of plan.subjects)if(!config.levels.some(l=>l.code===s.levelCode)||s.eligibility==='ELIGIBLE'&&!config.enabled)throw conflict('Legacy qualification policy source unavailable');
  for(const s of plan.subjects){await c.query('SELECT id FROM zzsh_auth_user."user" WHERE id=$1 FOR UPDATE',[s.userId]);const proof=(await c.query("SELECT 1 FROM zzsh_iam.audit_event WHERE object_id=$1 AND action='user.legacy_owner.migrated' AND outcome='SUCCESS' AND details->>'sourceSystem'=$2 AND details->>'sourceEntity'='la_user' AND details->>'legacyId'=$3 AND details->>'sourceDigest'=$4",[s.userId,input.sourceSystem,s.legacyId,s.identitySourceDigest])).rowCount;if(!proof)throw conflict('Original migrated identity tuple unavailable');}
  const ids=plan.subjects.map(s=>s.userId);if((await c.query('SELECT user_id FROM zzsh_order.distribution_participant WHERE user_id=ANY($1::text[])',[ids])).rowCount||(await c.query('SELECT id FROM zzsh_order.distribution_invite_code WHERE user_id=ANY($1::text[]) OR match_code=ANY($2::text[])',[ids,plan.subjects.map(s=>String(s.userSource.code).toUpperCase())])).rowCount||(await c.query('SELECT id FROM zzsh_order.invitation_relation WHERE child_user_id=ANY($1::text[])',[ids])).rowCount)throw conflict('Original participant, code or relation already exists; no override');
  for(const s of plan.subjects){await c.query(`INSERT INTO zzsh_order.distribution_participant(user_id,eligibility,commission_frozen,level_code,policy_version_id,revision,inviter_knowledge,leader_knowledge,invitees_knowledge,source_type,source_ref,source_digest) VALUES($1,$2,$3,$4,$5,1,$6,$7,$8,'LEGACY_MYSQL',$9,$10)`,[s.userId,s.eligibility,s.commissionFrozen,s.levelCode,input.policyVersionId,s.inviterKnowledge,s.leaderKnowledge,s.inviteesKnowledge,s.sourceRef,s.sourceDigest]);await c.query(`INSERT INTO zzsh_order.distribution_invite_code(id,user_id,display_code,source_type,source_system,source_entity,source_id,source_digest) VALUES($1,$2,$3,'LEGACY_MYSQL',$4,'la_user',$5,$6)`,[s.codeId,s.userId,s.userSource.code,input.sourceSystem,s.legacyId,s.codeDigest]);}
  for(const r of plan.relations)await c.query(`INSERT INTO zzsh_order.invitation_relation(id,type,child_user_id,parent_user_id,policy_version_id,source_type,source_ref,source_digest) VALUES($1,$2,$3,$4,$5,'LEGACY_MYSQL',$6,$7)`,[r.id,r.type,r.childUserId,r.parentUserId,input.policyVersionId,r.sourceRef,r.sourceDigest]);
  if((await c.query('SELECT pg_current_xact_id_if_assigned()::text AS xid')).rows[0]?.xid!==transaction)throw conflict('Original legacy migration transaction changed');
  await recordAudit(c,{actorType:'admin',actorId:actor.userId,sessionId:actor.sessionId,requestId:actor.requestId,action:'distribution.legacy_sources.imported',objectType:'legacy_invitation_batch',objectId:plan.bodyDigest,outcome:'SUCCESS',reason:'Master-reviewed original legacy invitation sources',details:{bodyDigest:plan.bodyDigest,subjects:plan.subjects.length,relations:plan.relations.length,unknownInviteeTotals:plan.subjects.filter(s=>s.inviteesKnowledge==='UNKNOWN').length}});await authorizeFinanceMaintenance(c,actor);await c.query('SET CONSTRAINTS ALL IMMEDIATE');return{status:200,body:{bodyDigest:plan.bodyDigest,participants:plan.subjects.length,codes:plan.subjects.length,relations:plan.relations.length}};
 });
}
/** Original receipt recovery only. Later self-binding/grade updates do not rewrite
 * immutable migration provenance; the original imported edges and codes must remain. */
export async function recoverReviewedLegacyInvitations(c:PoolClient,actor:Actor,input:LegacyInvitationInput,reviewedDigest:string){
 const plan=prepareLegacyInvitationImport(input,reviewedDigest);await resource(c);await authorizeFinanceMaintenance(c,actor);
 const r=(await c.query('SELECT request_fingerprint AS fingerprint,response_status AS status,response_body AS body FROM zzsh_supply.idempotency_record WHERE scope_key=$1 AND key=$2',[JSON.stringify(['admin',actor.userId,operation,null]),plan.key])).rows[0];if(!r)return{knowledge:'UNKNOWN' as const,receipt:null};
 if(r.fingerprint!==fingerprintRequest(operation,undefined,input)||r.status!==200||r.body?.bodyDigest!==plan.bodyDigest||r.body.participants!==plan.subjects.length||r.body.codes!==plan.subjects.length||r.body.relations!==plan.relations.length)throw conflict('Original migration receipt body differs');
 for(const s of plan.subjects){const participant=(await c.query('SELECT source_type,source_ref,source_digest FROM zzsh_order.distribution_participant WHERE user_id=$1',[s.userId])).rows[0],code=(await c.query('SELECT user_id,display_code,source_type,source_system,source_entity,source_id,source_digest FROM zzsh_order.distribution_invite_code WHERE id=$1',[s.codeId])).rows[0];if(!participant||participant.source_type!=='LEGACY_MYSQL'||participant.source_ref!==s.sourceRef||participant.source_digest!==s.sourceDigest||!code||code.user_id!==s.userId||code.display_code!==s.userSource.code||code.source_type!=='LEGACY_MYSQL'||code.source_system!==input.sourceSystem||code.source_entity!=='la_user'||code.source_id!==s.legacyId||code.source_digest!==s.codeDigest)throw conflict('Original immutable participant/code source differs');}
 for(const edge of plan.relations){const row=(await c.query('SELECT type,child_user_id,parent_user_id,policy_version_id,source_type,source_ref,source_digest FROM zzsh_order.invitation_relation WHERE id=$1',[edge.id])).rows[0];if(!row||row.type!==edge.type||row.child_user_id!==edge.childUserId||row.parent_user_id!==edge.parentUserId||row.policy_version_id!==input.policyVersionId||row.source_type!=='LEGACY_MYSQL'||row.source_ref!==edge.sourceRef||row.source_digest!==edge.sourceDigest)throw conflict('Original immutable relation source differs');}
 return{knowledge:'KNOWN' as const,receipt:{status:r.status,body:r.body}};
}


