"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';import Link from 'next/link';import {Clock3,CreditCard,Info,RefreshCw} from 'lucide-react';
import {useUserSession,useUserSessionStore} from '@/components/session/user-session-provider';
import {WalletRequestError,walletMoney,type WalletRead} from '@/lib/personal-wallet-client';
import {pendingLocalWithdrawal,quoteLocalWithdrawal,readLocalWithdrawals,recoverLocalWithdrawal,submitLocalWithdrawal,yuanToCents,type LocalWithdrawalScope,type WithdrawalQuote} from '@/lib/controlled-withdrawal-client';
const labels={RESERVED:'资金已冻结',SUBMITTING:'正在受理',PROCESSING:'处理中',UNKNOWN:'结果待确认',SUCCEEDED:'本地处理成功',FAILED:'未出款，资金已释放',RECONCILIATION_REQUIRED:'需要核对'};
const errorText=(e:unknown)=>e instanceof WalletRequestError&&e.status===401?'登录身份已变化，请重新登录后查询原申请。':e instanceof WalletRequestError&&e.status===409?'金额、额度或钱包状态已变化，请重新读取；结果待确认时只能查询原申请。':'当前无法确认提现状态，请稍后查询。';
export function ControlledWithdrawal({wallet,scope,onWalletChanged,onIdentityFailure,compact=false}:{wallet:WalletRead;scope:string;onWalletChanged:()=>void;onIdentityFailure?:(error:WalletRequestError)=>void;compact?:boolean}){
 const session=useUserSession(),store=useUserSessionStore(),live=useRef({scope,mounted:false});live.current.scope=scope;
 const [value,setValue]=useState<{scope:string;data:LocalWithdrawalScope|null}>({scope,data:null}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(false),[amount,setAmount]=useState(''),[destination,setDestination]=useState(''),[quote,setQuote]=useState<WithdrawalQuote|null>(null),[notice,setNotice]=useState('');
 const current=()=>{const s=store.getSnapshot();return live.current.mounted&&s.status==='authenticated'&&s.userId===wallet.subjectId&&`${s.userId}:${s.identityVersion}`===scope&&live.current.scope===scope;};
 const failure=(e:unknown)=>{if(!current())return;setQuote(null);setError(errorText(e));if(e instanceof WalletRequestError&&(e.status===401||e.status===403)){setValue({scope,data:null});if(onIdentityFailure)onIdentityFailure(e);else if(e.status===401)session.revalidate();}};
 const load=async()=>{if(!current())return;setBusy(true);setError('');try{setPending(Boolean(pendingLocalWithdrawal(wallet.subjectId)));const data=await readLocalWithdrawals(wallet.subjectId);if(current())setValue({scope,data});}catch(e){if(current()){setValue({scope,data:null});failure(e);}}finally{if(current())setBusy(false);}};
 useEffect(()=>{live.current.mounted=true;setValue({scope,data:null});setQuote(null);setNotice('');void load();return()=>{live.current.mounted=false;};
 // Keep all replies bound to the shared confirmed identity and exact wallet snapshot.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[scope,wallet.ledgerRevision]);
 useEffect(()=>{const changed=(e:StorageEvent)=>{if(e.key==='zzsh.withdrawal.pending.v1:'+wallet.subjectId&&current())try{setPending(Boolean(pendingLocalWithdrawal(wallet.subjectId)));setQuote(null);}catch{setPending(true);setError('原申请标记无法读取，请保留当前浏览器状态并联系核对。');}};window.addEventListener('storage',changed);return()=>window.removeEventListener('storage',changed);
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[scope]);
 const data=value.scope===scope&&current()?value.data:null,selected=data?.destinations.find(d=>d.id===destination);
 const preview=async(e:FormEvent)=>{e.preventDefault();if(!current()||busy||pending||(!selected?.policyVersion||!selected.canQuote))return;setBusy(true);setError('');setNotice('');try{const q=await quoteLocalWithdrawal(wallet.subjectId,{amountCents:yuanToCents(amount),destinationId:selected.id,policyVersion:selected.policyVersion,expectedWalletVersion:wallet.ledgerRevision});if(current())setQuote(q);}catch(e){failure(e);}finally{if(current())setBusy(false);}};
 const submit=async()=>{if(!current()||busy||pending||!quote)return;setBusy(true);setError('');try{const result=await submitLocalWithdrawal(wallet.subjectId,quote,current);if(current()){setQuote(null);setAmount('');setNotice(labels[result.state]);onWalletChanged();}}catch(e){if(current()){let unresolved=true;try{unresolved=Boolean(pendingLocalWithdrawal(wallet.subjectId));setPending(unresolved);}catch{setPending(true);}failure(e);if(unresolved&&!(e instanceof WalletRequestError&&(e.status===401||e.status===403)))onWalletChanged();}}finally{if(current())setBusy(false);}};
 const recover=async()=>{if(!current()||busy)return;setBusy(true);setError('');try{const result=await recoverLocalWithdrawal(wallet.subjectId,current);if(current()){if(result){setPending(false);setNotice(labels[result.state]);onWalletChanged();}else{setPending(true);setError('原申请结果仍未确认，请稍后再次查询，勿重复提交。');}}}catch(e){failure(e);}finally{if(current())setBusy(false);}};
 if(compact){const unsettled=data?.items.filter(i=>!['SUCCEEDED','FAILED'].includes(i.state)).length;return <section className="account-module-card wallet-attention" aria-busy={busy||undefined}><h3><Clock3 size={17} aria-hidden="true"/>待处理事项</h3><strong>{busy?'正在读取处理状态':pending?'原申请结果待确认':data?unsettled?`${unsettled} 笔本轮申请需要确认`:'本轮暂无待处理申请':'提现状态待确认'}</strong><p>{data?'本轮申请单独核对；历史处理记录尚未纳入本轮范围。':'当前无法确认本轮申请状态，未确认金额不会按零展示。'}</p><Link className="button secondary" href="/account?view=wallet&wallet=withdraw" scroll={false}>查看提现状态</Link></section>;}
 return <div className="controlled-withdrawal" data-testid="controlled-withdrawal" aria-busy={busy||undefined}>
  <p className="wallet-history-note">本轮为本地受控处理，手续费由服务端确认，不发生真实银行卡或收款码出款。历史可提现条件仍待核定。</p>
  {pending?<section className="account-module-card wallet-withdraw-pending" role="status"><h3><Clock3 size={18} aria-hidden="true"/>原申请结果待确认</h3><p>已保留原申请。先查询处理结果，确认前无法再次提交。</p><button type="button" className="button primary" disabled={busy} onClick={()=>void recover()}>查询原申请</button></section>:null}
  {error?<p className="wallet-read-error" role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}
  {!data?<section className="account-module-card account-empty-state"><Info size={28} aria-hidden="true"/><h3>{busy?'正在读取提现条件':'提现条件尚未确认'}</h3><p>当前无法确认本轮准入与处理记录，不将未确认金额显示为零。</p><button className="button primary" disabled>暂不可申请提现</button><button className="button secondary" type="button" disabled={busy} onClick={()=>void load()}><RefreshCw size={15} aria-hidden="true"/>重新读取</button></section>:<>
   <div className="wallet-workbench"><section className="account-module-card"><h3><CreditCard size={17} aria-hidden="true"/>申请提现</h3><form className="wallet-withdraw-form" onSubmit={preview}><label htmlFor="withdraw-destination">本轮收款目标</label><select id="withdraw-destination" value={destination} disabled={busy||pending} onChange={e=>{setDestination(e.target.value);setQuote(null);}}><option value="">请选择已核定目标</option>{data.destinations.map(d=><option key={d.id} value={d.id} disabled={!d.canQuote}>{d.kind==='BANK_CARD'?'银行卡':'收款码'} · {d.mask}{d.canQuote?'':' · 本轮暂不可申请'}</option>)}</select><label htmlFor="withdraw-amount">提现金额（元）</label><input id="withdraw-amount" inputMode="decimal" autoComplete="off" placeholder="填写申请金额" value={amount} disabled={busy||pending} onChange={e=>{setAmount(e.target.value);setQuote(null);}}/><p>当前可用余额 {walletMoney(wallet.buckets.available.amountCents)}。本轮每笔准入 {walletMoney(selected?.perIntentCents??null)}，最终费用与资格以服务端确认结果为准。</p><button type="submit" className="button secondary" disabled={busy||pending||!amount||(!selected?.policyVersion||!selected.canQuote)}>确认金额与费用</button></form>
   {quote?<div className="wallet-withdraw-quote"><dl className="account-fact-list"><div><dt>申请金额</dt><dd>{walletMoney(quote.amountCents)}</dd></div><div><dt>服务端确认手续费</dt><dd>{walletMoney(quote.feeCents)}</dd></div><div><dt>预计到账</dt><dd>{walletMoney(quote.netCents)}</dd></div><div><dt>收款目标</dt><dd>{quote.destinationMask}</dd></div></dl><button type="button" className="button primary" disabled={busy||pending} onClick={()=>void submit()}>{busy?'正在确认申请…':'提交本地受控申请'}</button></div>:null}</section>
   <section className="account-module-card wallet-attention"><h3><Clock3 size={17} aria-hidden="true"/>本轮处理状态</h3><dl className="account-fact-list"><div><dt>本轮冻结</dt><dd>{walletMoney(data.totals.reservedCents)}</dd></div><div><dt>本轮已出账</dt><dd>{walletMoney(data.totals.payoutCents)}</dd></div><div><dt>本轮已记手续费</dt><dd>{walletMoney(data.totals.feeCents)}</dd></div></dl><p>仅统计已核定的本轮申请，不代表历史冻结总额。申请结果不明时，冻结资金不会释放。</p><button className="button secondary" type="button" disabled={busy} onClick={onWalletChanged}>查询处理状态</button></section></div>
   <div className="wallet-section-heading"><h3>本轮提现记录</h3></div>{data.items.length?<div className="account-module-card wallet-record-card">{data.items.map(i=><article key={i.id} className="wallet-withdraw-record"><div><strong>{labels[i.state]}</strong><p>{new Date(i.acceptedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</p><small>{i.state==='RECONCILIATION_REQUIRED'?(i.fundsDisposition==='PAYOUT_POSTED'?'原本地出账已记，晚到观察需核对，不会再次扣款。':i.fundsDisposition==='RELEASE_POSTED'?'原资金释放已记，晚到观察需核对，不会再次退回。':'本轮资金仍预留，需要核对。'):i.state==='FAILED'?'已确认未出款，申请金额已全部释放，未扣手续费。':i.state==='SUCCEEDED'?`本地出账 ${walletMoney(i.netCents)} · 已记手续费 ${walletMoney(i.feeCents)}`:'资金冻结中，尚无最终出款结果。'}</small></div><strong>{walletMoney(i.amountCents)}</strong></article>)}</div>:<p className="wallet-history-note">本轮暂无申请记录。历史处理记录不在本轮覆盖范围内。</p>}
  </>}
 </div>;
}
