"use client";
import {PersonalEarnings} from './personal-earnings';import {useEffect,useRef,useState,type FormEvent} from 'react';import {Copy,RefreshCw,Users,Link2,Clock3} from 'lucide-react';
import {useUserSession,useUserSessionStore} from '@/components/session/user-session-provider';import {formatOrderTime} from '@/lib/order-client';import {WalletRequestError} from '@/lib/personal-wallet-client';
import {readMyInvitation,readMyInvitees,pendingLeaderBinding,bindLeader,recoverLeaderBinding,type InvitationRead} from '@/lib/invitation-client';import {WalletSummary} from './personal-wallet';import './personal-invitations.css';
type Filter='ALL'|'INVITER'|'DISTRIBUTION_LEADER';type Page=Awaited<ReturnType<typeof readMyInvitees>>;
const typeLabel={INVITER:'注册邀请',DISTRIBUTION_LEADER:'分销下级'};
const errorText=(e:unknown)=>e instanceof WalletRequestError&&e.code==='PENDING_MARKER_UNREADABLE'?'本机保存的原绑定记录无法读取，暂时不能提交。请保留记录并联系支持。':e instanceof WalletRequestError&&e.status===401?'登录身份已变化，请重新确认登录。':e instanceof WalletRequestError&&e.status===403?'当前账号无法读取或修改邀请关系。':e instanceof WalletRequestError&&e.status===409?'关系或政策已变化，请重新读取。未确认的绑定先查询原记录。':'邀请记录暂时无法读取，请稍后重试。';
export function PersonalInvitations({scope}:{scope:string}){
 const session=useUserSession(),store=useUserSessionStore(),live=useRef({scope,mounted:false});live.current.scope=scope;
 const [data,setData]=useState<{scope:string;value:InvitationRead|null}>({scope,value:null}),[page,setPage]=useState<{scope:string;value:Page|null}>({scope,value:null}),[filter,setFilter]=useState<Filter>('ALL'),[busy,setBusy]=useState(false),[pending,setPending]=useState(false),[code,setCode]=useState(''),[accepted,setAccepted]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const ticket=useRef(0);
 const userId=session.userId,current=()=>{const s=store.getSnapshot();return live.current.mounted&&live.current.scope===scope&&s.status==='authenticated'&&s.userId===userId&&`${s.userId}:${s.identityVersion}`===scope;};
 const fail=(e:unknown)=>{if(!current())return;setError(errorText(e));if(e instanceof WalletRequestError&&[401,403,409].includes(e.status)){setData({scope,value:null});setPage({scope,value:null});if(e.status===401)session.revalidate();}};
 const load=async(type:Filter=filter)=>{if(!userId||!current())return;const id=++ticket.current;setBusy(true);setError('');try{setPending(Boolean(pendingLeaderBinding(userId)));const results=await Promise.allSettled([readMyInvitation(userId),readMyInvitees(userId,type)]);if(!current()||id!==ticket.current)return;const rejected=results.find(r=>r.status==='rejected'&&r.reason instanceof WalletRequestError&&[401,403,409].includes(r.reason.status));if(rejected?.status==='rejected'){fail(rejected.reason);return;}if(results[0].status==='fulfilled')setData({scope,value:results[0].value});else{setData({scope,value:null});fail(results[0].reason);}if(results[1].status==='fulfilled')setPage({scope,value:results[1].value});else{setPage({scope,value:null});fail(results[1].reason);}}catch(e){if(current()){setPending(true);fail(e);}}finally{if(current()&&id===ticket.current)setBusy(false);}};
 useEffect(()=>{live.current.mounted=true;setData({scope,value:null});setPage({scope,value:null});setFilter('ALL');setCode('');setAccepted(false);setNotice('');setError('');setPending(false);void load('ALL');return()=>{live.current.mounted=false;ticket.current++;};
 // Every completion checks stable identity against the shared store and its original scope.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[scope]);
 const value=data.scope===scope&&current()?data.value:null,list=page.scope===scope&&current()?page.value:null;
 const recover=async()=>{if(!userId||!current())return;setBusy(true);setError('');try{const result=await recoverLeaderBinding(userId,current);if(!current())return;setPending(Boolean(pendingLeaderBinding(userId)));if(result){setData({scope,value:result});setNotice('原绑定已确认。');}else setNotice('原绑定结果仍待确认，请稍后查询。');}catch(e){fail(e);}finally{if(current())setBusy(false);}};
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!value?.policyVersion||!value.participant.revision||!userId||!current()||!accepted)return;setBusy(true);setError('');setNotice('');try{const result=await bindLeader(userId,{code:code.trim(),policyVersion:value.policyVersion,expectedParticipantRevision:value.participant.revision},current);if(current()){setData({scope,value:result});setCode('');setAccepted(false);setNotice('分销上级已绑定。');}}catch(e){fail(e);}finally{if(current()){try{setPending(Boolean(pendingLeaderBinding(userId)));}catch{setPending(true);}setBusy(false);}}};
 const more=async()=>{if(!userId||!list?.nextCursor||!current())return;const id=++ticket.current;setBusy(true);try{const next=await readMyInvitees(userId,filter,list.nextCursor);if(current()&&id===ticket.current){if(next.knowledge!==list.knowledge||next.type!==list.type||next.snapshotVersion!==list.snapshotVersion||next.count!==list.count||next.mappedRelationCount!==list.mappedRelationCount||next.items.some(n=>list.items.some(i=>i.id===n.id)))throw new WalletRequestError(409,'INVITATION_PAGE_CHANGED');setPage({scope,value:{...next,items:[...list.items,...next.items]}});}}catch(e){fail(e);}finally{if(current()&&id===ticket.current)setBusy(false);}};
 const copy=async(link:boolean)=>{if(!value?.ownCode.code||!current())return;try{await navigator.clipboard.writeText(link?new URL('/login?inviteCode='+encodeURIComponent(value.ownCode.code),window.location.origin).href:value.ownCode.code);if(current())setNotice(link?'邀请链接已复制。':'邀请码已复制。');}catch{if(current())setNotice('无法自动复制，请选中邀请码复制。');}};
 return <section className="personal-invitations account-section" aria-labelledby="invitation-heading" aria-busy={busy||undefined}>
  <div className="account-section-heading"><div><h2 id="invitation-heading">分销中心</h2><p>查看邀请关系，确认上级与收益记录。</p></div><button className="button secondary" type="button" disabled={busy} onClick={()=>void load()}><RefreshCw size={15} aria-hidden="true"/>重新读取</button></div>
  <WalletSummary scope={scope}/>
  {error?<p className="invitation-error" role="alert">{error}</p>:null}{notice?<p className="invitation-notice" role="status">{notice}</p>:null}
  {pending?<section className="account-module-card invitation-pending"><Clock3 size={19} aria-hidden="true"/><div><h3>原绑定结果待确认</h3><p>已保留原请求。确认前无法提交新的绑定。</p><button type="button" className="button secondary" disabled={busy} onClick={()=>void recover()}>查询原绑定</button></div></section>:null}
  <div className="invitation-workbench"><section className="account-module-card invitation-code"><h3>我的邀请码</h3><strong>{value?.ownCode.code??(busy?'正在读取':'待核定')}</strong><p>{value?.ownCode.code?'邀请新用户时分享此码，注册来源与分销上级分别记录。':'邀请码归属尚未确认，暂时无法分享。'}</p><div className="invitation-actions"><button className="button secondary" type="button" disabled={!value?.ownCode.code||busy} onClick={()=>void copy(false)}><Copy size={15} aria-hidden="true"/>复制邀请码</button><button className="button secondary" type="button" disabled={!value?.ownCode.code||busy} onClick={()=>void copy(true)}><Link2 size={15} aria-hidden="true"/>复制邀请链接</button></div></section>
   <section className="account-module-card invitation-parent"><h3>分销上级</h3><strong>{value?.leader.knowledge==='KNOWN_PARENT'?'已绑定':value?.leader.knowledge==='KNOWN_NONE'?'尚未绑定':'关系待核定'}</strong><p>注册推荐来源只在注册时记录。绑定分销上级后无法更换，已有邀请来源不会被覆盖。</p>
    {value?.leader.knowledge==='KNOWN_NONE'?<form onSubmit={submit}><label htmlFor="leader-invitation-code">上级邀请码</label><input id="leader-invitation-code" autoComplete="off" maxLength={30} placeholder="填写对方的邀请码" value={code} disabled={busy||pending||value.policyEnabled!==true} onChange={e=>{setCode(e.target.value);setAccepted(false);}}/><label className="invitation-confirm"><input type="checkbox" checked={accepted} disabled={busy||pending||value.policyEnabled!==true} onChange={e=>setAccepted(e.target.checked)}/><span>我确认绑定后不能更换上级</span></label><button className="button primary" type="submit" disabled={busy||pending||!accepted||!code.trim()||value.policyEnabled!==true}>绑定分销上级</button>{value.policyEnabled!==true?<p>上级绑定当前未开放。</p>:null}</form>:null}
    <p className="invitation-source">注册邀请来源：{value?.inviter.knowledge==='KNOWN_PARENT'?'已确认':value?.inviter.knowledge==='KNOWN_NONE'?'注册时未提供':'待核定'}</p></section></div>
  <section className="account-module-card invitation-list"><div className="invitation-list-heading"><h3><Users size={18} aria-hidden="true"/>我的邀请关系</h3><span>{list?.knowledge==='KNOWN'?`${list.count} 条关系`:list?.mappedRelationCount!==null&&list?.mappedRelationCount!==undefined?`已确认 ${list.mappedRelationCount} 条 · 总数待核定`:'数量待核定'}</span></div><div className="invitation-filters" role="group" aria-label="邀请关系类型">{(['ALL','INVITER','DISTRIBUTION_LEADER'] as Filter[]).map(type=><button key={type} type="button" aria-pressed={filter===type} disabled={busy} onClick={()=>{setFilter(type);setPage({scope,value:null});void load(type);}}>{type==='ALL'?'全部关系':typeLabel[type]}</button>)}</div>
   {list?.knowledge==='UNKNOWN'&&list.items.length>0?<p className="invitation-source">历史邀请关系还在核对，以下为已确认的关系；总数暂未核定。</p>:null}
   {list?.items.length?<ul>{list.items.map(item=><li key={item.id}><div><strong>{item.nickname}</strong><small>{item.boundAt===null?'原绑定时间未核定':formatOrderTime(item.boundAt)}</small></div><span>{typeLabel[item.type]}</span></li>)}</ul>:<p className="invitation-empty">{busy?'正在读取邀请记录…':list?.knowledge==='KNOWN'?'暂无已确认的邀请关系。':'邀请记录尚未完整核定，暂时无法确认数量。'}</p>}
   {list?.nextCursor?<button className="button secondary" type="button" disabled={busy} onClick={()=>void more()}>继续读取关系</button>:null}</section>
  <PersonalEarnings scope={scope}/>
 </section>;
}
