import assert from 'node:assert/strict';import {test} from 'node:test';
import {quoteLocalWithdrawal,pendingLocalWithdrawal,submitLocalWithdrawal,recoverLocalWithdrawal,readLocalWithdrawal,yuanToCents} from '../src/lib/controlled-withdrawal-client.ts';
const user='user_test',body={amountCents:'200',destinationId:'code',policyVersion:'local_v1',expectedWalletVersion:'1'},quote={...body,requestKey:'original-server-key',netCents:'196',feeCents:'4',destinationMask:'local code',acceptedAt:'2026-10-04T00:00:00Z'};
const intent={id:'wd_1',scope:'LOCAL_CONTROLLED',evidenceLevel:'LOCAL_CONTROLLED',userId:user,state:'UNKNOWN',operationVersion:'3',fundsDisposition:'RESERVED',amountCents:'200',netCents:'196',feeCents:'4',destinationId:'code',policyVersion:'local_v1',acceptedAt:'2026-10-04T00:00:00Z',terminal:null};
async function withBrowser(run){const fetch=globalThis.fetch,storage=Object.getOwnPropertyDescriptor(globalThis,'localStorage'),nav=Object.getOwnPropertyDescriptor(globalThis,'navigator'),values=new Map();let locked=false;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)}});Object.defineProperty(globalThis,'navigator',{configurable:true,value:{locks:{request:async(_key,_options,fn)=>{if(locked)return fn(null);locked=true;try{return await fn({name:'test'});}finally{locked=false;}}}}});try{await run(values);}finally{globalThis.fetch=fetch;if(storage)Object.defineProperty(globalThis,'localStorage',storage);else delete globalThis.localStorage;if(nav)Object.defineProperty(globalThis,'navigator',nav);else delete globalThis.navigator;}}
test('exact yuan conversion rejects rounding, exponent and misleading zero formats',()=>{assert.equal(yuanToCents('999999999999999999999.99'),'99999999999999999999999');for(const n of ['2.001','1e2','-2','02',''])assert.throws(()=>yuanToCents(n));});
test('quote verifies server fees, subject, requested destination and wallet revision',async()=>{const old=globalThis.fetch;const q={...body,requestKey:'original-server-key',scope:'LOCAL_CONTROLLED',userId:user,grossCents:'200',netCents:'196',feeCents:'4',ledgerRevision:'1',globalWithdrawable:'UNKNOWN',identityMeaning:'EXPLICIT_LOCAL_TEST_ADMISSION_NOT_REAL_KYC',destination:{id:'code',mask:'local code'},acceptedAt:quote.acceptedAt};try{globalThis.fetch=async()=>Response.json({quote:q});assert.deepEqual(await quoteLocalWithdrawal(user,body),quote);for(const patch of [{ledgerRevision:'2'},{feeCents:'3'},{destinationId:'other'}]){globalThis.fetch=async()=>Response.json({quote:{...q,...patch}});await assert.rejects(quoteLocalWithdrawal(user,body),e=>e.code==='WITHDRAWAL_CONTRACT_REQUIRED');}globalThis.fetch=async()=>Response.json({quote:{...q,userId:'other'}});await assert.rejects(quoteLocalWithdrawal(user,body),e=>e.status===401);}finally{globalThis.fetch=old;}});
test('ACK loss preserves one original key, prohibits repeat POST and recovers only that receipt',()=>withBrowser(async()=>{let posts=0,originalKey;globalThis.fetch=async(u,o)=>{if(o.method==='POST'){posts++;originalKey=o.headers['idempotency-key'];assert(pendingLocalWithdrawal(user));throw Error('ACK lost');}assert(String(u).includes('/receipt?key='+originalKey));return Response.json({scope:'LOCAL_CONTROLLED',knowledge:'UNKNOWN',receipt:null});};await assert.rejects(submitLocalWithdrawal(user,quote,()=>true));assert.equal(posts,1);await assert.rejects(submitLocalWithdrawal(user,quote,()=>true),e=>e.code==='WITHDRAWAL_UNRESOLVED');assert.equal(await recoverLocalWithdrawal(user,()=>true),null);assert(pendingLocalWithdrawal(user));globalThis.fetch=async u=>String(u).includes('/receipt?')?Response.json({scope:'LOCAL_CONTROLLED',knowledge:'KNOWN',receipt:{intent}}):Response.json({intent:{...intent,state:'SUCCEEDED',operationVersion:'5',fundsDisposition:'PAYOUT_POSTED',terminal:{state:'SUCCEEDED',reference:'local_operation'}}});assert.equal((await recoverLocalWithdrawal(user,()=>true)).state,'SUCCEEDED');assert.equal(pendingLocalWithdrawal(user),null);assert.equal(posts,1);}));
test('accepted write with failed readback keeps marker across identity401 and same-user recovery',()=>withBrowser(async()=>{globalThis.fetch=async(u,o)=>o.method==='POST'?Response.json({intent}):Response.json({error:{code:'UNAUTHENTICATED'}},{status:401});await assert.rejects(submitLocalWithdrawal(user,quote,()=>true),e=>e.status===401);assert(pendingLocalWithdrawal(user));await assert.rejects(recoverLocalWithdrawal(user,()=>true),e=>e.status===401);assert(pendingLocalWithdrawal(user));assert.equal(pendingLocalWithdrawal('other'),null);}));
test('late identity change keeps write marker and suppresses readback or new submission',()=>withBrowser(async()=>{let active=true,reads=0;globalThis.fetch=async()=>{active=false;reads++;return Response.json({intent});};await assert.rejects(submitLocalWithdrawal(user,quote,()=>active),e=>e.status===401);assert.equal(reads,1);assert(pendingLocalWithdrawal(user));assert.equal(await recoverLocalWithdrawal(user,()=>active),null);}));
test('definite validation rejection clears intent; malformed accepted response stays unresolved',()=>withBrowser(async()=>{globalThis.fetch=async()=>Response.json({error:{code:'CONFLICT'}},{status:409});await assert.rejects(submitLocalWithdrawal(user,quote,()=>true),e=>e.status===409);assert.equal(pendingLocalWithdrawal(user),null);globalThis.fetch=async()=>Response.json({intent:{...intent,feeCents:'3'}});await assert.rejects(submitLocalWithdrawal(user,quote,()=>true));assert(pendingLocalWithdrawal(user));}));
test('cross-tab lock unavailable and unreadable pending marker both prevent a business POST',()=>withBrowser(async values=>{let posts=0;globalThis.fetch=async()=>{posts++;return Response.json({intent});};navigator.locks.request=async(_key,_opts,fn)=>fn(null);await assert.rejects(submitLocalWithdrawal(user,quote,()=>true),e=>e.code==='WITHDRAWAL_UNRESOLVED');values.set('zzsh.withdrawal.pending.v1:'+user,'bad json');assert.throws(()=>pendingLocalWithdrawal(user),e=>e.code==='PENDING_MARKER_UNREADABLE');assert.equal(posts,0);}));
test('readback rejects another ID even for same user; terminal disposition remains exact',async()=>{const old=globalThis.fetch;try{globalThis.fetch=async()=>Response.json({intent:{...intent,id:'wd_other'}});await assert.rejects(readLocalWithdrawal(user,'wd_1'));globalThis.fetch=async()=>Response.json({intent:{...intent,state:'SUCCEEDED',fundsDisposition:'RELEASE_POSTED',terminal:{state:'SUCCEEDED',reference:'local'}}});await assert.rejects(readLocalWithdrawal(user,'wd_1'));}finally{globalThis.fetch=old;}});
