import {test} from 'node:test';import {strict as assert} from 'node:assert';
import {earningsPage,earningsDetail,readEarnings,readEarningDetail} from '../src/lib/distribution-earnings-client.ts';
const at='2026-10-04T00:00:00.000000Z',base={contractVersion:'distribution-earnings.read.v1',subjectId:'self',snapshotVersion:'source-v1',asOf:at};
export const old={id:'history:old',origin:'LEGACY_MYSQL',state:'SETTLED',role:'RENTER_REFERRAL',amount:{currency:'CNY',unit:'cent',amountCents:'1234'},occurredAt:at,dueAt:null,dueAtKnowledge:'UNKNOWN',fundsDisposition:'HISTORICAL_STATUS_ONLY',recoveryRequiredCents:null,includedInOpening:true,version:null,accountingEffect:'OBSERVATION_ONLY_NO_NEW_CREDIT',businessReference:{type:'LEGACY_UNRESOLVED',id:'legacy'},channelArrivalKnowledge:'UNKNOWN'};
const page={...base,state:'ALL',knowledge:'UNKNOWN',count:null,mappedRecordCount:'1',reason:'HISTORICAL_EARNINGS_COVERAGE_NOT_CLOSED',totalAmountKnowledge:'UNKNOWN',items:[old],nextCursor:null};
test('history remains an observation and source fields are stripped by the shared DTO',()=>{const r=earningsPage({...page,privateSource:'secret',items:[{...old,sourceDigest:'secret',phone:'secret'}]},'self','ALL');assert.equal(r.count,null);assert.equal(r.items[0].includedInOpening,true);assert.equal(r.items[0].dueAt,null);assert(!JSON.stringify(r).includes('secret'));});
test('mismatched subject, source state, date knowledge, money unit and false channel arrival reject',()=>{assert.throws(()=>earningsPage({...page,subjectId:'other'},'self','ALL'),e=>e.status===401);for(const patch of [{state:'REVOKED'},{dueAt:at,dueAtKnowledge:'KNOWN'},{channelArrivalKnowledge:'KNOWN'},{accountingEffect:'NEW_CREDIT'},{amount:{currency:'CNY',unit:'yuan',amountCents:'1234'}}])assert.throws(()=>earningsPage({...page,items:[{...old,...patch}]},'self','ALL'));assert.throws(()=>earningsDetail({...base,item:old},'self','history:another'));});
test('native recovery keeps settled funds and exact original debt; a false zero debt rejects',()=>{const native={...old,id:'native:new',origin:'NATIVE',state:'RECOVERY_REQUIRED',fundsDisposition:'SETTLED',dueAt:at,dueAtKnowledge:'KNOWN',recoveryRequiredCents:'1234',version:'3',includedInOpening:false,accountingEffect:'EXISTING_LEDGER_EVENT',businessReference:{type:'RENTAL_ORDER',id:'order'}};assert.equal(earningsDetail({...base,item:native},'self',native.id).item.recoveryRequiredCents,'1234');assert.throws(()=>earningsDetail({...base,item:{...native,recoveryRequiredCents:'0'}},'self',native.id));});
test('client only GETs the original self list/detail and preserves 401',async()=>{const previous=globalThis.fetch,requests=[];globalThis.fetch=async(url,options)=>{requests.push({url:String(url),options});return Response.json(String(url).includes('/history%3Aold')?{...base,item:old}:page);};try{await readEarnings('self','ALL');await readEarningDetail('self','history:old');assert(requests.every(r=>r.options.method===undefined&&r.options.credentials==='same-origin'));globalThis.fetch=async()=>Response.json({error:{code:'UNAUTHENTICATED'}},{status:401});await assert.rejects(readEarnings('self','ALL'),e=>e.status===401);}finally{globalThis.fetch=previous;}});
