import assert from 'node:assert/strict';import {test} from 'node:test';
import {invitationRead,inviteesPage,readMyInvitees,pendingLeaderBinding,bindLeader,recoverLeaderBinding} from '../src/lib/invitation-client.ts';
const user='self',body={code:'FX0001',policyVersion:'policy',expectedParticipantRevision:'1'},relation={id:'relation',type:'DISTRIBUTION_LEADER',childUserId:user,parentUserId:'parent',policyVersion:'policy'};
const unknown={scope:'LOCAL_CONTROLLED',subjectId:user,policyKnowledge:'UNKNOWN',policyVersion:null,policyEnabled:null,participant:{knowledge:'UNKNOWN',eligibility:'UNKNOWN',levelCode:null,revision:null},ownCode:{knowledge:'UNKNOWN',code:null},inviter:{knowledge:'UNKNOWN',relation:null},leader:{knowledge:'UNKNOWN',relation:null}};
const linked={...unknown,leader:{knowledge:'KNOWN_PARENT',relation:{id:'relation',parentUserId:'parent',sourceType:'LOCAL_CONTROLLED',boundAt:'2026-10-04T02:00:00Z'}}};
test('legacy parent DTO keeps original binding time unknown even when an older response supplies migration time',()=>{const r=invitationRead({...linked,leader:{...linked.leader,relation:{...linked.leader.relation,sourceType:'LEGACY_MYSQL'}}},user);assert.equal(r.leader.relation.boundAt,null);assert.equal(r.leader.relation.boundAtKnowledge,'UNKNOWN');});
test('partial list contract retains mapped counts and hides legacy import timestamps; inconsistent partial sources reject',()=>{
 const partial={subjectId:user,knowledge:'UNKNOWN',type:'INVITER',snapshotVersion:'snapshot',count:null,mappedRelationCount:'2',nextCursor:'next',items:[{id:'r',type:'INVITER',nickname:'已确认用户',boundAt:'2026-10-04T00:00:00Z',sourceType:'LEGACY_MYSQL'}]};
 const page=inviteesPage(partial,user,'INVITER');assert.equal(page.count,null);assert.equal(page.mappedRelationCount,'2');assert.equal(page.items[0].boundAt,null);assert.equal(page.items[0].boundAtKnowledge,'UNKNOWN');
 for(const patch of [{mappedRelationCount:null},{mappedRelationCount:'0'},{snapshotVersion:null},{type:'ALL'},{count:'2'},{items:[partial.items[0],partial.items[0]]}])assert.throws(()=>inviteesPage({...partial,...patch},user,'INVITER'));
 assert.throws(()=>inviteesPage({...partial,subjectId:'other'},user,'INVITER'),e=>e.status===401);
});
async function browser(run){const previous=globalThis.fetch,storage=Object.getOwnPropertyDescriptor(globalThis,'localStorage'),nav=Object.getOwnPropertyDescriptor(globalThis,'navigator'),values=new Map();Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)}});Object.defineProperty(globalThis,'navigator',{configurable:true,value:{locks:{request:async(_key,_opts,fn)=>fn({})}}});try{await run(values);}finally{globalThis.fetch=previous;if(storage)Object.defineProperty(globalThis,'localStorage',storage);else delete globalThis.localStorage;if(nav)Object.defineProperty(globalThis,'navigator',nav);else delete globalThis.navigator;}}
test('unknown qualification and parents are preserved; inconsistent projection or another identity is rejected',()=>{assert.equal(invitationRead(unknown,user).participant.eligibility,'UNKNOWN');assert.throws(()=>invitationRead({...unknown,subjectId:'other'},user),e=>e.status===401);assert.throws(()=>invitationRead({...unknown,leader:{knowledge:'KNOWN_NONE',relation:linked.leader.relation}},user));assert.throws(()=>invitationRead({...unknown,policyKnowledge:'KNOWN'},user));});
test('list UNKNOWN retains null count rather than displaying a fabricated zero',async()=>{const previous=globalThis.fetch;try{globalThis.fetch=async()=>Response.json({subjectId:user,knowledge:'UNKNOWN',count:null,items:[],nextCursor:null});assert.equal((await readMyInvitees(user,'ALL')).count,null);globalThis.fetch=async()=>Response.json({subjectId:user,knowledge:'UNKNOWN',count:'0',items:[],nextCursor:null});await assert.rejects(readMyInvitees(user,'ALL'));}finally{globalThis.fetch=previous;}});
test('binding ACK loss persists original key and recovers through GET without repeating POST',()=>browser(async()=>{let posts=0,key;globalThis.fetch=async(u,o)=>{if(o.method==='POST'){posts++;key=o.headers['idempotency-key'];assert(pendingLeaderBinding(user));throw Error('lost ACK');}assert(String(u).includes('/bind/receipt?key='+key));return Response.json({subjectId:user,knowledge:'UNKNOWN',receipt:null});};await assert.rejects(bindLeader(user,body,()=>true));await assert.rejects(bindLeader(user,body,()=>true),e=>e.code==='BINDING_UNRESOLVED');assert.equal(await recoverLeaderBinding(user,()=>true),null);assert(pendingLeaderBinding(user));globalThis.fetch=async u=>String(u).includes('/receipt?')?Response.json({subjectId:user,knowledge:'KNOWN',receipt:{relation}}):Response.json(linked);assert.equal((await recoverLeaderBinding(user,()=>true)).leader.relation.id,'relation');assert.equal(posts,1);assert.equal(pendingLeaderBinding(user),null);}));
test('accepted write then 401 readback or late identity change retains marker',()=>browser(async()=>{globalThis.fetch=async(_u,o)=>o.method==='POST'?Response.json({relation}):Response.json({error:{code:'UNAUTHENTICATED'}},{status:401});await assert.rejects(bindLeader(user,body,()=>true),e=>e.status===401);assert(pendingLeaderBinding(user));assert.equal(pendingLeaderBinding('other'),null);let active=false;assert.equal(await recoverLeaderBinding(user,()=>active),null);}));
test('definite rejection can clear marker; malformed accepted response remains unresolved',()=>browser(async()=>{globalThis.fetch=async()=>Response.json({error:{code:'CONFLICT'}},{status:409});await assert.rejects(bindLeader(user,body,()=>true));assert.equal(pendingLeaderBinding(user),null);globalThis.fetch=async()=>Response.json({relation:{...relation,childUserId:'other'}});await assert.rejects(bindLeader(user,body,()=>true));assert(pendingLeaderBinding(user));}));
test('corrupt storage and another tab lock prevent submission',()=>browser(async values=>{let posts=0;globalThis.fetch=async()=>{posts++;throw Error();};navigator.locks.request=async(_k,_o,fn)=>fn(null);await assert.rejects(bindLeader(user,body,()=>true));values.set('zzsh.invitation.binding.pending.v1:'+user,'broken');assert.throws(()=>pendingLeaderBinding(user),e=>e.code==='PENDING_MARKER_UNREADABLE');assert.equal(posts,0);}));
