import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire,Module} from 'node:module';
import {fileURLToPath} from 'node:url';
import {test} from 'node:test';
const tree=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),rq=createRequire(tree+'/package.json'),React=rq('react'),ts=rq('typescript'),{Window}=rq('happy-dom');
async function gallery(media){const window=new Window({url:'http://127.0.0.1:3100/accounts/example'});Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,Node:window.Node,DocumentFragment:window.DocumentFragment,MutationObserver:window.MutationObserver,CustomEvent:window.CustomEvent,NodeFilter:window.NodeFilter,IS_REACT_ACT_ENVIRONMENT:true,getComputedStyle:window.getComputedStyle.bind(window)});Object.defineProperty(globalThis,'navigator',{value:window.navigator,configurable:true});
 const file=tree+'/apps/web/src/components/market/listing-detail.tsx',m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(tree);m.require=n=>n.startsWith('@/')?{}:n==='next/link'?()=>null:rq(n);
 const source=fs.readFileSync(file,'utf8').replace('function DetailGallery(','export function DetailGallery(');m._compile(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
 const host=window.document.createElement('div');window.document.body.append(host);const root=rq('react-dom/client').createRoot(host);await React.act(async()=>root.render(React.createElement(m.exports.DetailGallery,{title:'公开样本',media})));
 return{host,window,async click(label){const b=host.querySelector(`[aria-label="${label}"]`);assert.ok(b);await React.act(async()=>b.click());},async close(){await React.act(async()=>root.unmount());await window.happyDOM.abort();}};
}
test('mixed showcase/penalty uses one gallery collection and correct count/selection',async()=>{const p=await gallery([{assetId:'A',url:'/A.png',category:'SHOWCASE'},{assetId:'P',url:'/P.png',category:'PENALTY'},{assetId:'B',url:'/B.png',category:'SHOWCASE'}]);try{assert.equal(p.host.querySelectorAll('.detail-gallery-thumb').length,2);assert.match(p.host.querySelector('.detail-gallery-count').textContent,/1 \/ 2/);await p.click('选择第 2 张公开展示图');assert.equal(p.host.querySelector('.detail-gallery-main img').getAttribute('src'),'/B.png');assert.match(p.host.querySelector('.detail-gallery-count').textContent,/2 \/ 2/);assert.equal(p.host.querySelector('img[src="/P.png"]'),null);await React.act(async()=>p.host.querySelector('.detail-gallery-main img').dispatchEvent(new p.window.Event('error')));assert.match(p.host.textContent,/图片暂不可用/);await p.click('选择第 1 张公开展示图');assert.equal(p.host.querySelector('.detail-gallery-main img').getAttribute('src'),'/A.png');}finally{await p.close();}});
test('all-penalty and empty inputs have no misleading main gallery or thumbnails',async()=>{for(const media of [[],[{assetId:'P',url:'/P.png',category:'PENALTY'}]]){const p=await gallery(media);try{assert.equal(p.host.querySelector('.detail-gallery-main'),null);assert.equal(p.host.querySelectorAll('.detail-gallery-thumb').length,0);assert.match(p.host.textContent,/暂无可展示的图片/);}finally{await p.close();}}});

test('combined detail keeps rental version binding and remounts confirmation on identity change',async()=>{
 const window=new Window({url:'http://127.0.0.1:3100/accounts/example'});Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,Node:window.Node,DocumentFragment:window.DocumentFragment,MutationObserver:window.MutationObserver,CustomEvent:window.CustomEvent,NodeFilter:window.NodeFilter,IS_REACT_ACT_ENVIRONMENT:true,getComputedStyle:window.getComputedStyle.bind(window)});Object.defineProperty(globalThis,'navigator',{value:window.navigator,configurable:true});
 let session={status:'authenticated',userId:'A'},mounts=0,lastProps;
 function Panel(props){lastProps=props;const [instance]=React.useState(()=>++mounts);return React.createElement('div',{'data-confirmation-instance':instance});}
 const file=tree+'/apps/web/src/components/market/listing-detail.tsx',m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(tree);m.require=n=>n==='@/components/order/rental-confirm-panel'?{RentalConfirmPanel:Panel}:n==='@/components/session/user-session-provider'?{useUserSession:()=>session}:n==='@/components/favorites/favorite-button'?{FavoriteButton:()=>null,FavoriteNotice:()=>null}:n==='@/components/delta/account-card'?{isHaff:()=>false,orderedQuoteResources:()=>[],skinChipTone:()=>'',moneyValue:(v,f)=>v??f}:n.startsWith('@/')?{}:n==='next/link'?()=>null:rq(n);
 m._compile(ts.transpileModule(fs.readFileSync(file,'utf8').replace('function ReadyDetail(','export function ReadyDetail('),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
 const host=window.document.createElement('div');window.document.body.append(host);const root=rq('react-dom/client').createRoot(host),data={id:'account',gameId:'game',versionId:'version',releaseId:'release',title:'combined',displayNo:'TEST',conditionLines:[],resourceLines:[],skinTags:[],media:[],entitlementNames:[],termLabel:'1天'};
 const render=async()=>React.act(async()=>root.render(React.createElement(m.exports.ReadyDetail,{data,back:{href:'/',label:'返回'},activeAnchor:'detail-info'})));
 try{await render();assert.deepEqual(lastProps,{accountId:'account',gameId:'game',versionId:'version',releaseId:'release'});assert.equal(mounts,1);await render();assert.equal(mounts,1);session={status:'authenticated',userId:'B'};await render();assert.equal(mounts,2);data.historicalReadOnly=true;await render();assert.equal(host.querySelector('[data-confirmation-instance]'),null);assert.match(host.textContent,/历史只读账号仅展示公开信息，不支持在线租赁/);}finally{await React.act(async()=>root.unmount());await window.happyDOM.abort();}
});
