import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire,Module} from 'node:module';
import {fileURLToPath} from 'node:url';
import {test} from 'node:test';
const tree=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),rq=createRequire(tree+'/package.json'),React=rq('react'),ts=rq('typescript'),{Window}=rq('happy-dom');
function cardHelpers(){const file=tree+'/apps/web/src/components/delta/account-card.tsx',m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(tree);m.require=n=>n.startsWith('@/')||n.startsWith('./')?{}:n==='next/link'?()=>null:rq(n);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return m.exports;}
const card=cardHelpers();
const Pass=props=>React.createElement(React.Fragment,null,props.children);
const tooltip={Tooltip:Pass,TooltipTrigger:Pass,TooltipContent:()=>null};
async function gallery(media){const window=new Window({url:'http://127.0.0.1:3100/accounts/example'});Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,Node:window.Node,DocumentFragment:window.DocumentFragment,MutationObserver:window.MutationObserver,CustomEvent:window.CustomEvent,NodeFilter:window.NodeFilter,IS_REACT_ACT_ENVIRONMENT:true,getComputedStyle:window.getComputedStyle.bind(window)});Object.defineProperty(globalThis,'navigator',{value:window.navigator,configurable:true});
 const file=tree+'/apps/web/src/components/market/listing-detail.tsx',m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(tree);m.require=n=>n.endsWith('.css')?{}:n.startsWith('@/')?{}:n==='next/link'?()=>null:rq(n);
 const source=fs.readFileSync(file,'utf8').replace('function DetailGallery(','export function DetailGallery(').replace('function entitlementExpiryLabel(','export function entitlementExpiryLabel(');m._compile(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
 const host=window.document.createElement('div');window.document.body.append(host);const root=rq('react-dom/client').createRoot(host);await React.act(async()=>root.render(React.createElement(m.exports.DetailGallery,{title:'公开样本',media})));
 return{host,window,expiryLabel:m.exports.entitlementExpiryLabel,async click(label){const b=host.querySelector(`[aria-label="${label}"]`);assert.ok(b);await React.act(async()=>b.click());},async close(){await React.act(async()=>root.unmount());await window.happyDOM.abort();}};
}
test('mixed showcase/penalty uses one gallery collection and correct count/selection',async()=>{const p=await gallery([{assetId:'A',url:'/A.png',category:'SHOWCASE'},{assetId:'P',url:'/P.png',category:'PENALTY'},{assetId:'B',url:'/B.png',category:'SHOWCASE'}]);try{assert.equal(p.host.querySelectorAll('.detail-gallery-thumb').length,2);assert.match(p.host.querySelector('.detail-gallery-count').textContent,/1 \/ 2/);await p.click('选择第 2 张公开展示图');assert.equal(p.host.querySelector('.detail-gallery-main img').getAttribute('src'),'/B.png');assert.match(p.host.querySelector('.detail-gallery-count').textContent,/2 \/ 2/);assert.equal(p.host.querySelector('img[src="/P.png"]'),null);await React.act(async()=>p.host.querySelector('.detail-gallery-main img').dispatchEvent(new p.window.Event('error')));assert.match(p.host.textContent,/图片暂不可用/);await p.click('选择第 1 张公开展示图');assert.equal(p.host.querySelector('.detail-gallery-main img').getAttribute('src'),'/A.png');}finally{await p.close();}});
test('all-penalty and empty inputs have no misleading main gallery or thumbnails',async()=>{for(const media of [[],[{assetId:'P',url:'/P.png',category:'PENALTY'}]]){const p=await gallery(media);try{assert.equal(p.host.querySelector('.detail-gallery-main'),null);assert.equal(p.host.querySelectorAll('.detail-gallery-thumb').length,0);assert.match(p.host.textContent,/暂无可展示的图片/);}finally{await p.close();}}});

test('gallery arrows and keyboard select only showcase images; single image remains discoverable',async()=>{
 const p=await gallery([{assetId:'A',url:'/A.png',category:'SHOWCASE'},{assetId:'P',url:'/P.png',category:'PENALTY'},{assetId:'B',url:'/B.png',category:'SHOWCASE'}]);
 try{assert.equal(p.host.querySelector('[aria-label="上一张公开展示图"]').disabled,true);await p.click('下一张公开展示图');assert.equal(p.host.querySelector('.detail-gallery-main img').getAttribute('src'),'/B.png');assert.equal(p.host.querySelector('[aria-label="下一张公开展示图"]').disabled,true);await React.act(async()=>p.host.querySelector('.detail-gallery-main').dispatchEvent(new p.window.KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true})));assert.equal(p.host.querySelector('.detail-gallery-main img').getAttribute('src'),'/A.png');assert.equal(p.host.querySelector('img[src="/P.png"]'),null);}finally{await p.close();}
 const single=await gallery([{assetId:'one',url:'/one.png',category:'SHOWCASE'}]);try{assert.equal(single.host.querySelectorAll('.detail-gallery-thumb').length,1);assert.match(single.host.querySelector('.detail-gallery-count').textContent,/1 \/ 1/);assert.equal(single.host.querySelector('.detail-gallery-nav'),null);}finally{await single.close();}
});

test('entitlement expiry states do not turn missing disclosure into permanent',async()=>{
 const p=await gallery([]);try{const now=Date.parse('2026-10-09T12:00:00Z');assert.match(p.expiryLabel({expiresAt:null,expiryState:'MISSING'},now),/期限未提供/);assert.match(p.expiryLabel({expiresAt:null,expiryState:'PERMANENT'},now),/长期权益/);assert.match(p.expiryLabel({expiresAt:'2026-10-10T12:00:00Z',expiryState:'TIMED'},now),/到期/);assert.match(p.expiryLabel({expiresAt:'2026-10-08T12:00:00Z',expiryState:'TIMED'},now),/已到期/);}finally{await p.close();}
});

test('combined detail keeps rental version binding and remounts confirmation on identity change',async()=>{
 const window=new Window({url:'http://127.0.0.1:3100/accounts/example'});Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,Node:window.Node,DocumentFragment:window.DocumentFragment,MutationObserver:window.MutationObserver,CustomEvent:window.CustomEvent,NodeFilter:window.NodeFilter,IS_REACT_ACT_ENVIRONMENT:true,getComputedStyle:window.getComputedStyle.bind(window)});Object.defineProperty(globalThis,'navigator',{value:window.navigator,configurable:true});
 let session={status:'authenticated',userId:'A'},mounts=0,lastProps;
 function Panel(props){lastProps=props;const [instance]=React.useState(()=>++mounts);return React.createElement('div',{'data-confirmation-instance':instance});}
 const file=tree+'/apps/web/src/components/market/listing-detail.tsx',m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(tree);m.require=n=>n.endsWith('.css')?{}:n==='@/components/order/rental-confirm-panel'?{RentalConfirmPanel:Panel}:n==='@/components/session/user-session-provider'?{useUserSession:()=>session}:n==='@/components/favorites/favorite-button'?{FavoriteButton:()=>null,FavoriteNotice:()=>null}:n==='@/components/ui/tooltip'?tooltip:n==='@/components/delta/login-method-icon'?{LoginMethodIcon:()=>null}:n==='@/components/delta/account-card'?{accountHref:card.accountHref,composeGridTitle:card.composeGridTitle,isHaff:()=>false,orderedQuoteResources:()=>[],skinChipTone:()=>'',moneyValue:(v,f)=>v??f}:n.startsWith('@/')?{}:n==='next/link'?()=>null:rq(n);
 m._compile(ts.transpileModule(fs.readFileSync(file,'utf8').replace('function ReadyDetail(','export function ReadyDetail('),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
 const host=window.document.createElement('div');window.document.body.append(host);const root=rq('react-dom/client').createRoot(host),data={id:'account',gameId:'game',versionId:'version',releaseId:'release',title:'combined',displayNo:'TEST',conditionLines:[],resourceLines:[],skinTags:[],media:[],entitlementNames:[],termLabel:'1天',resourceTotalLabel:'¥295.91',haffRentLabel:'¥256.41',itemResourceTotalLabel:'¥39.50'};
 const render=async()=>React.act(async()=>root.render(React.createElement(m.exports.ReadyDetail,{data,back:{href:'/',label:'返回'},activeAnchor:'detail-info'})));
  try{await render();assert.deepEqual(lastProps,{accountId:'account',gameId:'game',versionId:'version',releaseId:'release',autoQuote:true,reference:{total:'¥295.91',haff:'¥256.41',items:'¥39.50'}});assert.equal(mounts,1);await render();assert.equal(mounts,1);session={status:'authenticated',userId:'B'};await render();assert.equal(mounts,2);data.historicalReadOnly=true;await render();assert.equal(host.querySelector('[data-confirmation-instance]'),null);assert.match(host.textContent,/历史只读/);}finally{await React.act(async()=>root.unmount());await window.happyDOM.abort();}
});

test('detail presentation keeps fields unique, copy bound to public number, and unknown money honest', async () => {
 const window=new Window({url:'http://127.0.0.1:4220/accounts/a'});Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,Node:window.Node,DocumentFragment:window.DocumentFragment,MutationObserver:window.MutationObserver,CustomEvent:window.CustomEvent,NodeFilter:window.NodeFilter,IS_REACT_ACT_ENVIRONMENT:true,getComputedStyle:window.getComputedStyle.bind(window)});Object.defineProperty(globalThis,'navigator',{value:window.navigator,configurable:true});
 let copied=null;Object.defineProperty(window.navigator,'clipboard',{value:{writeText:async value=>{copied=value;}},configurable:true});
 const view=await import('../src/lib/listing-view.ts'), filters=await import('../src/lib/listing-filters.ts');
 const file=tree+'/apps/web/src/components/market/listing-detail.tsx',m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(tree);
 m.require=n=>n.endsWith('.css')?{}:n==='next/link'?props=>React.createElement('a',props):n==='@/components/order/rental-confirm-panel'?{RentalConfirmPanel:props=>React.createElement('div',null,React.createElement('p',{className:'account-reference-price'},props.reference.total),React.createElement('button',null,'本人报价'))}:n==='@/components/session/user-session-provider'?{useUserSession:()=>({status:'guest'})}:n==='@/components/favorites/favorite-button'?{FavoriteButton:()=>null,FavoriteNotice:()=>null}:n==='@/lib/listing-view'?view:n==='@/lib/listing-filters'?filters:n==='@/components/ui/tooltip'?tooltip:n==='@/components/delta/login-method-icon'?{LoginMethodIcon:()=>null}:n==='@/components/delta/account-card'?{accountHref:card.accountHref,composeGridTitle:card.composeGridTitle,isHaff:l=>l.unitLabel==='哈夫币',orderedQuoteResources:d=>d.resourceLines.filter(l=>l.unitLabel!=='哈夫币'),skinChipTone:()=>'',moneyValue:v=>v??'待确认'}:n.startsWith('@/')?{}:rq(n);
 const source=fs.readFileSync(file,'utf8').replace('function ReadyDetail(','export function ReadyDetail(').replace('function unitPriceText(','export function unitPriceText(');m._compile(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
 const host=window.document.createElement('div');window.document.body.append(host);const root=rq('react-dom/client').createRoot(host);
 const line={itemId:'six',code:'level6_round',name:'六级子弹',quantity:'60',quantityLabel:'1组（60发）',unitLabel:'发',costAmount:'10.00',costLabel:'¥10.00',unitPriceLabel:'¥10.00000000 / 60 发'};
 const data={id:'a',title:'100M derived title',gameName:'三角洲行动',publicTitle:null,displayNo:null,publishedAt:'2026-10-08T07:33:16Z',resourceLines:[{...line,itemId:'haff',unitLabel:'哈夫币',quantity:'100000000',quantityLabel:'100 M',costAmount:'256.41'},line],conditionLines:[{key:'vit_level',value:'7级'},{key:'service_window',value:'00:00–24:00'},{key:'safe_box_code',value:'顶级安全箱(3*3)'},{key:'grading_code',value:'钻石'},{key:'character_level',value:'60级'}],skinTags:[],media:[],entitlementNames:[],resourceTotalLabel:'¥295.91',haffRentLabel:'¥256.41',itemResourceTotalLabel:'¥39.50',depositLabel:null,payableTotalLabel:null,termLabel:'10天',description:'Original public remark'};
 const render=()=>React.act(async()=>root.render(React.createElement(m.exports.ReadyDetail,{data,back:{href:'/accounts?game=g',label:'返回列表'}})));
 try {
  await render();assert.equal(host.querySelector('h1').textContent,'100M 哈夫币 · 3×3安全箱 · 钻石段位 60级');assert.equal(host.querySelector('h1').classList.contains('sr-only'),false);assert.equal(host.querySelector('.account-identity time').textContent,'发布时间 2026-10-08 15:33');assert.equal(host.querySelector('.account-detail-info .account-number-row')!==null,true);assert.equal(host.querySelector('.account-detail-info .account-facts'),null);assert.equal(host.querySelectorAll('.account-core .account-fact').length,13);assert.equal(host.querySelector('[aria-label="复制账号编号"]').disabled,true);assert.match(host.querySelector('.account-number-row').textContent,/未提供/);
  assert.equal(host.querySelectorAll('nav,[role="tablist"]').length,0);assert.equal(host.querySelectorAll('.account-summary-conditions > div').length,4);for(const label of ['上号方式','每日消耗','推算租期','配合上号'])assert.equal([...host.querySelectorAll('dt')].filter(n=>n.textContent===label).length,1);for(const label of ['哈夫币','安全箱','游戏段位','角色等级'])assert.equal([...host.querySelectorAll('dt')].filter(n=>n.textContent===label).length,1);assert.equal([...host.querySelectorAll('dt')].filter(n=>n.textContent==='体力').length,1);assert.equal(host.querySelectorAll('.account-core .account-fact').length,13);assert.equal(host.querySelectorAll('.account-reference-price').length,1);assert.equal(host.querySelectorAll('.account-stock-table tbody tr').length,1);assert.equal(host.querySelector('.account-reference-price').textContent,'¥295.91');assert.ok(!host.textContent.includes('无需押金'));assert.ok(!host.textContent.includes('支付与订单功能尚未开放'));assert.match(host.textContent,/Original public remark/);assert.ok(!host.textContent.includes('100M derived title'));
  assert.equal(m.exports.unitPriceText(line),'¥10 / 组');assert.equal(m.exports.unitPriceText({...line,code:'df_billable_top_insure_card',unitPriceLabel:'¥5.00000000 / 1 天'}),'¥5 / 天');assert.equal(m.exports.unitPriceText({...line,code:'df_billable_barrett_bullet',unitPriceLabel:'¥0.50000000 / 1 发'}),'¥0.5 / 发');assert.equal(m.exports.unitPriceText({...line,unitPriceLabel:null}),'未确认');
  assert.equal(host.querySelector('.account-detail-deal'),null);data.rentalMode='fast';await render();assert.match(host.querySelector('.account-detail-deal').textContent,/特惠.*极速出租/);data.rentalMode='ordinary';await render();assert.equal(host.querySelector('.account-detail-deal'),null);
  assert.ok(!host.textContent.includes('7×24'));assert.ok(!host.textContent.includes('已审核'));assert.ok(!host.textContent.includes('资金安全'));
  await React.act(async()=>host.querySelector('.account-share').click());assert.equal(copied,'http://127.0.0.1:4220/accounts/a');assert.match(host.querySelector('.account-link-notice').textContent,/已复制/);
  data.id='other';await render();assert.equal(host.querySelector('.account-link-notice'),null);data.id='a';data.resourceTotalLabel=null;await render();assert.equal(host.querySelector('.account-reference-price').textContent,'待确认');data.resourceTotalLabel='¥295.91';
  data.displayNo='202610080194';await render();assert.equal(host.querySelector('[aria-label="复制账号编号"]').disabled,false);await React.act(async()=>host.querySelector('[aria-label="复制账号编号"]').click());assert.equal(copied,'202610080194');assert.match(host.querySelector('[role="status"]').textContent,/已复制/);
  data.id='b';data.displayNo=null;await render();assert.equal(host.querySelector('[aria-label="复制账号编号"]').disabled,true);assert.equal(host.querySelector('.account-copy-note'),null);
 } finally {await React.act(async()=>root.unmount());await window.happyDOM.abort();}
});
