import assert from 'node:assert/strict';import {test} from 'node:test';import {createRequire,Module} from 'node:module';import {readFileSync} from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const tree=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),require=createRequire(tree+'/package.json'),React=require('react'),{Window}=require('happy-dom'),ts=require('typescript');
const client=require(tree+'/apps/web/src/lib/distribution-earnings-client.ts'),wallet=require(tree+'/apps/web/src/lib/personal-wallet-client.ts');
const compiled=ts.transpileModule(readFileSync(tree+'/apps/web/src/components/account/personal-earnings.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
const at='2026-10-04T00:00:00.000000Z',old={id:'history:one',origin:'LEGACY_MYSQL',state:'SETTLED',role:'RENTER_REFERRAL',amount:{currency:'CNY',unit:'cent',amountCents:'1234'},occurredAt:at,dueAt:null,dueAtKnowledge:'UNKNOWN',fundsDisposition:'HISTORICAL_STATUS_ONLY',recoveryRequiredCents:null,includedInOpening:true,version:null,accountingEffect:'OBSERVATION_ONLY_NO_NEW_CREDIT',businessReference:{type:'LEGACY_UNRESOLVED',id:'legacy'},channelArrivalKnowledge:'UNKNOWN'};
const native={...old,id:'native:two',origin:'NATIVE',state:'RECOVERY_REQUIRED',role:'OWNER_REFERRAL',amount:{currency:'CNY',unit:'cent',amountCents:'1000'},dueAt:at,dueAtKnowledge:'KNOWN',fundsDisposition:'SETTLED',recoveryRequiredCents:'1000',includedInOpening:false,version:'3',accountingEffect:'EXISTING_LEDGER_EVENT',businessReference:{type:'RENTAL_ORDER',id:'order'}};
const base=user=>({contractVersion:'distribution-earnings.read.v1',subjectId:user,snapshotVersion:'v1',asOf:at});
const page=(user,items=[old,native])=>({...base(user),state:'ALL',knowledge:'UNKNOWN',count:null,mappedRecordCount:String(items.length),reason:'HISTORICAL_EARNINGS_COVERAGE_NOT_CLOSED',totalAmountKnowledge:'UNKNOWN',items,nextCursor:null});
async function probe(fetcher){const w=new Window({url:'http://127.0.0.1:4200/account?view=invite'}),previous=globalThis.fetch;Object.assign(globalThis,{window:w,document:w.document,HTMLElement:w.HTMLElement,Element:w.Element,Node:w.Node,Event:w.Event,MouseEvent:w.MouseEvent,IS_REACT_ACT_ENVIRONMENT:true});Object.defineProperty(globalThis,'navigator',{value:w.navigator,configurable:true});globalThis.fetch=fetcher;const session={status:'authenticated',userId:'user_A',identityVersion:1,revalidations:0,revalidate(){this.revalidations++;}},m=new Module(tree+'/earnings-ui-probe.cjs');m.filename=tree+'/earnings-ui-probe.cjs';m.paths=Module._nodeModulePaths(tree);m.require=name=>{if(name==='next/link')return({scroll:_scroll,...props})=>React.createElement('a',props);if(name==='@/components/session/user-session-provider')return{useUserSession:()=>session,useUserSessionStore:()=>({getSnapshot:()=>session})};if(name==='@/lib/distribution-earnings-client')return client;if(name==='@/lib/personal-wallet-client')return wallet;if(name==='@/lib/order-client')return require(tree+'/apps/web/src/lib/order-client.ts');if(name.endsWith('.css'))return{};return require(name);};m._compile(compiled,m.filename);const host=w.document.createElement('div');w.document.body.append(host);const root=require('react-dom/client').createRoot(host),settle=async()=>{for(let i=0;i<3;i++)await React.act(async()=>{await new Promise(setImmediate);});};return{host,session,settle,async render(){await React.act(async()=>root.render(React.createElement(m.exports.PersonalEarnings,{scope:session.userId+':'+session.identityVersion})));await settle();},async click(label){const button=[...host.querySelectorAll('button')].find(b=>b.textContent.includes(label));assert(button);await React.act(async()=>button.dispatchEvent(new w.MouseEvent('click',{bubbles:true})));await settle();return button;},async close(){await React.act(async()=>root.unmount());await w.happyDOM.abort();globalThis.fetch=previous;}};}
test('actual earnings component preserves partial truth, shows original history and returns focus to its row',async()=>{let lists=0;const p=await probe(async url=>{if(String(url).includes('/history%3Aone'))return Response.json({...base('user_A'),item:old});lists++;return Response.json(page('user_A'));});try{await p.render();assert.match(p.host.textContent,/已确认 2 条 · 总数待核定/);const button=await p.click('购买分佣');assert.match(p.host.querySelector('.earning-detail').textContent,/已包含在期初余额，不会再次入账/);assert.match(p.host.querySelector('.earning-detail').textContent,/未核定/);assert.equal(document.activeElement,p.host.querySelector('h4'));await p.click('返回收益列表');assert.equal(document.activeElement,button);assert.equal(lists,1);}finally{await p.close();}});
test('recovery detail preserves unsettled debt instead of claiming a reversal or payout',async()=>{const p=await probe(async url=>Response.json(String(url).includes('/native%3Atwo')?{...base('user_A'),item:native}:page('user_A')));try{await p.render();await p.click('上架分佣');const text=p.host.querySelector('.earning-detail').textContent;assert.match(text,/待追回金额/);assert.match(text,/尚未完成扣回/);assert.doesNotMatch(text,/已到账|已扣回/);}finally{await p.close();}});
test('definite 401 clears list and detail and revalidates shared identity',async()=>{let denied=false;const p=await probe(async()=>denied?Response.json({error:{code:'UNAUTHENTICATED'}},{status:401}):Response.json(page('user_A')));try{await p.render();assert.equal(p.host.querySelectorAll('.earning-record').length,2);denied=true;await p.click('重新读取');assert.equal(p.host.querySelectorAll('.earning-record').length,0);assert.equal(p.session.revalidations,1);}finally{await p.close();}});
test('late previous identity earnings never replace the new subject list',async()=>{let phase='old',resolveOld;const pending=new Promise(r=>resolveOld=r),p=await probe(async()=>phase==='old'?pending:Response.json(page('user_B',[{...old,amount:{...old.amount,amountCents:'9900'}}])));try{await p.render();phase='new';p.session.userId='user_B';p.session.identityVersion=2;await p.render();await React.act(async()=>resolveOld(Response.json(page('user_A'))));await p.settle();assert.match(p.host.textContent,/99\.00/);assert.doesNotMatch(p.host.textContent,/12\.34/);}finally{resolveOld(Response.json(page('user_A')));await p.close();}});
test('next-page snapshot drift clears stale records instead of joining incompatible states',async()=>{const p=await probe(async url=>Response.json(String(url).includes('cursor=')?{...page('user_A',[native]),snapshotVersion:'changed',mappedRecordCount:'2'}:{...page('user_A',[old]),mappedRecordCount:'2',nextCursor:'next'}));try{await p.render();await p.click('加载更多收益');assert.equal(p.host.querySelectorAll('.earning-record').length,0);assert.match(p.host.textContent,/收益记录已变化/);}finally{await p.close();}});
