import assert from 'node:assert/strict';
import {test} from 'node:test';
import {loadSupplyIntent,prepareSupplyIntent,acceptSupplyIntent,retainUncertainSupplyIntent,clearSupplyIntent,SupplyIntentStorageError} from '../src/lib/supply-write-intent.ts';
function storage(){const map=new Map();globalThis.window={sessionStorage:{getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)}};return map;}
const input={userId:'owner-a',gameId:'game',accountId:'account',action:'save-draft',key:'original',body:{expectedRevision:'1',attributes:{secret_kd:'1.50'},description:'public remark'}};
test('supply intent freezes the exact subject/target/action/key/body and survives age',()=>{storage();const first=prepareSupplyIntent(input);assert.deepEqual(prepareSupplyIntent(input),first);assert.equal(loadSupplyIntent('owner-b'),null);assert.throws(()=>prepareSupplyIntent({...input,key:'new'}));assert.throws(()=>prepareSupplyIntent({...input,accountId:'other'}));const old={...first,createdAt:'2000-01-01T00:00:00.000Z'};window.sessionStorage.setItem('zzsh.supply-write.v1:owner-a',JSON.stringify(old));assert.equal(loadSupplyIntent('owner-a').key,'original');clearSupplyIntent(old);assert.equal(loadSupplyIntent('owner-a'),null);});
test('accepted record has a minimal receipt and cannot become a new POST',()=>{storage();const record=prepareSupplyIntent(input),accepted=acceptSupplyIntent(record,{accountId:'account',revision:'2'});assert.equal(loadSupplyIntent('owner-a').phase,'accepted');assert.throws(()=>prepareSupplyIntent(input));clearSupplyIntent(accepted);assert.equal(loadSupplyIntent('owner-a'),null);});
test('late storage updates match the entire original responsibility and never downgrade accepted',()=>{storage();const first=prepareSupplyIntent(input);assert.equal(clearSupplyIntent(first),true);const next=prepareSupplyIntent({...input,accountId:'another',key:'next',body:{expectedRevision:'2'}}),before=window.sessionStorage.getItem('zzsh.supply-write.v1:owner-a');assert.throws(()=>acceptSupplyIntent(first,{accountId:'account'}),SupplyIntentStorageError);assert.throws(()=>retainUncertainSupplyIntent(first),SupplyIntentStorageError);assert.equal(clearSupplyIntent(first),false);assert.equal(window.sessionStorage.getItem('zzsh.supply-write.v1:owner-a'),before);const accepted=acceptSupplyIntent(next,{accountId:'another',revision:'3'});assert.deepEqual(retainUncertainSupplyIntent(next),accepted);assert.deepEqual(acceptSupplyIntent(next,{accountId:'another',revision:'999'}),accepted);for(const patch of [{gameId:'other'},{accountId:'other'},{action:'quote'},{body:{expectedRevision:'other'}},{createdAt:'2000-01-01T00:00:00.000Z'}]){assert.equal(clearSupplyIntent({...accepted,...patch}),false);assert.deepEqual(loadSupplyIntent('owner-a'),accepted);}});
test('storage/corruption/secret/file/function failures block writes instead of fabricating an empty store',()=>{const map=storage();assert.throws(()=>prepareSupplyIntent({...input,body:{uploadToken:'secret'}}),SupplyIntentStorageError);assert.throws(()=>prepareSupplyIntent({...input,body:{run:()=>{}}}),SupplyIntentStorageError);assert.throws(()=>prepareSupplyIntent({...input,body:{file:new Blob(['x'])}}),SupplyIntentStorageError);for(const body of ['invalid',true,[],null]){map.set('zzsh.supply-write.v1:owner-a',JSON.stringify({...input,version:1,phase:'pending',createdAt:new Date().toISOString(),body}));assert.throws(()=>loadSupplyIntent('owner-a'),SupplyIntentStorageError);}map.set('zzsh.supply-write.v1:owner-a','broken');assert.throws(()=>loadSupplyIntent('owner-a'),SupplyIntentStorageError);Object.defineProperty(window,'sessionStorage',{get(){throw Error('denied')}});assert.throws(()=>prepareSupplyIntent(input),SupplyIntentStorageError);});
