import {randomUUID} from "node:crypto";
import {isHttpOrigin,userCookies,readBoundedBody} from "../../../../../lib/user-proxy.ts";
import {parseNativeReservation} from "../../../../../lib/personal-wallet-client.ts";
const api=process.env.ZZSH_API_ORIGIN??'',web=process.env.ZZSH_WEB_ORIGIN??'';
const error=(status:number,code:string,id:string)=>Response.json({error:{code,message:'钱包读取暂不可用',requestId:id}},{status,headers:{'cache-control':'no-store','x-request-id':id}});
function cents(value:unknown){if(typeof value!=='string'||! /^-?(0|[1-9]\d{0,23})$/.test(value)||value==='-0')throw Error();return value;}
function money(value:any){if(!value||value.currency!=='CNY'||value.unit!=='cent'||!['KNOWN','UNKNOWN'].includes(value.knowledge))throw Error();if((value.knowledge==='KNOWN')!==(value.amountCents!==null))throw Error();return {currency:'CNY',unit:'cent',knowledge:value.knowledge,amountCents:value.amountCents===null?null:cents(value.amountCents)};}
const coverage=(c:any)=>({knowledge:c?.knowledge,origin:c?.origin,cutoff:c?.cutoff,coverageVersion:c?.coverageVersion,reason:c?.reason});
const context=(b:any)=>({contractVersion:b.contractVersion,subjectId:b.subjectId,asOf:b.asOf,snapshotVersion:b.snapshotVersion,coverage:coverage(b.coverage)});
function entry(e:any){if(!e||e.schemaVersion!==1||typeof e.id!=='string'||!['AVAILABLE','REFUND_PAYABLE'].includes(e.bucket)||!['POSTED','HISTORICAL'].includes(e.kind)||typeof e.includedInOpening!=='boolean')throw Error();return {schemaVersion:1,id:e.id,occurredAt:e.occurredAt,importedAt:e.importedAt,bucket:e.bucket,deltaCents:cents(e.deltaCents),kind:e.kind,includedInOpening:e.includedInOpening,sourceKind:e.sourceKind,sourceId:e.sourceId,source:{type:e.source?.type??'UNKNOWN',system:e.source?.system??null,entity:e.source?.entity??null,id:e.source?.id??null},businessReference:{type:e.businessReference?.type??'UNKNOWN',id:e.businessReference?.id??null,number:e.businessReference?.number??null},balanceAfterCents:e.balanceAfterCents===null?null:cents(e.balanceAfterCents)};}
export async function GET(request:Request,{params}:{params:Promise<{path?:string[]}>}){
 const id=`req_finance_${randomUUID().replaceAll('-','')}`;if(!isHttpOrigin(api)||!isHttpOrigin(web))return error(503,'EVIDENCE_UNAVAILABLE',id);if(request.headers.has('authorization'))return error(403,'FORBIDDEN',id);
 const parts=(await params).path??[];if(parts.length>2||parts.length&&parts[0]!=='entries')return error(404,'NOT_FOUND',id);
 const q=new URL(request.url).searchParams;for(const k of q.keys())if(!['limit','cursor','bucket'].includes(k))return error(400,'INVALID_ARGUMENT',id);
 if(parts.length!==1&&q.size)return error(400,'INVALID_ARGUMENT',id);
 const url=new URL('/api/v1/users/me/wallet'+(parts.length?'/'+parts.map(encodeURIComponent).join('/'):''),api);url.search=q.toString();const headers=new Headers({origin:web,'x-request-id':id});const cookie=userCookies(request.headers.get('cookie'));if(cookie)headers.set('cookie',cookie);
 try{const deadline=AbortSignal.timeout(15000),r=await fetch(url,{headers,cache:'no-store',redirect:'error',signal:deadline});const body=JSON.parse(new TextDecoder().decode(await readBoundedBody(r,256*1024,deadline)));
  if(!r.ok)return error(r.status,typeof body.error?.code==='string'&&/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(body.error.code)?body.error.code:'INTERNAL_ERROR',id);
  let result;if(body.wallet){const w=body.wallet;const buckets=Object.fromEntries(['available','reserved','restricted','pendingEarnings','refundPayable'].map(k=>[k,money(w.buckets?.[k])]));result={wallet:{contractVersion:w.contractVersion,subjectId:w.subjectId,asOf:w.asOf,currency:'CNY',coverage:{knowledge:w.coverage?.knowledge,origin:w.coverage?.origin,cutoff:w.coverage?.cutoff,coverageVersion:w.coverage?.coverageVersion,reason:w.coverage?.reason},ledgerRevision:w.ledgerRevision,readRevision:w.readRevision,snapshotVersion:w.snapshotVersion,buckets,withdrawable:{...money(w.withdrawable),reasonCodes:w.withdrawable.reasonCodes},nativeWithdrawal:parseNativeReservation(w.nativeWithdrawal)}};}
  else if(body.entry)result={...context(body),entry:entry(body.entry)};else{if(!Array.isArray(body.items)||!body.totals||!Array.isArray(body.totals.byBucket))throw Error();result={...context(body),bucket:body.bucket,items:body.items.map(entry),totals:{count:body.totals.count,byBucket:body.totals.byBucket.map((t:any)=>{if(!['AVAILABLE','REFUND_PAYABLE'].includes(t.bucket))throw Error();return {bucket:t.bucket,count:t.count,postedNetCents:cents(t.postedNetCents),coveredHistoricalNetCents:cents(t.coveredHistoricalNetCents),uncoveredHistoricalNetCents:cents(t.uncoveredHistoricalNetCents),coveredCount:t.coveredCount,uncoveredCount:t.uncoveredCount};}),historicalCoverage:body.totals.historicalCoverage,meaning:body.totals.meaning},nextCursor:body.nextCursor};}
  return Response.json(result,{headers:{'cache-control':'no-store','x-request-id':id,'x-content-type-options':'nosniff'}});
 }catch{return error(502,'INTERNAL_ERROR',id);}
}
export function POST(){return error(404,'NOT_FOUND','req_finance_method');}
