import {test} from 'node:test';import {strict as assert} from 'node:assert';import type {Pool,PoolClient} from 'pg';
import {assertControlledWithdrawalResource,readControlledWithdrawalQuote,recoverControlledWithdrawal,applyWithdrawalResult} from '../src/finance/controlled-withdrawal-store';
import {queryOriginalControlledPayout} from '../src/finance/controlled-withdrawal-worker';
import {createHash} from 'node:crypto';
import {finishControlledWithdrawal,ownerLocalWithdrawalPolicy,quoteControlledWithdrawal,reserveControlledWithdrawal} from '../src/finance/controlled-withdrawal';
const resource={name:'zzsh_test_m2_auth_auth_compat',oid:820148,role:'zzsh_m2_auth_compat_r',marker:'zzsh:m2-auth-test:v1',complete:true};
test('controlled persistence rejects absent/partial schema and foreign database/role even with local-looking data',async()=>{
 for(const changed of [{complete:false},{name:'production'},{oid:1},{role:'zzsh'},{marker:'wrong'}]){const c={query:async()=>({rows:[{...resource,...changed}]})} as unknown as PoolClient;await assert.rejects(assertControlledWithdrawalResource(c),e=>(e as {status?:number}).status===503);}
});
test('quote is fail-closed before any business write on the current unupgraded resource',async()=>{const sql:string[]=[];const pool={connect:async()=>({release(){},query:async(text:string)=>{sql.push(text);return{rows:text.startsWith('SELECT current_database')?[{...resource,complete:false}]:[]};}})} as unknown as Pool;await assert.rejects(readControlledWithdrawalQuote(pool,{userId:'fixture',sessionId:'session',requestId:'req_test'},{amountCents:'200',destinationId:'fixture',policyVersion:'owner',expectedWalletVersion:'1'}),e=>(e as {status?:number}).status===503);assert(sql.includes('ROLLBACK'));assert(!sql.some(s=>/\bINSERT\b|\bUPDATE\b|\bDELETE\b/.test(s)));});
test('bounded restored UI plans conserve failure release and original-key timeout then payout',()=>{
 const facts={userId:'fixture',active:true,localAdmissionEligible:true,coverageKnown:true,availableCents:'1000',ledgerRevision:'1',now:'2026-10-03T18:00:00.000Z',destination:{id:'bank',userId:'fixture',mode:'LOCAL_CONTROLLED' as const,kind:'BANK_CARD' as const,active:true},usage:{start:'2026-10-03T16:00:00.000Z',end:'2026-10-04T16:00:00.000Z',quotaCount:0}};
 const bank=ownerLocalWithdrawalPolicy('BANK_CARD',['fixture']),body={amountCents:'200',destinationId:'bank',policyVersion:bank.version,expectedWalletVersion:'1'},first=reserveControlledWithdrawal('first',quoteControlledWithdrawal(body,bank,facts));assert.equal(first.intent.feeCents,'100');assert.equal(first.intent.netCents,'100');
 const token='12345678901234567890123456789012',lease={tokenHash:require('node:crypto').createHash('sha256').update(token).digest('hex'),until:'2026-10-03T18:01:00.000Z'};
 const failed=finishControlledWithdrawal({...first.intent,state:'SUBMITTING',lease,operationVersion:'2'},'2',token,{mode:'LOCAL_CONTROLLED',intentId:'first',payoutKey:first.intent.payoutKey,outcome:'FAILED',reference:'fixture-failed',unpaidConfirmed:true,transferredCents:'0',chargedFeeCents:'0'},facts.now);assert.equal(failed.ledgerPlan?.kind,'RELEASE');assert.equal(failed.ledgerPlan?.lines[1]?.creditCents,'200');
 const code=ownerLocalWithdrawalPolicy('PAYMENT_CODE',['fixture']),second=reserveControlledWithdrawal('second',quoteControlledWithdrawal({...body,destinationId:'code',policyVersion:code.version},code,{...facts,destination:{...facts.destination,id:'code',kind:'PAYMENT_CODE'}}));assert.equal(second.intent.feeCents,'4');assert.equal(second.intent.netCents,'196');
 const unknown=finishControlledWithdrawal({...second.intent,state:'SUBMITTING',lease,operationVersion:'2'},'2',token,{mode:'LOCAL_CONTROLLED',intentId:'second',payoutKey:second.intent.payoutKey,outcome:'TIMEOUT'},facts.now);assert.equal(unknown.intent.state,'UNKNOWN');assert.equal(unknown.ledgerPlan,null);
 const succeeded=finishControlledWithdrawal({...unknown.intent,lease,operationVersion:'4'},'4',token,{mode:'LOCAL_CONTROLLED',intentId:'second',payoutKey:second.intent.payoutKey,outcome:'SUCCEEDED',reference:'fixture-success',netCents:'196',feeCents:'4'},facts.now);assert.equal(succeeded.ledgerPlan?.kind,'PAYOUT');assert.deepEqual(succeeded.ledgerPlan?.lines.map(l=>[l.debitCents,l.creditCents]),[['200','0'],['0','196'],['0','4']]);
});
function workerProbe(){
 const token='worker-probe-token-0123456789012345',hash=createHash('sha256').update(token).digest('hex'),queries:string[]=[],facts=new Map<string,{evidence_digest:string;producer_lease_hash:string}>();
 const row={id:'probe_intent',user_id:'fixture',destination_id:'code',policy_version:'OWNER_LOCAL_RESTORED_20261003_v1_PAYMENT_CODE',expected_ledger_revision:'1',accepted_at:new Date(),gross_cents:'200',net_cents:'196',fee_cents:'4',payout_key:'unchanged_original_key',state:'UNKNOWN',operation_version:'4',funds_disposition:'RESERVED',terminal:null as any,conflict_digest:null,lease_token_hash:hash as string|null,lease_until:new Date(Date.now()+30000)};
 const pool={connect:async()=>({release(){},query:async(sql:string,args:any[]=[])=>{queries.push(sql);
  if(sql.startsWith('SELECT current_database'))return{rows:[resource]};
  if(sql.startsWith('SELECT user_id'))return{rows:[{user_id:row.user_id}]};
  if(sql.startsWith('SELECT id FROM zzsh_auth_user'))return{rows:[{id:row.user_id}]};
  if(sql.startsWith('SELECT payout_key'))return{rows:[{payout_key:row.payout_key,version:row.operation_version}]};
  if(sql.startsWith('SELECT * FROM zzsh_order.withdrawal_intent'))return{rows:[row]};
  if(sql.includes('FROM zzsh_order.controlled_payout_operation'))return{rows:[]};
  if(sql.startsWith('SELECT evidence_digest'))return{rows:facts.has(args[1])?[facts.get(args[1])]:[]};
  if(sql.startsWith('SELECT date_trunc'))return{rows:[{now:new Date()}]};
  if(sql.startsWith('INSERT INTO zzsh_order.withdrawal_provider_fact')){facts.set(args[3],{evidence_digest:args[5],producer_lease_hash:args[6]});return{rows:[]};}
  if(sql.startsWith('UPDATE zzsh_order.withdrawal_intent')){assert.equal(args[4],null,'TIMEOUT must bind SQL NULL, not JSON null masquerading as terminal evidence');row.state=args[1];row.operation_version=args[2];row.terminal=args[4];row.lease_token_hash=null;return{rows:[row]};}
  if(sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK'||sql.startsWith('SELECT set_config')||sql.startsWith('INSERT INTO "zzsh_iam"."audit_event"')||sql==='SET CONSTRAINTS ALL IMMEDIATE')return{rows:[]};
  throw Error('Unexpected unit-probe SQL: '+sql);
 }})} as unknown as Pool;
 return{pool,row,token,hash,queries,facts};
}
test('no-original-result queries keep payout key but each current lease observation can release its lease',async()=>{const p=workerProbe();const first=await queryOriginalControlledPayout(p.pool,p.row.id,p.row.payout_key,'4');assert.equal(first.evidence.payoutKey,p.row.payout_key);await applyWithdrawalResult(p.pool,p.row.id,'4',p.token,first.resultKey,first.evidence);assert.equal(p.row.lease_token_hash,null);p.row.operation_version='6';p.row.lease_token_hash=p.hash;const next=await queryOriginalControlledPayout(p.pool,p.row.id,p.row.payout_key,'6');assert.notEqual(next.resultKey,first.resultKey);assert.equal(next.evidence.payoutKey,first.evidence.payoutKey);await applyWithdrawalResult(p.pool,p.row.id,'6',p.token,next.resultKey,next.evidence);assert.equal(p.row.lease_token_hash,null);assert.equal(p.row.state,'UNKNOWN');assert(!p.queries.some(sql=>sql.startsWith('INSERT INTO zzsh_order.finance_event')||sql.startsWith('INSERT INTO zzsh_order.settlement_ledger_entry')));});
test('monetary terminal cannot be supplied without matching durable original channel truth',async()=>{const p=workerProbe();await assert.rejects(applyWithdrawalResult(p.pool,p.row.id,'4',p.token,'invented_final',{mode:'LOCAL_CONTROLLED',intentId:p.row.id,payoutKey:p.row.payout_key,outcome:'SUCCEEDED',reference:'invented',netCents:'196',feeCents:'4'}),e=>(e as {status?:number}).status===409);assert.equal(p.row.state,'UNKNOWN');assert(!p.queries.some(sql=>sql.startsWith('INSERT')||sql.startsWith('UPDATE')));});
test('query from a superseded operation version does not create a new observation',async()=>{const p=workerProbe();await assert.rejects(queryOriginalControlledPayout(p.pool,p.row.id,p.row.payout_key,'2'),e=>(e as {status?:number}).status===409);assert.equal(p.facts.size,0);});
test('ACKNOWLEDGED and TIMEOUT bind SQL NULL terminal evidence and keep reserved funds',async()=>{for(const outcome of ['ACKNOWLEDGED','TIMEOUT'] as const){const p=workerProbe();await applyWithdrawalResult(p.pool,p.row.id,'4',p.token,'null_terminal_'+outcome,{mode:'LOCAL_CONTROLLED',intentId:p.row.id,payoutKey:p.row.payout_key,outcome});assert.equal(p.row.terminal,null);assert.equal(p.row.state,outcome==='ACKNOWLEDGED'?'PROCESSING':'UNKNOWN');assert.equal(p.row.funds_disposition,'RESERVED');assert(!p.queries.some(sql=>sql.startsWith('INSERT INTO zzsh_order.finance_event')));}});
