import {test} from 'node:test';import {strict as assert} from 'node:assert';import {createHash} from 'node:crypto';import type {Pool} from 'pg';import type {AppConfig} from '../src/config/config';import {canonicalize} from '../src/supply/content-hash';import {createDeclaredControlledPaymentReader} from '../src/finance/controlled-payment-source';
const input={orderId:'order',merchantOrderNo:'ZZ001',providerTransactionId:'transaction',amountCents:'10000',currency:'CNY',providerPaidAt:'2026-10-04T00:00:00.000Z',requestId:'request'},canonical=canonicalize(input),digest=createHash('sha256').update(canonical).digest('hex'),opts={config:{profile:'test',provider:'fake',testOperationsEnabled:true,database:{target:'local-compose',host:'127.0.0.1',port:55432,name:'zzsh_test_order_existing_order',user:'zzsh_order_existing_order_r'}} as AppConfig,resourceSet:'existing_order',resourceOid:12345,appId:'app',merchantScopeId:'merchant',allowedOrderIds:['order'],approvalDigest:'a'.repeat(64),allowedSourceIds:['source']};
function probe(patch:Record<string,unknown>={},complete=true,payment:Record<string,unknown>|null=null){const sqls:string[]=[],pool={connect:async()=>({release(){},query:async(sql:string)=>{sqls.push(sql);if(sql.startsWith('SELECT d.oid'))return{rows:[{oid:12345,name:opts.config.database.name,role:opts.config.database.user,marker:'zzsh:order-reservation-test:v1',complete}]};if(sql.startsWith('SELECT *'))return{rows:[{id:'source',mode:'LOCAL_CONTROLLED_DECLARED_PAYMENT',app_id:'app',merchant_scope_id:'merchant',approval_digest:opts.approvalDigest,resource_oid:12345,canonical_payment:canonical,payment_digest:digest,order_id:'order',provider_transaction_id:'transaction',merchant_order_no:'ZZ001',source_event_key:'original-event',...patch}]};if(sql.startsWith('SELECT id,order_id,disposition'))return{rows:payment?[payment]:[]};return{rows:[]};}})} as unknown as Pool;return{pool,sqls};}
test('new reader reconstructs the original bounded payment capability solely from durable declared source, without writes',async()=>{const p=probe(),a=await createDeclaredControlledPaymentReader(p.pool,opts).read('source'),b=await createDeclaredControlledPaymentReader(p.pool,opts).read('source');assert.deepEqual(a.fact,b.fact);assert.equal(a.fact.providerTransactionId,'transaction');assert.equal(a.sourceDigest,digest);assert(!p.sqls.some(q=>/^INSERT|^UPDATE|^DELETE/.test(q)));});
test('unknown source/schema and foreign declaration bindings cannot become new payment facts',async()=>{for(const patch of [{payment_digest:'0'.repeat(64)},{app_id:'other'},{approval_digest:'0'.repeat(64)},{order_id:'other'},{resource_oid:9999},{mode:'REAL_BANK_CALLBACK'}]){const p=probe(patch);await assert.rejects(createDeclaredControlledPaymentReader(p.pool,opts).read('source'));assert(!p.sqls.some(q=>/^INSERT|^UPDATE|^DELETE/.test(q)));}const absent=probe({},false);await assert.rejects(createDeclaredControlledPaymentReader(absent.pool,opts).read('source'),e=>(e as {status?:number}).status===503);const outside=probe();await assert.rejects(createDeclaredControlledPaymentReader(outside.pool,opts).read('other'));assert.equal(outside.sqls.length,2);});
test('restorable source never enlarges original controlled-payment resource door to auth or production',()=>{const p=probe();for(const config of [{...opts.config,profile:'prod'},{...opts.config,database:{...opts.config.database,name:'zzsh_test_m2_auth_auth_compat',user:'zzsh_m2_auth_compat_r'}}])assert.throws(()=>createDeclaredControlledPaymentReader(p.pool,{...opts,config:config as AppConfig}));assert.equal(p.sqls.length,0);});
test('absence of original acceptance remains UNKNOWN responsibility and never automatically repeats payment',async()=>{const p=probe(),result=await createDeclaredControlledPaymentReader(p.pool,opts).recover('source');assert.equal(result.acceptanceKnowledge,'UNKNOWN');assert.equal(result.mayReapply,false);assert.equal(result.reason,'ORIGINAL_ACCEPTANCE_NOT_PROVED');assert(!p.sqls.some(q=>/^INSERT|^UPDATE|^DELETE/.test(q)));});
const accepted={id:'payment',order_id:input.orderId,merchant_order_no:input.merchantOrderNo,amount_cents:input.amountCents,currency:input.currency,provider_paid_at:input.providerPaidAt,disposition:'APPLIED'};
test('same transaction key cannot recover a different original amount, currency, time, merchant number or order',async()=>{for(const changed of [{order_id:'different'},{merchant_order_no:'ZZ002'},{amount_cents:'10001'},{currency:'USD'},{provider_paid_at:'2026-10-04T00:00:00.001Z'}]){const p=probe({},true,{...accepted,...changed});await assert.rejects(createDeclaredControlledPaymentReader(p.pool,opts).recover('source'),e=>(e as {status?:number}).status===409);assert(!p.sqls.some(q=>/^(INSERT|UPDATE|DELETE)/.test(q)));}});
test('matching original APPLIED payment without basis stays explicit UNKNOWN and cannot reapply',async()=>{const p=probe({},true,accepted),result=await createDeclaredControlledPaymentReader(p.pool,opts).recover('source');assert.equal(result.acceptanceKnowledge,'KNOWN');assert.equal(result.disposition,'APPLIED');assert.equal(result.basisKnowledge,'UNKNOWN_MISSING_ORIGINAL_BASIS');assert.equal(result.mayReapply,false);});


