import {test} from 'node:test';import {strict as assert} from 'node:assert';import {createHash} from 'node:crypto';import type {Pool} from 'pg';import {canonicalize} from '../src/supply/content-hash';
import {createControlledNoticeReader,type VerifiedControlledNotice} from '../src/finance/controlled-withdrawal-notice';import {receiveTerminalControlledNotice} from '../src/finance/controlled-withdrawal-notice-receiver';
const digest=(v:unknown)=>createHash('sha256').update(canonicalize(v)).digest('hex');
function probe(){const conclusions=new Map<string,any>(),queries:string[]=[],facts=new Map<string,{evidence_digest:string}>(),original={mode:'LOCAL_CONTROLLED',intentId:'intent',payoutKey:'original',outcome:'SUCCEEDED',reference:'op',netCents:'196',feeCents:'4'},late={mode:'LOCAL_CONTROLLED',intentId:'intent',payoutKey:'original',outcome:'FAILED',reference:'op',unpaidConfirmed:true,transferredCents:'0',chargedFeeCents:'0'},terminal={state:'SUCCEEDED',evidenceDigest:digest(original),reference:'op'};
 const row:any={id:'intent',user_id:'user',destination_id:'dest',policy_version:'policy',expected_ledger_revision:'1',accepted_at:new Date(),gross_cents:'200',net_cents:'196',fee_cents:'4',payout_key:'original',state:'SUCCEEDED',operation_version:'5',funds_disposition:'PAYOUT_POSTED',terminal,conflict_digest:null,lease_token_hash:null,lease_until:null};let updates=0,audits=0;
 const pool={connect:async()=>({release(){},query:async(sql:string,args:any[]=[])=>{queries.push(sql);if(sql.startsWith('SELECT current_database'))return{rows:[{name:'zzsh_test_m2_auth_auth_compat',oid:820148,role:'zzsh_m2_auth_compat_r',marker:'zzsh:m2-auth-test:v1',complete:true}]};if(sql.startsWith('SELECT to_regclass'))return{rows:[{present:true}]};if(sql.startsWith('SELECT n.id'))return{rows:[{id:args[0],original_operation_id:'op',evidence_canonical:canonicalize(late),source_digest:digest(late),mode:'LOCAL_CONTROLLED_DECLARED_NOTICE',intent_id:'intent',payout_key:'original'}]};if(sql.startsWith('SELECT details FROM zzsh_iam.audit_event'))return{rows:conclusions.has(args[0])?[{details:conclusions.get(args[0])}]:[]};if(sql.startsWith('SELECT user_id'))return{rows:[{user_id:row.user_id}]};if(sql.startsWith('SELECT id FROM zzsh_auth_user'))return{rows:[{id:row.user_id}]};if(sql.startsWith('SELECT * FROM zzsh_order.withdrawal_intent'))return{rows:[{...row}]};if(sql.startsWith('SELECT evidence_digest'))return{rows:facts.has(args[1])?[facts.get(args[1])]:[]};if(sql.startsWith('SELECT id,evidence_digest'))return{rows:facts.has(args[1])?[{id:'original_notice_fact',...facts.get(args[1])}]:[]};if(sql.startsWith('SELECT date_trunc'))return{rows:[{now:new Date()}]};if(sql.startsWith('UPDATE zzsh_order.withdrawal_intent')){updates++;row.state=args[1];row.operation_version=args[2];if(sql.includes('last_provider_fact_id')){assert.equal(args[3],'PAYOUT_POSTED');assert.deepEqual(JSON.parse(args[4]),terminal);row.conflict_digest=args[5];row.lease_token_hash=null;row.lease_until=null;}else{row.lease_token_hash=args[3];row.lease_until=new Date(args[4]);}return{rows:[{...row}]};}if(sql.startsWith('INSERT INTO zzsh_order.withdrawal_provider_fact')){facts.set(args[3],{evidence_digest:args[5]});return{rows:[]};}if(sql.startsWith('INSERT INTO "zzsh_iam"."audit_event"')){audits++;if(args[4]==='controlled.withdrawal.notice.processed')conclusions.set(args[6],JSON.parse(args[10]));return{rows:[]};}if(['BEGIN','COMMIT','ROLLBACK','SET CONSTRAINTS ALL IMMEDIATE'].includes(sql)||sql.startsWith('SELECT set_config'))return{rows:[]};throw Error('Unexpected receiver unit SQL');}})} as unknown as Pool;
 return{pool,row,queries,facts,terminal,conclusions,get updates(){return updates;},get audits(){return audits;}};
}
test('verified late opposite terminal records reconciliation and preserves original terminal with zero money SQL',async()=>{const p=probe(),reader=createControlledNoticeReader(p.pool,{resourceOid:820148,allowedNoticeIds:['notice']}),notice=await reader('notice');const result=await receiveTerminalControlledNotice(p.pool,notice);assert.equal(result.action,'OBSERVED');assert.equal(p.row.state,'RECONCILIATION_REQUIRED');assert.equal(p.row.operation_version,'7');assert.equal(p.row.funds_disposition,'PAYOUT_POSTED');assert.deepEqual(p.row.terminal,p.terminal);assert.equal(p.facts.size,1);assert.equal(p.audits,3);assert(!p.queries.some(s=>s.startsWith('INSERT INTO zzsh_order.finance_event')||s.startsWith('INSERT INTO zzsh_order.settlement_ledger_entry')));const count=p.updates;assert.equal((await receiveTerminalControlledNotice(p.pool,notice)).action,'REPLAY');assert.equal(p.updates,count);assert.equal(p.facts.size,1);});
test('new notice on frozen reconciliation never clears state or submits a second payout; fabricated capability rejects before SQL',async()=>{const p=probe(),reader=createControlledNoticeReader(p.pool,{resourceOid:820148,allowedNoticeIds:['notice','notice2']}),first=await reader('notice');await receiveTerminalControlledNotice(p.pool,first);const count=p.updates,second=await reader('notice2');assert.equal((await receiveTerminalControlledNotice(p.pool,second)).action,'ALREADY_FROZEN');assert.equal(p.updates,count);assert.equal(p.conclusions.size,2);assert.equal(p.conclusions.get('notice2').conclusion,'ALREADY_FROZEN');const auditCount=p.audits;assert.equal((await receiveTerminalControlledNotice(p.pool,second)).action,'REPLAY');assert.equal(p.audits,auditCount);const prior=p.queries.length;await assert.rejects(receiveTerminalControlledNotice(p.pool,{...second} as VerifiedControlledNotice));assert.equal(p.queries.length,prior);});
test('claim, original result and exact conclusion use one transaction and bind original fact proof',async()=>{const p=probe(),notice=await createControlledNoticeReader(p.pool,{resourceOid:820148,allowedNoticeIds:['notice']})('notice');p.queries.length=0;await receiveTerminalControlledNotice(p.pool,notice);assert.equal(p.queries.filter(q=>q==='BEGIN').length,1);assert.equal(p.queries.filter(q=>q==='COMMIT').length,1);assert.equal(p.conclusions.get('notice').providerFactId,'original_notice_fact');assert.match(p.conclusions.get('notice').resultKey,/^controlled-notice-/);});
test('an orphan original fact is retained as UNKNOWN instead of deriving its conclusion from another notice RCR',async()=>{const p=probe(),notice=await createControlledNoticeReader(p.pool,{resourceOid:820148,allowedNoticeIds:['notice']})('notice'),key='controlled-notice-'+createHash('sha256').update('notice').digest('hex').slice(0,48);p.facts.set(key,{evidence_digest:notice.sourceDigest});p.row.state='RECONCILIATION_REQUIRED';const prior=p.updates;await assert.rejects(receiveTerminalControlledNotice(p.pool,notice),e=>(e as {status?:number}).status===503);assert.equal(p.updates,prior);assert.equal(p.facts.size,1);assert.equal(p.conclusions.size,0);});
function faultPool(p:ReturnType<typeof probe>,fault:'BEFORE_CONCLUSION'|'COMMIT_ACK_LOSS'){
 let once=true;return{connect:async()=>{const c=await p.pool.connect();let snapshot:{row:any;facts:Map<string,any>;conclusions:Map<string,any>}|null=null;return{release(){c.release();},query:async(sql:string,args:any[]=[])=>{
  if(sql==='BEGIN')snapshot={row:structuredClone(p.row),facts:new Map(p.facts),conclusions:new Map(p.conclusions)};
  if(sql==='ROLLBACK'&&snapshot){Object.assign(p.row,snapshot.row);p.facts.clear();for(const[k,v]of snapshot.facts)p.facts.set(k,v);p.conclusions.clear();for(const[k,v]of snapshot.conclusions)p.conclusions.set(k,v);snapshot=null;}
  if(fault==='BEFORE_CONCLUSION'&&once&&sql.startsWith('INSERT INTO "zzsh_iam"."audit_event"')&&args[4]==='controlled.withdrawal.notice.processed'){once=false;throw Error('Injected conclusion storage failure after original result SQL');}
  const result=await c.query(sql,args);if(sql==='COMMIT'){snapshot=null;if(fault==='COMMIT_ACK_LOSS'&&once&&p.conclusions.size){once=false;throw Error('Injected COMMIT ACK loss');}}return result;
 }};}} as unknown as Pool;
}
test('failure after result SQL rolls back claim, fact and conclusion together; original source can be read again',async()=>{
 const p=probe(),pool=faultPool(p,'BEFORE_CONCLUSION'),before=structuredClone(p.row),notice=await createControlledNoticeReader(pool,{resourceOid:820148,allowedNoticeIds:['notice']})('notice');
 await assert.rejects(receiveTerminalControlledNotice(pool,notice));assert.deepEqual(p.row,before);assert.equal(p.facts.size,0);assert.equal(p.conclusions.size,0);
 const reread=await createControlledNoticeReader(pool,{resourceOid:820148,allowedNoticeIds:['notice']})('notice');await receiveTerminalControlledNotice(pool,reread);assert.equal(p.facts.size,1);assert.equal(p.conclusions.size,1);
});
test('COMMIT ACK loss recovers original notice proof through a new reader without another claim or fact',async()=>{
 const p=probe(),pool=faultPool(p,'COMMIT_ACK_LOSS'),notice=await createControlledNoticeReader(pool,{resourceOid:820148,allowedNoticeIds:['notice']})('notice');await assert.rejects(receiveTerminalControlledNotice(pool,notice));const updates=p.updates,original=p.conclusions.get('notice');assert.equal(p.facts.size,1);
 const reread=await createControlledNoticeReader(pool,{resourceOid:820148,allowedNoticeIds:['notice']})('notice'),result=await receiveTerminalControlledNotice(pool,reread);assert.equal(result.action,'REPLAY');assert.equal(result.operationVersion,original.operationVersion);assert.equal(p.updates,updates);assert.equal(p.facts.size,1);assert.equal(p.conclusions.size,1);
});
