import {test} from 'node:test';import {strict as assert} from 'node:assert';import type {PoolClient} from 'pg';
import {createPaymentDistributionStore} from '../src/finance/distribution-payment-store';
const scope={resourceSet:'existing_order',resourceOid:12345,approvalDigest:'a'.repeat(64),allowedOrderIds:['order']};
test('payment prepares the complete deduplicated user set in database order and rejects a missing beneficiary',async()=>{
 for(const missing of [false,true]){const seen:{sql:string;args:any[]}[]=[],c={query:async(sql:string,args:any[]=[])=>{seen.push({sql,args});if(sql.startsWith('SELECT d.oid'))return{rows:[{oid:12345,name:'zzsh_test_order_existing_order',role:'zzsh_order_existing_order_r',marker:'zzsh:order-reservation-test:v1'}]};if(sql.startsWith('SELECT to_regclass'))return{rows:[{complete:true}]};if(sql.startsWith('SELECT * FROM zzsh_order.distribution_order_admission'))return{rows:[{id:'admit',revision:'1',native_creation_audit_id:'audit'}]};if(sql.startsWith('SELECT id,renter_user_id'))return{rows:[{id:'order',renter_user_id:'renter',owner_user_id:'owner'}]};if(sql.startsWith('SELECT id FROM zzsh_iam.audit_event'))return{rows:[{}],rowCount:1};if(sql.startsWith('SELECT r.*'))return{rows:[{child_user_id:'renter',parent_user_id:'owner'},{child_user_id:'owner',parent_user_id:'leader'}]};if(sql.startsWith('SELECT id FROM zzsh_auth_user."user" WHERE id=ANY'))return{rows:(missing?['renter','owner']:['leader','owner','renter']).map(id=>({id}))};if(sql.startsWith('SELECT user_id FROM zzsh_order.distribution_participant'))throw Error('PARTICIPANT_BOUNDARY');return{rows:[]};}} as unknown as PoolClient;
  await assert.rejects(createPaymentDistributionStore(scope).prepare(c,'order'),e=>missing?(e as {status?:number}).status===503:(e as Error).message==='PARTICIPANT_BOUNDARY');const locked=seen.find(q=>q.sql.includes('WHERE id=ANY'));assert(locked);assert(locked.sql.includes('ORDER BY id FOR UPDATE'));assert.deepEqual(locked.args,[['renter','owner','leader']]);assert.equal(seen.filter(q=>q.sql.startsWith('SELECT user_id FROM zzsh_order.distribution_participant')).length,missing?0:1);assert(!seen.some(q=>/^(INSERT|UPDATE|DELETE)/.test(q.sql)));
 }
});
function probe(patch:Record<string,unknown>={},complete=false){const seen:{sql:string;args:any[]}[]=[],c={query:async(sql:string,args:any[]=[])=>{seen.push({sql,args});if(sql.startsWith('SELECT d.oid'))return{rows:[{oid:12345,name:'zzsh_test_order_existing_order',role:'zzsh_order_existing_order_r',marker:'zzsh:order-reservation-test:v1',...patch}]};if(sql.startsWith('SELECT to_regclass'))return{rows:[{complete}]};if(sql.startsWith('SELECT * FROM zzsh_order.distribution_order_admission'))return{rows:[]};return{rows:[]};}} as PoolClient;return{c,seen};}
test('order scope cannot masquerade as auth_compat or accept an implicit resource/allowlist',async()=>{for(const patch of [{name:'zzsh_test_m2_auth_auth_compat',oid:820148,role:'zzsh_m2_auth_compat_r'},{oid:9999},{role:'zzsh_order_existing_order_m'},{marker:'foreign'}]){const p=probe(patch);await assert.rejects(createPaymentDistributionStore(scope).prepare(p.c,'order'));assert.equal(p.seen.length,1);}for(const change of [{allowedOrderIds:[]},{approvalDigest:'unreviewed'},{resourceSet:'auth-compat'},{resourceOid:0}])assert.throws(()=>createPaymentDistributionStore({...scope,...change}));});
test('missing schema, unadmitted and out-of-allowlist orders leave normal payment behavior unchanged without writes',async()=>{const store=createPaymentDistributionStore(scope),outside=probe();assert.equal(await store.prepare(outside.c,'other'),null);assert.equal(outside.seen.length,0);for(const complete of [false,true]){const p=probe({},complete);assert.equal(await store.prepare(p.c,'order'),null);assert(!p.seen.some(q=>/^(INSERT|UPDATE|DELETE)/.test(q.sql)));}});
test('copied or fabricated prepared binding is rejected before SQL and never creates ledger entries',async()=>{const p=probe();await assert.rejects(createPaymentDistributionStore(scope).record(p.c,{orderId:'order'},'confirmation','request'));assert.equal(p.seen.length,0);});
test('a genuine v1 quote contentHash does not crash preparation or fabricate a rental mode',async()=>{
 const writes:string[]=[],hash='b'.repeat(64),c={query:async(sql:string,args:any[]=[])=>{
  if(sql.startsWith('SELECT d.oid'))return{rows:[{oid:12345,name:'zzsh_test_order_existing_order',role:'zzsh_order_existing_order_r',marker:'zzsh:order-reservation-test:v1'}]};
  if(sql.startsWith('SELECT to_regclass'))return{rows:[{complete:true}]};
  if(sql.startsWith('SELECT * FROM zzsh_order.distribution_order_admission'))return{rows:[{id:'admit',revision:'1',native_creation_audit_id:'native_audit'}]};
  if(sql.startsWith('SELECT id,renter_user_id'))return{rows:[{id:'order',renter_user_id:'renter',owner_user_id:'owner',game_id:'delta',currency:'CNY',quote_snapshot:{schemaVersion:1,contentHash:hash,platformFullProfit:{currency:'CNY',unit:'yuan',scale:2,amount:'10.00'}}}]};
  if(sql.startsWith('SELECT id FROM zzsh_auth_user."user" WHERE id=ANY'))return{rows:args[0].map((id:string)=>({id}))};if(sql.startsWith('SELECT id FROM zzsh_iam.audit_event'))return{rows:[{}],rowCount:1};
  if(sql.startsWith('SELECT leader_knowledge'))return{rows:[{leader_knowledge:'KNOWN_NONE'}]};
  if(sql.startsWith('SELECT pg_current_xact_id'))return{rows:[{id:'100'}]};
  if(sql.startsWith('SELECT p.id,p.order_id'))return{rows:[{id:'confirmation',order_id:'order',source:'CONTROLLED',accepted_at:'2026-10-04T00:00:00.000000Z'}]};
  if(sql.startsWith('INSERT INTO zzsh_order.payment_distribution_basis')){writes.push(args[5]);return{rows:[]};}
  return{rows:[]};
 }} as unknown as PoolClient;
 const store=createPaymentDistributionStore(scope),prepared=await store.prepare(c,'order');assert(prepared);const result=await store.record(c,prepared,'confirmation','request');assert.equal(result.basis?.accountMode,null);assert.equal(result.basis?.estimateBaseCents,'1000');assert.equal(writes.length,1);assert.equal(result.basis?.roles.every(r=>r.status==='UNKNOWN_POLICY'),true);
});
test('original basis read requires durable APPLIED payment ownership and cannot create missed basis',async()=>{const p=probe();await assert.rejects(createPaymentDistributionStore(scope).readOriginal(p.c,'order','confirmation'));assert(!p.seen.some(q=>/^(INSERT|UPDATE|DELETE)/.test(q.sql)));assert(p.seen.some(q=>q.sql.includes("p.disposition='APPLIED'")));});
test('a pooled client reused in another transaction cannot reuse previous prepared eligibility',async()=>{
 let xid='100';const sqls:string[]=[],c={query:async(sql:string,args:any[]=[])=>{sqls.push(sql);if(sql.startsWith('SELECT d.oid'))return{rows:[{oid:12345,name:'zzsh_test_order_existing_order',role:'zzsh_order_existing_order_r',marker:'zzsh:order-reservation-test:v1'}]};if(sql.startsWith('SELECT to_regclass'))return{rows:[{complete:true}]};if(sql.startsWith('SELECT * FROM zzsh_order.distribution_order_admission'))return{rows:[{id:'admit',revision:'1',native_creation_audit_id:'native_audit'}]};if(sql.startsWith('SELECT id,renter_user_id'))return{rows:[{id:'order',renter_user_id:'renter',owner_user_id:'owner',game_id:'delta',currency:'CNY',quote_snapshot:{}}]};if(sql.startsWith('SELECT id FROM zzsh_auth_user."user" WHERE id=ANY'))return{rows:args[0].map((id:string)=>({id}))};if(sql.startsWith('SELECT id FROM zzsh_iam.audit_event'))return{rows:[{id:'native_audit'}],rowCount:1};if(sql.startsWith('SELECT leader_knowledge'))return{rows:[{leader_knowledge:'KNOWN_NONE'}]};if(sql.startsWith('SELECT pg_current_xact_id'))return{rows:[{id:xid}]};return{rows:[]};}} as PoolClient;
 const store=createPaymentDistributionStore(scope),prepared=await store.prepare(c,'order');assert(prepared);xid='101';const before=sqls.length;await assert.rejects(store.record(c,prepared,'confirmation','request'),e=>(e as {status?:number}).status===409);assert.equal(sqls.length-before,1);assert(!sqls.some(s=>/^INSERT|^UPDATE|^DELETE/.test(s)));assert(!sqls.some(s=>s.includes('FROM zzsh_order.payment_confirmation')));
});
