import {test} from 'node:test';import {strict as assert} from 'node:assert';import {createHash} from 'node:crypto';
import {freezePaymentDistributionBasis,readOriginalPaymentDistributionBasis,type PaymentReferralFacts} from '../src/finance/distribution-payment-basis';import {canonicalize} from '../src/supply/content-hash';import {validateDistributionPolicy} from '../src/finance/distribution-policy';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex'),h='a'.repeat(64),config=(rate='5')=>validateDistributionPolicy({schema:'distribution-policy.v1',scope:'LOCAL_CONTROLLED',enabled:true,participation:'AUTO_AT_REGISTRATION',depth:1,selfRebate:false,accountModes:['ordinary','custom'],minimumAccrualCents:'1',settlementDelayDays:7,levels:[{code:'L1',rank:1,default:true,renterPercent:rate,ownerPercent:rate,upgrade:null}]}),policy=(rate='5')=>{const c=config(rate);return{versionId:'policy_'+rate,digest:sha(canonicalize(c)),config:c};};
const facts:PaymentReferralFacts[]=(['RENTER_REFERRAL','OWNER_REFERRAL'] as const).map((role,n)=>({role,partyUserId:'party_'+n,relation:{knowledge:'KNOWN_PARENT',id:'relation_'+n,childUserId:'party_'+n,parentUserId:'parent_'+n,sourceDigest:(n===0?'b':'c').repeat(64)},beneficiary:{userId:'parent_'+n,active:true,eligibility:'ELIGIBLE',commissionFrozen:false,levelCode:'L1'}}));
const input=()=>({orderId:'order',gameId:'delta',currency:'CNY' as const,confirmationId:'confirmation',acceptedAt:'2026-10-04T04:00:00.123456Z',paymentDigest:h,admissionId:'admission',admissionRevision:'1',origin:'NATIVE' as const,accountMode:'ordinary',estimate:{baseCents:'10000',sourceDigest:h},policy:policy(),facts:structuredClone(facts)});
test('first payment freezes both roles, exact ratios, original microseconds and a copy of policy; no money plan',()=>{const i=input(),basis=freezePaymentDistributionBasis(i);assert.equal(basis.acceptedAt,i.acceptedAt);assert.deepEqual([basis.orderId,basis.confirmationId,basis.admissionId,basis.admissionRevision,basis.paymentDigest,basis.estimateDigest],['order','confirmation','admission','1',h,h]);assert.deepEqual(basis.roles.map(r=>[r.role,r.partyUserId,r.beneficiaryUserId,r.relationId,r.relationDigest]),[['OWNER_REFERRAL','party_1','parent_1','relation_1','c'.repeat(64)],['RENTER_REFERRAL','party_0','parent_0','relation_0','b'.repeat(64)]]);assert.deepEqual(basis.roles.map(r=>[r.status,r.percent,r.estimatedCents]),[['ELIGIBLE','5','500'],['ELIGIBLE','5','500']]);i.policy.config.accountModes.push('custom');i.policy.config.levels[0]!.renterPercent='30';assert.equal(basis.policyConfig?.accountModes.length,2);assert.equal(basis.roles[1]?.percent,'5');assert(!('ledgerPlan'in basis));assert.equal(readOriginalPaymentDistributionBasis(basis,{orderId:'order',confirmationId:'confirmation',paymentDigest:h}).knowledge,'KNOWN');});
test('replay reads original basis and missing original never acquires the new head',()=>{const basis=freezePaymentDistributionBasis(input()),changed=freezePaymentDistributionBasis({...input(),policy:policy('30')});assert.notEqual(basis.digest,changed.digest);assert.equal(readOriginalPaymentDistributionBasis(basis,{orderId:'order',confirmationId:'confirmation',paymentDigest:h}).basis?.roles[0]?.percent,'5');assert.equal(readOriginalPaymentDistributionBasis(null,{orderId:'order',confirmationId:'confirmation',paymentDigest:h}).reason,'MISSING_ORIGINAL_BASIS');assert.throws(()=>readOriginalPaymentDistributionBasis(basis,{orderId:'other',confirmationId:'confirmation',paymentDigest:h}));assert.throws(()=>readOriginalPaymentDistributionBasis({...basis,policyVersion:'new'}, {orderId:'order',confirmationId:'confirmation',paymentDigest:h}));});
test('legacy/unknown origin, missing role or changed immutable policy digest cannot generate a new basis',()=>{for(const origin of ['LEGACY_MYSQL','UNKNOWN'] as const)assert.throws(()=>freezePaymentDistributionBasis({...input(),origin}));assert.throws(()=>freezePaymentDistributionBasis({...input(),facts:[facts[0]!]}));assert.throws(()=>freezePaymentDistributionBasis({...input(),policy:{...policy(),digest:'b'.repeat(64)}}));});
test('disabled, fast and proven no-parent remain distinct from unknown relations',()=>{const off=policy();off.config.enabled=false;off.digest=sha(canonicalize(off.config));assert(freezePaymentDistributionBasis({...input(),policy:off}).roles.every(r=>r.status==='SKIPPED_DISABLED'));assert(freezePaymentDistributionBasis({...input(),accountMode:'fast'}).roles.every(r=>r.status==='SKIPPED_FAST'));const none=structuredClone(facts);none[0]!.relation={knowledge:'KNOWN_NONE',id:null,childUserId:'party_0',parentUserId:null,sourceDigest:null};none[0]!.beneficiary=null;assert.equal(freezePaymentDistributionBasis({...input(),facts:none}).roles.find(r=>r.role==='RENTER_REFERRAL')?.status,'SKIPPED_NO_PARENT');none[0]!.relation.knowledge='UNKNOWN';const unknown=freezePaymentDistributionBasis({...input(),facts:none});assert.equal(unknown.roles.find(r=>r.role==='RENTER_REFERRAL')?.status,'UNKNOWN_RELATION');assert.equal(unknown.roles.find(r=>r.role==='OWNER_REFERRAL')?.status,'UNKNOWN_ESTIMATE_CONSERVATION');});
test('qualification, level, missing estimate and source minimum do not collapse into zero',()=>{const missing=structuredClone(facts);missing[0]!.beneficiary!.eligibility='UNKNOWN';assert.equal(freezePaymentDistributionBasis({...input(),facts:missing}).roles.find(r=>r.role==='RENTER_REFERRAL')?.status,'UNKNOWN_PARTICIPANT');missing[0]!.beneficiary!.eligibility='ELIGIBLE';missing[0]!.beneficiary!.levelCode='MISSING';assert.equal(freezePaymentDistributionBasis({...input(),facts:missing}).roles.find(r=>r.role==='RENTER_REFERRAL')?.status,'UNKNOWN_LEVEL');assert(freezePaymentDistributionBasis({...input(),estimate:null}).roles.every(r=>r.status==='UNKNOWN_ESTIMATE'&&r.estimatedCents===null));assert(freezePaymentDistributionBasis({...input(),estimate:{baseCents:'1',sourceDigest:h}}).roles.every(r=>r.status==='SKIPPED_BELOW_MIN'&&r.estimatedCents===null));});
test('rounded pair that exceeds source becomes recorded uncertainty and does not reject the original payment',()=>{const basis=freezePaymentDistributionBasis({...input(),policy:policy('50'),estimate:{baseCents:'1',sourceDigest:h}});assert(basis.roles.every(r=>r.status==='UNKNOWN_ESTIMATE_CONSERVATION'&&r.percent==='50'&&r.estimatedCents===null));});
test('distributor status and commission freeze are separate source facts; missing mode or freeze is UNKNOWN',()=>{const frozen=structuredClone(facts);frozen[0]!.beneficiary!.commissionFrozen=true;assert.equal(freezePaymentDistributionBasis({...input(),facts:frozen}).roles.find(r=>r.role==='RENTER_REFERRAL')?.status,'SKIPPED_INELIGIBLE');frozen[0]!.beneficiary!.commissionFrozen=null;assert.equal(freezePaymentDistributionBasis({...input(),facts:frozen}).roles.find(r=>r.role==='RENTER_REFERRAL')?.status,'UNKNOWN_PARTICIPANT');assert(freezePaymentDistributionBasis({...input(),accountMode:null}).roles.every(r=>r.status==='UNKNOWN_MODE'));});

test('wrong relation child or beneficiary cannot acquire eligibility under the original role',()=>{
 for(const mismatch of ['child','beneficiary'] as const){const i=input();if(mismatch==='child')i.facts[0]!.relation.childUserId='foreign';else i.facts[0]!.beneficiary!.userId='foreign';const frozen=freezePaymentDistributionBasis(i);assert.equal(frozen.roles.find(r=>r.role==='RENTER_REFERRAL')!.status,mismatch==='child'?'UNKNOWN_RELATION':'UNKNOWN_PARTICIPANT');assert(frozen.roles.every(r=>r.estimatedCents===null));}
 const frozen=freezePaymentDistributionBasis(input());for(const patch of [{confirmationId:'foreign'},{paymentDigest:'b'.repeat(64)}])assert.throws(()=>readOriginalPaymentDistributionBasis(frozen,{orderId:'order',confirmationId:'confirmation',paymentDigest:h,...patch}));
});
