import {test} from 'node:test';import {strict as assert} from 'node:assert';import {createHash} from 'node:crypto';import {canonicalize} from '../src/supply/content-hash';
import {freezePaymentDistributionBasis,type PaymentReferralFacts} from '../src/finance/distribution-payment-basis';import {validateDistributionPolicy} from '../src/finance/distribution-policy';import {prepareAccrualFromFrozenPayment,type CompletedDistributionFacts} from '../src/finance/distribution-accrual';
const h='a'.repeat(64),cfg=validateDistributionPolicy({schema:'distribution-policy.v1',scope:'LOCAL_CONTROLLED',enabled:true,participation:'AUTO_AT_REGISTRATION',depth:1,selfRebate:false,accountModes:['ordinary','custom'],minimumAccrualCents:'1',settlementDelayDays:7,levels:[{code:'L1',rank:1,default:true,renterPercent:'5',ownerPercent:'5',upgrade:null}]}),policy={versionId:'p1',config:cfg,digest:createHash('sha256').update(canonicalize(cfg)).digest('hex')},facts:PaymentReferralFacts[]=(['RENTER_REFERRAL','OWNER_REFERRAL'] as const).map((role,n)=>({role,partyUserId:'party'+n,relation:{knowledge:'KNOWN_PARENT',id:'rel'+n,childUserId:'party'+n,parentUserId:'parent'+n,sourceDigest:(n===0?'b':'c').repeat(64)},beneficiary:{userId:'parent'+n,active:true,eligibility:'ELIGIBLE',commissionFrozen:false,levelCode:'L1'}}));
const basis=(base='10000')=>freezePaymentDistributionBasis({orderId:'o1',gameId:'delta',currency:'CNY',confirmationId:'p1',acceptedAt:'2026-10-04T03:00:00.000000Z',paymentDigest:h,admissionId:'a1',admissionRevision:'1',origin:'NATIVE',accountMode:'ordinary',estimate:{baseCents:base,sourceDigest:h},policy,facts});
const posting:CompletedDistributionFacts={origin:'NATIVE',orderId:'o1',confirmationId:'p1',postingId:'posting1',postingDigest:'d'.repeat(64),postedAt:'2026-10-04T03:12:10.123456Z',classification:'NORMAL',calculationMode:'SYSTEM',capturedCents:'10000',ownerNetCents:'4000',renterRefundCents:'1000',platformContributionCents:'5000',compensationFeeCents:'200'};
test('completed normal source uses frozen5 percent on final base4800, preserves microseconds and frozen7day due',()=>{const frozen=basis(),result=prepareAccrualFromFrozenPayment(frozen,posting);assert.equal(result.knowledge,'KNOWN');assert.equal(result.baseCents,'4800');assert.deepEqual(result.items.map(i=>[i.amountCents,i.dueAt]),[['240','2026-10-11T03:12:10.123456Z'],['240','2026-10-11T03:12:10.123456Z']]);assert.deepEqual(result.items.map(i=>[i.beneficiaryUserId,i.role,i.policyVersion,i.basisDigest,i.postingDigest,i.relationDigest]),[['parent1','OWNER_REFERRAL','p1',frozen.digest,'d'.repeat(64),'c'.repeat(64)],['parent0','RENTER_REFERRAL','p1',frozen.digest,'d'.repeat(64),'b'.repeat(64)]]);assert.deepEqual(result.items.map(i=>JSON.parse(i.economicKey)),[['NATIVE_RENTAL_REFERRAL','NATIVE','zzsh','rental_order','o1','parent1','OWNER_REFERRAL'],['NATIVE_RENTAL_REFERRAL','NATIVE','zzsh','rental_order','o1','parent0','RENTER_REFERRAL']]);assert(!('ledgerPlan'in result));});
test('old skipped below-minimum roles are not added when final base becomes larger; final zero for admitted role is recorded',()=>{assert.equal(prepareAccrualFromFrozenPayment(basis('1'),posting).items.length,0);const zero=prepareAccrualFromFrozenPayment(basis(),{...posting,compensationFeeCents:'5000'});assert.equal(zero.items.length,2);assert(zero.items.every(i=>i.amountCents==='0'));});
test('early and approved manual completion use the original frozen ratio and final immutable accounting amounts',()=>{for(const patch of [{calculationMode:'MANUAL' as const},{classification:'EARLY' as const},{calculationMode:'MANUAL' as const,classification:'EARLY' as const}]){const r=prepareAccrualFromFrozenPayment(basis(),{...posting,...patch,ownerNetCents:'3000',renterRefundCents:'2000'});assert.equal(r.knowledge,'KNOWN');assert.equal(r.baseCents,'4800');assert.deepEqual(r.items.map(i=>i.amountCents),['240','240']);}});
test('unknown classification, missing original and negative final base remain UNKNOWN rather than fabricated zero',()=>{for(const patch of [{calculationMode:'UNKNOWN' as const},{classification:'UNKNOWN' as const},{compensationFeeCents:'5001'}]){const r=prepareAccrualFromFrozenPayment(basis(),{...posting,...patch});assert.equal(r.knowledge,'UNKNOWN');assert.equal(r.reason,'UNKNOWN_BASE_MAPPING');assert.equal(r.baseCents,null);}assert.equal(prepareAccrualFromFrozenPayment(null,posting).reason,'MISSING_ORIGINAL_BASIS');});
test('legacy, foreign payment and unbalanced source cannot generate new earnings',()=>{assert.throws(()=>prepareAccrualFromFrozenPayment(basis(),{...posting,origin:'LEGACY_MYSQL'}));assert.throws(()=>prepareAccrualFromFrozenPayment(basis(),{...posting,confirmationId:'other'}));assert.throws(()=>prepareAccrualFromFrozenPayment(basis(),{...posting,ownerNetCents:'3999'}));});
test('economic root excludes mutable policy/version/posting timestamps but retains role and beneficiary',()=>{const a=prepareAccrualFromFrozenPayment(basis(),posting),b=prepareAccrualFromFrozenPayment(basis(),{...posting,postingId:'correction',postingDigest:'b'.repeat(64),postedAt:'2026-10-05T03:12:10.123456Z'});assert.equal(a.items[0]!.economicKey,b.items[0]!.economicKey);assert.notEqual(a.digest,b.digest);assert.notEqual(a.items[0]!.economicKey,a.items[1]!.economicKey);});

// Independent HALF_UP boundary: two 50% shares of 2 cents are 1+1; of 1 cent are 1+1 and exceed the source.
test('final cumulative referral pair cannot exceed its source after per-role rounding',()=>{
 const config=structuredClone(cfg);config.levels[0]!.renterPercent='50';config.levels[0]!.ownerPercent='50';
 const frozen=freezePaymentDistributionBasis({orderId:'o1',gameId:'delta',currency:'CNY',confirmationId:'p1',acceptedAt:'2026-10-04T03:00:00.000000Z',paymentDigest:h,admissionId:'a1',admissionRevision:'1',origin:'NATIVE',accountMode:'ordinary',estimate:{baseCents:'10000',sourceDigest:h},policy:{versionId:'half',config,digest:createHash('sha256').update(canonicalize(config)).digest('hex')},facts});
 const exact=prepareAccrualFromFrozenPayment(frozen,{...posting,compensationFeeCents:'4998'});assert.deepEqual(exact.items.map(i=>i.amountCents),['1','1']);assert.equal(exact.baseCents,'2');
 assert.throws(()=>prepareAccrualFromFrozenPayment(frozen,{...posting,compensationFeeCents:'4999'}),/exceeds source base/);
});
