import {test} from 'node:test';import {strict as assert} from 'node:assert';import type {Pool} from 'pg';
import {parseEarningsQuery,earningProjection,readMyDistributionEarnings} from '../src/finance/distribution-earning-read';
const actor={userId:'self',sessionId:'session'},key={keyId:'test',secret:'x'.repeat(40)},at='2026-10-04T00:00:00.000000Z';
const legacy={id:'history:one',origin:'LEGACY_MYSQL',state:'SETTLED',role:'RENTER_REFERRAL',source_amount:'12.34',occurred_at:at,due_at:null,funds_disposition:'HISTORICAL_STATUS_ONLY',recovery_required_cents:null,included:true,version:'0',order_id:'legacy-id'};
const native={...legacy,id:'native:two',origin:'NATIVE',state:'RECOVERY_REQUIRED',source_amount:'1234',funds_disposition:'SETTLED',recovery_required_cents:'1234',version:'3',due_at:at,included:false};
function probe(nativeInstalled:boolean,rows:Record<string,any>[],coverage='RECONCILED_OPENING'){
 const seen:{sql:string;args:any[]}[]=[],pool={connect:async()=>({release(){},query:async(sql:string,args:any[]=[])=>{seen.push({sql,args});
  if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};
  if(sql.startsWith('SELECT "suspended"'))return{rows:[{suspended:false}]};
  if(sql.includes('FROM "zzsh_iam"."user_identity_state"'))return{rows:[{accountStatus:'ACTIVE'}]};
  if(sql.startsWith('SELECT 1 FROM "zzsh_auth_user"."session"'))return{rows:[{}],rowCount:1};
  if(sql.startsWith('SELECT to_regclass'))return{rows:[{history:true,native:nativeInstalled}]};
  if(sql.startsWith('SELECT origin'))return{rows:coverage?[{origin:coverage}]:[]};
  if(sql.includes(' AS count,md5'))return{rows:[{count:String(rows.length),digest:'source-digest'}]};
  if(sql.startsWith('SELECT to_char'))return{rows:[{at}]};
  if(sql.startsWith('WITH earnings'))return{rows:args.length===2?rows.filter(r=>r.id===args[1]):rows.filter(r=>!args[4]||r.id<args[4]).slice(0,args[5])};
  throw Error('Unexpected read query');}})} as unknown as Pool;return{pool,seen};
}
test('legacy settled observation keeps original cents and cannot become new credit or paid-channel proof',()=>{const r=earningProjection(legacy);assert.equal(r.amount.amountCents,'1234');assert.equal(r.includedInOpening,true);assert.equal(r.accountingEffect,'OBSERVATION_ONLY_NO_NEW_CREDIT');assert.equal(r.dueAt,null);assert.equal(r.dueAtKnowledge,'UNKNOWN');assert.equal(r.channelArrivalKnowledge,'UNKNOWN');assert.equal(earningProjection({...legacy,state:'EXPIRED'}).state,'EXPIRED');});
test('native recovery projects the original settled liability without pretending it has been reversed',()=>{const r=earningProjection(native);assert.equal(r.state,'RECOVERY_REQUIRED');assert.equal(r.fundsDisposition,'SETTLED');assert.equal(r.recoveryRequiredCents,'1234');for(const patch of [{recovery_required_cents:'1233'},{funds_disposition:'REVOKED'},{due_at:null},{role:'TASK_REFERRAL'},{source_amount:'1.2'}])assert.throws(()=>earningProjection({...native,...patch}));});
test('earnings query rejects caller-selected identity, duplicate keys and unbounded pages',()=>{assert.deepEqual(parseEarningsQuery(new URLSearchParams()),{state:'ALL',limit:20,cursor:null});for(const q of ['userId=other','state=ALL&state=PENDING','limit=51','state=PAID','limit=0'])assert.throws(()=>parseEarningsQuery(new URLSearchParams(q)));});
test('missing native schema still returns own historical evidence without fabricating a complete total',async()=>{const p=probe(false,[legacy]),r=await readMyDistributionEarnings(p.pool,actor,{state:'ALL',limit:20,cursor:null},key);assert.equal(r.knowledge,'UNKNOWN');assert.equal(r.count,null);assert.equal(r.mappedRecordCount,'1');assert.equal(r.items?.[0]?.amount.amountCents,'1234');assert(!p.seen.some(q=>q.sql.startsWith('WITH')&&q.sql.includes('rental_referral_earning')));assert(p.seen.filter(q=>q.sql.startsWith('WITH')).every(q=>q.args[0]==='self'));assert(!p.seen.some(q=>/^(INSERT|UPDATE|DELETE)/.test(q.sql)));});
test('source-version cursor permits native paging but rejects another session and foreign detail',async()=>{const row={...native,state:'SETTLED',recovery_required_cents:null},p=probe(true,[{...row,id:'native:z'},{...row,id:'native:a'}],'NATIVE_GENESIS'),q={state:'ALL' as const,limit:1,cursor:null};const first=await readMyDistributionEarnings(p.pool,actor,q,key);assert.equal(first.knowledge,'KNOWN');assert.equal(first.count,'2');assert(first.nextCursor);const second=await readMyDistributionEarnings(p.pool,actor,{...q,cursor:first.nextCursor!},key);assert.equal(second.items?.[0]?.id,'native:a');await assert.rejects(readMyDistributionEarnings(p.pool,{...actor,sessionId:'other'},{...q,cursor:first.nextCursor!},key),e=>(e as {status?:number}).status===409);await assert.rejects(readMyDistributionEarnings(p.pool,actor,q,key,'native:foreign'),e=>(e as {status?:number}).status===404);});
