import {test} from 'node:test';import {strict as assert} from 'node:assert';import {createHash} from 'node:crypto';import type {Pool} from 'pg';import {canonicalize} from '../src/supply/content-hash';import {createDistributionEarningStore} from '../src/finance/distribution-earning-store';import type {RentalEarning} from '../src/finance/distribution-mechanism';
import {freezePaymentDistributionBasis,type PaymentReferralFacts} from '../src/finance/distribution-payment-basis';import {validateDistributionPolicy} from '../src/finance/distribution-policy';
const h='a'.repeat(64),scope={resourceSet:'existing_order',resourceOid:12345,approvalDigest:h,allowedOrderIds:['order']},sha=(v:string)=>createHash('sha256').update(v).digest('hex');
test('pending accrual retains original payment/posting/basis in the earning while derived lines have a null source pointer',async()=>{
 const at='2026-10-05T00:00:00.000000Z',payment={id:'payment',order_id:'order',source:'CONTROLLED',merchant_scope_id:'scope',provider_transaction_id:'tx',merchant_order_no:'merchant',amount_cents:'10000',currency:'CNY',provider_paid_at:at,accepted_at:at};
 const config=validateDistributionPolicy({schema:'distribution-policy.v1',scope:'LOCAL_CONTROLLED',enabled:true,participation:'AUTO_AT_REGISTRATION',depth:1,selfRebate:false,accountModes:['ordinary'],minimumAccrualCents:'1',settlementDelayDays:0,levels:[{code:'L1',rank:1,default:true,renterPercent:'5',ownerPercent:'5',upgrade:null}]});
 const facts:PaymentReferralFacts[]=(['RENTER_REFERRAL','OWNER_REFERRAL'] as const).map((role,i)=>({role,partyUserId:'party'+i,relation:{knowledge:'KNOWN_PARENT',id:'relation'+i,childUserId:'party'+i,parentUserId:'parent'+i,sourceDigest:h},beneficiary:{userId:'parent'+i,active:true,eligibility:'ELIGIBLE',commissionFrozen:false,levelCode:'L1'}}));
 const basis=freezePaymentDistributionBasis({orderId:'order',gameId:'delta',currency:'CNY',confirmationId:'payment',acceptedAt:at,paymentDigest:sha(canonicalize(payment)),admissionId:'admission',admissionRevision:'1',origin:'NATIVE',accountMode:'ordinary',estimate:{baseCents:'5000',sourceDigest:h},policy:{versionId:'policy',config,digest:sha(canonicalize(config))},facts});const {digest,...body}=basis;
 const posting={id:'posting',order_id:'order',payment_confirmation_id:'payment',version_hash:h,early:false,manual_reason:null,captured_cents:'10000',owner_net_cents:'4000',renter_refund_cents:'1000',platform_contribution_cents:'5000',compensation_fee_cents:'200',posted_at:at};
 const seen:{sql:string;args:any[]}[]=[],pool={connect:async()=>({release(){},query:async(sql:string,args:any[]=[])=>{seen.push({sql,args});if(sql.startsWith('SELECT d.oid'))return{rows:[{oid:12345,name:'zzsh_test_order_existing_order',role:'zzsh_order_existing_order_r',marker:'zzsh:order-reservation-test:v1',complete:true}]};if(sql.startsWith('SELECT p.id,p.order_id,p.payment_confirmation_id'))return{rows:[posting]};if(sql.startsWith('SELECT p.id,p.order_id,p.source'))return{rows:[payment]};if(sql.startsWith('SELECT canonical_basis'))return{rows:[{canonical_basis:canonicalize(body),basis_digest:digest}]};if(sql.startsWith('SELECT 1 FROM zzsh_order.wallet_coverage'))return{rows:[{}],rowCount:1};if(sql.startsWith('SELECT ledger_revision'))return{rows:[{revision:'1',available:'0'}]};return{rows:[]};}})} as unknown as Pool;
 const result=await createDistributionEarningStore(scope).accrue(pool,'order','request');assert.equal(result.knowledge,'KNOWN');assert.equal(result.items.length,2);
 const lines=seen.filter(q=>q.sql.startsWith('INSERT INTO zzsh_order.settlement_ledger_entry'));assert.equal(lines.length,4);assert(lines.every(q=>q.args[7]===null));
 const roots=seen.filter(q=>q.sql.startsWith('INSERT INTO zzsh_order.rental_referral_earning'));assert.equal(roots.length,2);for(const q of roots){assert.equal(q.args[2],'order');assert.equal(q.args[3],'payment');assert.equal(q.args[4],'posting');assert.equal(q.args[9],digest);assert.equal(q.args[10],sha(canonicalize(posting)));assert.equal(JSON.parse(q.args[11]).source.digest,q.args[10]);}
 assert(!seen.some(q=>q.sql.startsWith('INSERT INTO zzsh_order.payment_confirmation')));
});
test('settlement and reversal lines never consume the original payment-source pointer a second time',async()=>{
 for(const [state,action,version]of [['PENDING','SETTLE','1'],['PENDING','REVOKE','1'],['SETTLED','REVOKE','2'],['RECOVERY_REQUIRED','RECOVER','3']] as const){const p=probe(state,'150');await createDistributionEarningStore(scope).transition(p.pool,'earning',action,version,'request',action==='SETTLE'?undefined:'original_reversal');const lines=p.seen.filter(q=>q.sql.startsWith('INSERT INTO zzsh_order.settlement_ledger_entry'));assert.equal(lines.length,2);for(const line of lines){assert.equal(line.args[7],null);assert.equal(JSON.parse(line.args[8]).earningId,'earning');assert(line.args[1]);}assert(!p.seen.some(q=>q.sql.startsWith('UPDATE zzsh_order.payment_confirmation')));}
});
function probe(state:'PENDING'|'SETTLED'|'RECOVERY_REQUIRED'|'REVOKED'='PENDING',available='100',due=true,complete=true,receipt:any=null,reversal=true,seedPatch?:(root:RentalEarning)=>RentalEarning){const seen:{sql:string;args:any[]}[]=[],root:RentalEarning={id:'earning',economicKey:canonicalize(['NATIVE_RENTAL_REFERRAL','NATIVE','zzsh','rental_order','order','beneficiary','RENTER_REFERRAL']),source:{kind:'NATIVE_RENTAL_REFERRAL',type:'NATIVE',system:'zzsh',entity:'rental_order',id:'order',digest:h,eventAt:'2026-10-04T00:00:00.000123Z'},beneficiaryUserId:'beneficiary',role:'RENTER_REFERRAL',policyVersion:'policy',policyDigest:h,baseDigest:h,relationDigest:h,amountCents:'100',dueAt:'2026-10-04T00:00:00.000123Z',fingerprint:h,state:'PENDING',fundsDisposition:'PENDING',recoveryRequiredCents:null,version:'1'},canonical=canonicalize(seedPatch?seedPatch(structuredClone(root)):root),row={id:root.id,economic_root_id:root.id,economic_key:root.economicKey,beneficiary_role:root.role,posting_digest:h,order_id:'order',beneficiary_user_id:root.beneficiaryUserId,amount_cents:'100',due_exact:root.dueAt,canonical_seed:canonical,seed_digest:sha(canonical),basis_digest:h,payment_confirmation_id:'payment',state,funds_disposition:state==='PENDING'?'PENDING':state==='REVOKED'?'REVOKED':'SETTLED',version:state==='PENDING'?'1':state==='SETTLED'?'2':state==='RECOVERY_REQUIRED'?'3':'4',recovery_required_cents:state==='RECOVERY_REQUIRED'?'100':null},source='original_reversal';
 const pool={connect:async()=>({release(){},query:async(sql:string,args:any[]=[])=>{seen.push({sql,args});if(sql.startsWith('SELECT d.oid'))return{rows:[{oid:12345,name:'zzsh_test_order_existing_order',role:'zzsh_order_existing_order_r',marker:'zzsh:order-reservation-test:v1',complete}]};if(sql.startsWith('SELECT order_id'))return{rows:[{order_id:'order',beneficiary_user_id:'beneficiary'}]};if(sql.startsWith('SELECT e.*'))return{rows:[row]};if(sql.startsWith('SELECT * FROM zzsh_order.rental_referral_transition'))return{rows:receipt?[receipt]:[]};if(sql.startsWith('SELECT * FROM zzsh_order.rental_referral_reversal_source'))return{rows:reversal?[{id:source,scope:'LOCAL_CONTROLLED',basis_digest:h,amount_cents:'100',canonical_source:canonicalize({schema:'rental-referral-reversal.v1',scope:'LOCAL_CONTROLLED',earningId:'earning',basisDigest:h,amountCents:'100'}),source_digest:sha(canonicalize({schema:'rental-referral-reversal.v1',scope:'LOCAL_CONTROLLED',earningId:'earning',basisDigest:h,amountCents:'100'})),approval_digest:h}]:[]};if(sql.startsWith('SELECT reversal_source_id'))return{rows:[{reversal_source_id:'original_reversal',finance_event_id:null}]};if(sql.startsWith('SELECT date_trunc'))return{rows:[{now:new Date('2026-10-04T00:00:01.000Z'),due}]};if(sql.startsWith('SELECT 1 FROM zzsh_order.wallet_coverage'))return{rows:[{}],rowCount:1};if(sql.startsWith('SELECT ledger_revision'))return{rows:[{revision:'5',available}]};if(sql.startsWith('UPDATE zzsh_order.rental_referral_earning'))return{rows:[],rowCount:1};return{rows:[]};}})} as unknown as Pool;return{pool,seen};}
test('missing earning schema rejects before any financial write; no default wallet is invented',async()=>{const p=probe('PENDING','100',true,false);await assert.rejects(createDistributionEarningStore(scope).transition(p.pool,'earning','SETTLE','1','request'),e=>(e as {status?:number}).status===503);assert(!p.seen.some(q=>/^INSERT|^UPDATE|^DELETE/.test(q.sql)));});
test('microsecond due predicate is authoritative and version mismatch cannot post money',async()=>{const p=probe('PENDING','100',false);await assert.rejects(createDistributionEarningStore(scope).transition(p.pool,'earning','SETTLE','1','request'),e=>(e as {status?:number}).status===409);assert(!p.seen.some(q=>/^INSERT|^UPDATE|^DELETE/.test(q.sql)));const stale=probe();await assert.rejects(createDistributionEarningStore(scope).transition(stale.pool,'earning','SETTLE','2','request'));assert(!stale.seen.some(q=>/^INSERT|^UPDATE|^DELETE/.test(q.sql)));});
test('pending revoke reverses pending expense, never touches available or refund bucket',async()=>{const p=probe(),result=await createDistributionEarningStore(scope).transition(p.pool,'earning','REVOKE','1','request','original_reversal');assert.equal(result.root.state,'REVOKED');const lines=p.seen.filter(q=>q.sql.startsWith('INSERT INTO zzsh_order.settlement_ledger_entry'));assert.deepEqual(lines.map(q=>q.args[3]),['WALLET_PENDING_EARNINGS','DISTRIBUTION_EXPENSE']);assert(!lines.some(q=>q.args[3]==='WALLET_AVAILABLE'||q.args[3]==='REFUND_PAYABLE'));});
test('settled revoke with insufficient available preserves settled funds and records recovery with zero ledger writes',async()=>{const p=probe('SETTLED','99'),result=await createDistributionEarningStore(scope).transition(p.pool,'earning','REVOKE','2','request','original_reversal');assert.equal(result.root.state,'RECOVERY_REQUIRED');assert.equal(result.root.fundsDisposition,'SETTLED');assert.equal(result.root.recoveryRequiredCents,'100');assert(!p.seen.some(q=>q.sql.includes('INSERT INTO zzsh_order.finance_event')||q.sql.includes('INSERT INTO zzsh_order.settlement_ledger_entry')));assert(p.seen.some(q=>q.sql.startsWith('INSERT INTO zzsh_order.rental_referral_transition')&&q.args[5]===null));});
test('same reversal receipt does not post again and changing source under that action rejects',async()=>{const p=probe('RECOVERY_REQUIRED','100',true,true,{earning_id:'earning',action:'REVOKE',expected_version:'2',result_version:'3',finance_event_id:null,source_digest:h,reversal_source_id:'original_reversal'});assert.equal((await createDistributionEarningStore(scope).transition(p.pool,'earning','REVOKE','2','request','original_reversal')).replayed,true);await assert.rejects(createDistributionEarningStore(scope).transition(p.pool,'earning','REVOKE','2','request','different'),e=>(e as {status?:number}).status===409);assert(!p.seen.some(q=>/^INSERT|^UPDATE|^DELETE/.test(q.sql)));});
test('missing original reversal source is unavailable rather than a successful correction',async()=>{const p=probe('SETTLED','100',true,true,null,false);await assert.rejects(createDistributionEarningStore(scope).transition(p.pool,'earning','REVOKE','2','request','original_reversal'),e=>(e as {status?:number}).status===503);assert(!p.seen.some(q=>/^INSERT|^UPDATE|^DELETE/.test(q.sql)));});
test('outstanding recovery cannot debit until the same locked available wallet can repay the whole original amount',async()=>{const p=probe('RECOVERY_REQUIRED','99');await assert.rejects(createDistributionEarningStore(scope).transition(p.pool,'earning','RECOVER','3','request','original_reversal'),e=>(e as {status?:number}).status===409);assert(!p.seen.some(q=>/^INSERT|^UPDATE|^DELETE/.test(q.sql)));});
test('funded recovery closes the original debt with one available debit and expense reversal, preserving original source',async()=>{const p=probe('RECOVERY_REQUIRED','150'),r=await createDistributionEarningStore(scope).transition(p.pool,'earning','RECOVER','3','request','original_reversal');assert.equal(r.root.state,'REVOKED');assert.equal(r.root.fundsDisposition,'REVOKED');assert.equal(r.root.recoveryRequiredCents,null);assert.equal(r.root.version,'4');const lines=p.seen.filter(q=>q.sql.startsWith('INSERT INTO zzsh_order.settlement_ledger_entry'));assert.deepEqual(lines.map(q=>[q.args[3],q.args[4],q.args[5]]),[['WALLET_AVAILABLE','100','0'],['DISTRIBUTION_EXPENSE','0','100']]);assert(p.seen.some(q=>q.sql.startsWith('INSERT INTO zzsh_order.rental_referral_transition')&&q.args[2]==='RECOVER'&&q.args[6]==='original_reversal'));});
test('same completed recovery receipt never posts again and a changed reversal source rejects',async()=>{const p=probe('REVOKED','50',true,true,{earning_id:'earning',action:'RECOVER',expected_version:'3',result_version:'4',finance_event_id:'recovered_event',source_digest:h,reversal_source_id:'original_reversal'});assert.equal((await createDistributionEarningStore(scope).transition(p.pool,'earning','RECOVER','3','request','original_reversal')).replayed,true);await assert.rejects(createDistributionEarningStore(scope).transition(p.pool,'earning','RECOVER','3','request','changed'),e=>(e as {status?:number}).status===409);assert(!p.seen.some(q=>/^INSERT|^UPDATE|^DELETE/.test(q.sql)));});
test('settled earning without a declared outstanding debt cannot use the recovery action',async()=>{const p=probe('SETTLED','150');await assert.rejects(createDistributionEarningStore(scope).transition(p.pool,'earning','RECOVER','2','request','original_reversal'),e=>(e as {status?:number}).status===409);assert(!p.seen.some(q=>/^INSERT|^UPDATE|^DELETE/.test(q.sql)));});
test('later recovery cannot overwrite the original outstanding reversal receipt',async()=>{const p=probe('REVOKED','50',true,true,{earning_id:'earning',action:'REVOKE',expected_version:'2',result_version:'3',finance_event_id:null,source_digest:h,reversal_source_id:'original_reversal'}),r=await createDistributionEarningStore(scope).transition(p.pool,'earning','REVOKE','2','request','original_reversal');assert.equal(r.root.state,'REVOKED');assert.equal(r.root.version,'4');assert.equal(r.originalResult?.state,'RECOVERY_REQUIRED');assert.equal(r.originalResult?.fundsDisposition,'SETTLED');assert.equal(r.originalResult?.recoveryRequiredCents,'100');assert.equal(r.originalResult?.version,'3');assert(!p.seen.some(q=>/^(INSERT|UPDATE|DELETE)/.test(q.sql)));});
test('original settlement remains settled at its original version after a later revoke',async()=>{const p=probe('REVOKED','50',true,true,{earning_id:'earning',action:'SETTLE',expected_version:'1',result_version:'2',finance_event_id:'settled_event',source_digest:h,reversal_source_id:null}),r=await createDistributionEarningStore(scope).transition(p.pool,'earning','SETTLE','1','request');assert.equal(r.originalResult?.state,'SETTLED');assert.equal(r.originalResult?.version,'2');assert.equal(r.root.state,'REVOKED');assert(!p.seen.some(q=>/^(INSERT|UPDATE|DELETE)/.test(q.sql)));});
test('receipt ownership, version arithmetic and missing settlement event reject without financial writes',async()=>{const receipt={earning_id:'earning',action:'SETTLE',expected_version:'1',result_version:'2',finance_event_id:'settled_event',source_digest:h,reversal_source_id:null};for(const patch of [{earning_id:'foreign'},{result_version:'5'},{result_version:'3'},{finance_event_id:null}]){const p=probe('REVOKED','50',true,true,{...receipt,...patch});await assert.rejects(createDistributionEarningStore(scope).transition(p.pool,'earning','SETTLE','1','request'),e=>(e as {status?:number}).status===409);assert(!p.seen.some(q=>/^(INSERT|UPDATE|DELETE)/.test(q.sql)));}});
test('a terminal state with no original receipt never reports a successful replay',async()=>{const p=probe('SETTLED','100',true,true,null);await assert.rejects(createDistributionEarningStore(scope).transition(p.pool,'earning','SETTLE','2','request'),e=>(e as {status?:number}).status===503);assert(!p.seen.some(q=>/^(INSERT|UPDATE|DELETE)/.test(q.sql)));});
test('a recomputed hash cannot bless a changed economic key, role, source or original state',async()=>{const mutations:((r:RentalEarning)=>RentalEarning)[]=[r=>({...r,economicKey:'other'}),r=>({...r,role:'OWNER_REFERRAL'}),r=>({...r,source:{...r.source,digest:'b'.repeat(64)}}),r=>({...r,source:{...r.source,type:'LEGACY_MYSQL'}}),r=>({...r,version:'2'}),r=>({...r,state:'SETTLED',fundsDisposition:'SETTLED'})];for(const patch of mutations){const p=probe('PENDING','100',true,true,null,true,patch);await assert.rejects(createDistributionEarningStore(scope).transition(p.pool,'earning','SETTLE','1','request'),e=>(e as {status?:number}).status===409);assert(!p.seen.some(q=>/^(INSERT|UPDATE|DELETE)/.test(q.sql)));}});
