import {test} from 'node:test';import {strict as assert} from 'node:assert';import {createHash} from 'node:crypto';
import {prepareLegacyInvitationImport,importReviewedLegacyInvitations,recoverReviewedLegacyInvitations,type LegacyInvitationInput} from '../src/finance/legacy-invitation-maintenance';import {canonicalize} from '../src/supply/content-hash';import {legacyOwnerUserId} from '../src/supply/legacy-user-migration';import type {PoolClient} from 'pg';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
function source():LegacyInvitationInput{const subject=(id:string,parent:string)=>({legacyId:id,userId:legacyOwnerUserId('legacy_mysql_restore','la_user',id),identitySourceDigest:'a'.repeat(64),userSource:{id,code:'fx'+id,is_delete:0,inviter_id:parent,first_leader:parent},qualificationSource:{id:'d'+id,user_id:id,level_id:'1',is_distribution:1,is_delete:0,is_freeze:0},childCounts:{INVITER:{all:id==='1'?7:0,inPlan:id==='1'?1:0},DISTRIBUTION_LEADER:{all:id==='1'?8:0,inPlan:id==='1'?1:0}}});const subjects=[subject('1','0'),subject('2','1')];for(const s of subjects)s.qualificationSource.id=s.legacyId;return{schema:'legacy-invitations.v1',sourceSystem:'legacy_mysql_restore',policyVersionId:'policy1',policyConfigDigest:'b'.repeat(64),subjects,gradeMapping:[{legacyGradeId:'1',levelCode:'LEGACY_L1'}],sourceCodeMultiplicity:subjects.map(s=>({matchCode:String(s.userSource.code).toUpperCase(),count:1}))};}
function prepare(input=source()){return prepareLegacyInvitationImport(input,hash(canonicalize(input)));}
test('original inviter and leader persist independently and incomplete source child totals remain UNKNOWN',()=>{const p=prepare();assert.equal(p.relations.length,2);const first=p.subjects.find(s=>s.legacyId==='1')!,second=p.subjects.find(s=>s.legacyId==='2')!;assert.equal(first.inviteesKnowledge,'UNKNOWN');assert.equal(first.inviterKnowledge,'KNOWN_NONE');assert.equal(second.inviterKnowledge,'KNOWN_PARENT');assert.equal(second.leaderKnowledge,'KNOWN_PARENT');assert.equal(second.inviteesKnowledge,'KNOWN');assert.equal(second.userSource.code,'fx2');});
test('a missing nonzero original parent never becomes known-none or a default parent',()=>{const x=source();x.subjects[1]!.userSource.inviter_id='3';assert.throws(()=>prepare(x));});
test('source identity override, global code collision and reviewed body drift reject before database work',()=>{const x=source();x.subjects[1]!.userId='other';assert.throws(()=>prepare(x));const duplicate=source();duplicate.sourceCodeMultiplicity[0]!.count=2;assert.throws(()=>prepare(duplicate));assert.throws(()=>prepareLegacyInvitationImport(source(),'0'.repeat(64)));});
test('child source closure and source qualification freeze cannot be inferred from VIP or missing fields',()=>{const x=source();x.subjects[0]!.childCounts.INVITER.inPlan=0;assert.throws(()=>prepare(x));const missing=source();delete missing.subjects[0]!.qualificationSource.is_freeze;assert.throws(()=>prepare(missing));const frozen=source();frozen.subjects[0]!.qualificationSource.is_freeze=1;assert.equal(prepare(frozen).subjects.find(s=>s.legacyId==='1')!.commissionFrozen,true);});
test('cyclic legacy graph or unmapped old grade is rejected rather than rewritten',()=>{const cycle=source();cycle.subjects[0]!.userSource.first_leader='2';assert.throws(()=>prepare(cycle));const grade=source();grade.subjects[0]!.qualificationSource.level_id='9';assert.throws(()=>prepare(grade));});
test('runtime, wrong database and uninstalled schema cannot invoke maintenance import or recovery',async()=>{for(const row of [{oid:833000,name:'zzsh_test_m2_auth_auth_compat_ui',role:'zzsh_m2_auth_compat_ui_r',marker:'zzsh:m2-auth-test:v1',complete:true},{oid:820148,name:'zzsh_test_m2_auth_auth_compat',role:'zzsh_m2_auth_compat_m',marker:'zzsh:m2-auth-test:v1',complete:true},{oid:833000,name:'zzsh_test_m2_auth_auth_compat_ui',role:'zzsh_m2_auth_compat_ui_m',marker:'zzsh:m2-auth-test:v1',complete:false}]){const seen:string[]=[],c={query:async(sql:string)=>{seen.push(sql);return{rows:[row]};}} as PoolClient,input=source(),digest=hash(canonicalize(input)),actor={userId:'actor',sessionId:'sdk',requestId:'request'};await assert.rejects(importReviewedLegacyInvitations(c,actor,input,digest));await assert.rejects(recoverReviewedLegacyInvitations(c,actor,input,digest));assert.equal(seen.length,2);assert(seen.every(q=>q.startsWith('SELECT d.oid')));}});
test('autocommit callers cannot leave a partially imported legacy source batch',async()=>{const seen:string[]=[],c={query:async(sql:string)=>{seen.push(sql);return{rows:sql.startsWith('SELECT d.oid')?[{oid:833000,name:'zzsh_test_m2_auth_auth_compat_ui',role:'zzsh_m2_auth_compat_ui_m',marker:'zzsh:m2-auth-test:v1',complete:true}]:sql.startsWith('SELECT s.id')?[{id:'sdk'}]:[{xid:null}]};}} as PoolClient,input=source();await assert.rejects(importReviewedLegacyInvitations(c,{userId:'actor',sessionId:'sdk',requestId:'request'},input,hash(canonicalize(input))),e=>(e as {status?:number}).status===409);assert.equal(seen.length,3);assert(seen.every(q=>q.startsWith('SELECT')));});
