import {test} from 'node:test';import {strict as assert} from 'node:assert';import type {AppConfig} from '../src/config/config';import type {PoolClient} from 'pg';
import {createNativeWithdrawalScope,assertNativeWithdrawalResource,nativeWithdrawalBindings,assertNativeWithdrawalDestination,assertNativeWithdrawalIntent,type NativeWithdrawalScope} from '../src/finance/native-withdrawal-resource';
function options(){return{config:{profile:'test',provider:'fake',testOperationsEnabled:true,database:{target:'local-compose',host:'127.0.0.1',port:55432,name:'zzsh_test_order_personal_finance',user:'zzsh_order_personal_finance_r'}} as AppConfig,resourceSet:'personal_finance',resourceOid:869754,bindings:[{userId:'user',admissionId:'admission-a',destinationId:'destination-a',intentId:'intent-a',payoutKey:'payout-a'},{userId:'user',admissionId:'admission-b',destinationId:'destination-b',intentId:'intent-b',payoutKey:'payout-b'}]};}
const live={oid:869754,name:'zzsh_test_order_personal_finance',role:'zzsh_order_personal_finance_r',marker:'zzsh:order-reservation-test:v1',rolsuper:false,rolbypassrls:false,complete:true};
const client=(row:unknown)=>({query:async()=>({rows:row?[row]:[]})}) as unknown as PoolClient;
test('token is frozen and copied fields cannot be forged as a capability',()=>{const scope=createNativeWithdrawalScope(options());assert(Object.isFrozen(scope));assert.throws(()=>nativeWithdrawalBindings({...scope},'user'),/not verified/);assert.throws(()=>nativeWithdrawalBindings({kind:'NATIVE_LOCAL_CONTROLLED_WITHDRAWAL'} as NativeWithdrawalScope,'user'),/not verified/);});
test('caller and returned-view mutations cannot expand or replace allowed bindings',async()=>{const input=options(),scope=createNativeWithdrawalScope(input);input.bindings[0]!.userId='other';input.bindings.push({userId:'other',admissionId:'x',destinationId:'x',intentId:'x',payoutKey:'x'});input.config.database.name='wrong';const exposed=nativeWithdrawalBindings(scope,'user') as unknown as Array<{userId:string}>;exposed[0]!.userId='other';assert.equal(nativeWithdrawalBindings(scope,'user').length,2);assert.throws(()=>nativeWithdrawalBindings(scope,'other'));await assertNativeWithdrawalResource(client(live),scope);});
test('wrong config profile, provider, test flag, host, port, database or runtime role cannot construct a scope',()=>{for(const mutate of [(o:ReturnType<typeof options>)=>o.config.profile='provider-test',(o:ReturnType<typeof options>)=>o.config.provider='real',(o:ReturnType<typeof options>)=>o.config.testOperationsEnabled=false,(o:ReturnType<typeof options>)=>o.config.database.host='remote',(o:ReturnType<typeof options>)=>o.config.database.port=5432,(o:ReturnType<typeof options>)=>o.config.database.name='other',(o:ReturnType<typeof options>)=>o.config.database.user='zzsh_order_personal_finance_m']){const o=options();mutate(o);assert.throws(()=>createNativeWithdrawalScope(o));}});
test('ambiguous intent, payout or destination tuples are rejected',()=>{for(const field of ['intentId','payoutKey'] as const){const o=options();o.bindings[1]![field]=o.bindings[0]![field];assert.throws(()=>createNativeWithdrawalScope(o),/ambiguous/);}const o=options();o.bindings[1]!.admissionId='admission-a';o.bindings[1]!.destinationId='destination-a';assert.throws(()=>createNativeWithdrawalScope(o),/ambiguous/);});
test('every live connection must match exact resource, marker and non-super runtime role',async()=>{const scope=createNativeWithdrawalScope(options());await assertNativeWithdrawalResource(client(live),scope);for(const changed of [{oid:833000},{name:'other'},{role:'zzsh_order_personal_finance_m'},{marker:'zzsh:m2-auth-test:v1'},{rolsuper:true},{rolbypassrls:true}])await assert.rejects(assertNativeWithdrawalResource(client({...live,...changed}),scope),/NATIVE_WITHDRAWAL_RESOURCE_NOT_ADMITTED/);await assert.rejects(assertNativeWithdrawalResource(client(null),scope));await assert.rejects(assertNativeWithdrawalResource(client({...live,complete:false}),scope),/SCHEMA_UNAVAILABLE/);});
test('destination and full intent binding cannot be mixed across approved tuples',()=>{const scope=createNativeWithdrawalScope(options());assertNativeWithdrawalDestination(scope,{userId:'user',admissionId:'admission-a',destinationId:'destination-a'});assert.throws(()=>assertNativeWithdrawalDestination(scope,{userId:'user',admissionId:'admission-a',destinationId:'destination-b'}));const row={id:'intent-a',user_id:'user',admission_id:'admission-a',destination_id:'destination-a',payout_key:'payout-a'};assertNativeWithdrawalIntent(scope,row);for(const changed of [{id:'other-intent'},{user_id:'other'},{admission_id:'admission-b'},{destination_id:'destination-b'},{payout_key:'payout-b'}])assert.throws(()=>assertNativeWithdrawalIntent(scope,{...row,...changed}));});
test('forged scope is rejected before any database query',async()=>{let queries=0;const c={query:async()=>{queries++;return{rows:[live]};}} as unknown as PoolClient;await assert.rejects(assertNativeWithdrawalResource(c,{kind:'NATIVE_LOCAL_CONTROLLED_WITHDRAWAL'}),/not verified/);assert.equal(queries,0);});
