import {test} from 'node:test';import {strict as assert} from 'node:assert';import {readFileSync} from 'node:fs';import {join} from 'node:path';import type {AppConfig} from '../src/config/config';import {createNativeWithdrawalScope} from '../src/finance/native-withdrawal-resource';
const token=()=>createNativeWithdrawalScope({config:{profile:'test',provider:'fake',testOperationsEnabled:true,database:{target:'local-compose',host:'127.0.0.1',port:55432,name:'zzsh_test_order_personal_finance',user:'zzsh_order_personal_finance_r'}} as AppConfig,resourceSet:'personal_finance',resourceOid:869754,bindings:[{userId:'user',admissionId:'a',destinationId:'d',intentId:'i',payoutKey:'p'}]});
const response=()=>({headersSent:false,statusCode:0,payload:null as any,status(n:number){this.statusCode=n;return this;},setHeader(){return this;},json(value:any){this.payload=value;this.headersSent=true;return this;}});
test('actual withdrawal middleware forwards only the explicit server scope on every route',async t=>{
 const user=require('../src/auth/user-identity'),store=require('../src/finance/controlled-withdrawal-store'),oldUser=user.readUserContext,names=['readControlledWithdrawals','readControlledWithdrawalQuote','recoverControlledWithdrawal','createControlledWithdrawal'],old=Object.fromEntries(names.map(n=>[n,store[n]])),seen:any[]=[];t.after(()=>{user.readUserContext=oldUser;Object.assign(store,old);});user.readUserContext=async()=>({userId:'user',sessionId:'session'});for(const name of names)store[name]=async(...args:any[])=>{seen.push({name,args});return name==='createControlledWithdrawal'?{status:200,body:{}}:{};};
 const {mountControlledWithdrawalRoutes}=require('../src/finance/controlled-withdrawal-routes');let handler:any;const app={getHttpAdapter:()=>({getInstance:()=>({use:(path:string,h:any)=>{handler=h;}})})},scope=token();mountControlledWithdrawalRoutes(app,{pool:{},apiOrigin:'http://api',userOrigin:'http://user',nativeWithdrawalScope:scope});
 for(const [method,suffix]of [['GET','/'],['GET','/i'],['GET','/receipt?key=key'],['POST','/quote'],['POST','/']]){const r=response();await handler({method,originalUrl:'/api/v1/users/me/withdrawals'+suffix,headers:{origin:'http://user','idempotency-key':'key','x-request-id':'req_test'},body:{amountCents:'200',destinationId:'d',policyVersion:'policy',expectedWalletVersion:'1'}},r);assert.equal(r.statusCode,200);assert.equal(seen.at(-1).args.at(-1),scope);}
 const count=seen.length,r=response();await handler({method:'POST',originalUrl:'/api/v1/users/me/withdrawals/quote',headers:{origin:'http://user','x-request-id':'req_bad'},body:{nativeWithdrawalScope:scope}},r);assert.equal(r.statusCode,400);assert.equal(seen.length,count);
});
test('membership→personal finance→withdrawal carries the same token without a parallel mount',()=>{
 const finance=require('../src/finance/personal-finance-routes'),withdrawal=require('../src/finance/controlled-withdrawal-routes'),oldFinance=finance.mountPersonalFinanceRead,oldWithdrawal=withdrawal.mountControlledWithdrawalRoutes,scope=token(),options={nativeWithdrawalScope:scope},seen:any[]=[];const app={getHttpAdapter:()=>({getInstance:()=>({use(){}})})};
 try{finance.mountPersonalFinanceRead=(a:any,o:any)=>seen.push(o.nativeWithdrawalScope);require('../src/auth/rental-membership-routes').mountRentalMembership(app,options);finance.mountPersonalFinanceRead=oldFinance;withdrawal.mountControlledWithdrawalRoutes=(a:any,o:any)=>seen.push(o.nativeWithdrawalScope);oldFinance(app,options);assert.deepEqual(seen,[scope,scope]);}finally{finance.mountPersonalFinanceRead=oldFinance;withdrawal.mountControlledWithdrawalRoutes=oldWithdrawal;}
});
test('wallet middleware passes the token while the legacy no-scope middleware passes undefined',async t=>{
 const read=require('../src/finance/personal-finance-read'),auth=require('../src/auth/user-identity'),order=require('../src/order/order'),oldRead=read.readPersonalWallet,oldUser=auth.readUserContext,oldAuth=order.assertReplayAuthorization;const received:any[]=[];t.after(()=>{read.readPersonalWallet=oldRead;auth.readUserContext=oldUser;order.assertReplayAuthorization=oldAuth;});read.readPersonalWallet=async(...args:any[])=>{received.push(args[2]);return{}};auth.readUserContext=async()=>({userId:'user',sessionId:'session'});order.assertReplayAuthorization=async()=>{};
 for(const scope of [token(),undefined]){let wallet:any;const app={getHttpAdapter:()=>({getInstance:()=>({use:(path:string,h:any)=>{if(path.endsWith('/wallet'))wallet=h;}})})},pool={connect:async()=>({query:async()=>({rows:[]}),release(){}})};require('../src/finance/personal-finance-routes').mountPersonalFinanceRead(app,{pool,apiOrigin:'http://api',userOrigin:'http://user',nativeWithdrawalScope:scope});const r=response();await wallet({method:'GET',originalUrl:'/api/v1/users/me/wallet',headers:{origin:'http://user','x-request-id':'req_wallet'}},r);assert.equal(r.statusCode,200);assert.equal(received.at(-1),scope);}
});
test('compiled auth assembly explicitly forwards the option without an environment constructor',()=>{const source=readFileSync(join(__dirname,'../src/auth/auth-runtime.js'),'utf8');assert.match(source,/mountRentalMembership\)\(app,\s*\{[^}]*nativeWithdrawalScope:\s*options\.nativeWithdrawalScope/);assert(!source.includes('NATIVE_WITHDRAWAL_SCOPE'));});


