import {test} from 'node:test';import {strict as assert} from 'node:assert';import type {Pool,PoolClient} from 'pg';import type {AppConfig} from '../src/config/config';
import {createNativeWithdrawalScope} from '../src/finance/native-withdrawal-resource';import {readControlledWithdrawalQuote,createControlledWithdrawal,recoverControlledWithdrawal,readControlledWithdrawals} from '../src/finance/controlled-withdrawal-store';import {readNativeReservationStatus} from '../src/finance/native-wallet-projection';import {fingerprintRequest} from '../src/supply/supply-util';
const resource={oid:869754,name:'zzsh_test_order_personal_finance',role:'zzsh_order_personal_finance_r',marker:'zzsh:order-reservation-test:v1',rolsuper:false,rolbypassrls:false,complete:true};
const config={profile:'test',provider:'fake',testOperationsEnabled:true,database:{target:'local-compose',host:'127.0.0.1',port:55432,name:resource.name,user:resource.role}} as AppConfig;
const binding={userId:'user',admissionId:'admission',destinationId:'destination',intentId:'intent',payoutKey:'payout'},scope=()=>createNativeWithdrawalScope({config,resourceSet:'personal_finance',resourceOid:869754,bindings:[binding]}),actor={userId:'user',sessionId:'session',requestId:'request'},body={amountCents:'200',destinationId:'destination',policyVersion:'policy',expectedWalletVersion:'9'};
function probe({debt=true,missing=false,replay=false,foreign=false}={}){
 const sqls:string[]=[],receipt={intent:{id:'intent',userId:'user',destinationId:'destination',state:'RESERVED'}},intent={id:'intent',user_id:'user',admission_id:'admission',destination_id:foreign?'other':'destination',payout_key:'payout',mode:'LOCAL_CONTROLLED',policy_version:'policy',expected_ledger_revision:'9',accepted_at:new Date(),gross_cents:'200',net_cents:'100',fee_cents:'100',state:'RESERVED',operation_version:'1',funds_disposition:'RESERVED',terminal:null,conflict_digest:null,lease_token_hash:null};
 const client={release(){},query:async(sql:string,args:unknown[]=[])=>{sqls.push(sql);if(sql.includes('FROM pg_database d JOIN pg_roles'))return{rows:[resource]};if(sql.startsWith('SELECT "suspended"'))return{rows:[{suspended:false}],rowCount:1};if(sql.includes('FROM "zzsh_iam"."user_identity_state"'))return{rows:[{accountStatus:'ACTIVE'}],rowCount:1};if(sql.includes('FROM "zzsh_auth_user"."session"'))return{rows:[{}],rowCount:1};if(sql.includes("to_regclass('zzsh_order.rental_referral_earning')"))return{rows:[{installed:!missing}]};if(sql.includes('recovery_required_cents'))return{rows:[{count:debt?'1':'0',amount:debt?'312':'0',invalid:0}]};if(sql.includes('FROM "zzsh_supply"."idempotency_record"'))return{rows:replay?[{requestFingerprint:fingerprintRequest('controlled.withdrawal.reserve',undefined,body),responseStatus:200,responseBody:receipt,publishRequired:false}]:[]};if(sql.startsWith('SELECT response_body AS body'))return{rows:replay?[{body:receipt}]:[]};if(sql.startsWith('SELECT id,user_id,admission_id')||sql.startsWith('SELECT * FROM zzsh_order.withdrawal_intent WHERE id='))return{rows:[intent]};if(['BEGIN','COMMIT','ROLLBACK'].includes(sql)||sql.startsWith('SELECT pg_advisory_xact_lock'))return{rows:[]};throw Error('unexpected native probe SQL: '+sql);}};
 return{pool:{connect:async()=>client} as unknown as Pool,client:client as unknown as PoolClient,sqls,receipt,intent};
}
test('new native quote checks debt after existing exclusive user lock, before wallet shared read',async()=>{const p=probe();await assert.rejects(readControlledWithdrawalQuote(p.pool,actor,body,scope()),e=>(e as any).status===409);const user=p.sqls.findIndex(s=>s.includes('FOR UPDATE')&&s.includes('"user"')),debt=p.sqls.findIndex(s=>s.includes('recovery_required_cents'));assert(user>=0&&debt>user);assert(!p.sqls.some(s=>s.includes('FOR SHARE')));assert(!p.sqls.some(s=>/^(INSERT|UPDATE|DELETE)/.test(s)));assert(p.sqls.includes('ROLLBACK'));});
test('missing debt schema blocks new quote with 503 instead of zero debt',async()=>{const p=probe({missing:true});await assert.rejects(readControlledWithdrawalQuote(p.pool,actor,body,scope()),e=>(e as any).status===503);assert(!p.sqls.some(s=>s.includes('recovery_required_cents')));});
test('fresh reservation is blocked by debt inside its new idempotent execution',async()=>{const p=probe();await assert.rejects(createControlledWithdrawal(p.pool,actor,body,'key',scope()),e=>(e as any).status===409);assert(p.sqls.some(s=>s.includes('FROM "zzsh_supply"."idempotency_record"')));assert(!p.sqls.some(s=>s.startsWith('INSERT')));});
test('accepted reservation replay remains available while debt exists',async()=>{const p=probe({replay:true}),r=await createControlledWithdrawal(p.pool,actor,body,'key',scope());assert.equal(r.replayed,true);assert.deepEqual(r.body,p.receipt);assert(!p.sqls.some(s=>s.includes('rental_referral_earning')));assert(!p.sqls.some(s=>s.startsWith('INSERT')));});
test('original receipt and original intent reads do not invoke the debt gate',async()=>{const p=probe({replay:true}),s=scope();assert.equal((await recoverControlledWithdrawal(p.pool,actor,'key',s)).knowledge,'KNOWN');const r=await readControlledWithdrawals(p.pool,actor,'intent',s);assert.equal((r as any).intent.id,'intent');assert(!p.sqls.some(sql=>sql.includes('rental_referral_earning')));});
test('receipt with an out-of-scope original destination cannot escape through replay',async()=>{const p=probe({replay:true,foreign:true});await assert.rejects(createControlledWithdrawal(p.pool,actor,body,'key',scope()),/INTENT_NOT_ADMITTED/);await assert.rejects(recoverControlledWithdrawal(p.pool,actor,'key',scope()),/INTENT_NOT_ADMITTED/);});
test('projection separates current balance, finite debt knowledge, scope and the need for a new quote',async()=>{const blocked=await readNativeReservationStatus(probe().client,'user',scope());assert.equal(blocked.reservationState,'BLOCKED_BY_RECOVERY');assert.equal(blocked.recovery.outstandingCents,'312');assert.equal(blocked.globalWithdrawable,'UNKNOWN');const unknown=await readNativeReservationStatus(probe({missing:true}).client,'user',scope());assert.equal(unknown.reservationState,'UNKNOWN');assert.equal(unknown.recovery.outstandingCents,null);const clear=await readNativeReservationStatus(probe({debt:false}).client,'user',scope());assert.equal(clear.reservationState,'REQUIRES_CURRENT_QUOTE');assert.equal(clear.scope,'NATIVE_REFERRAL_OBLIGATIONS_ONLY');const other=await readNativeReservationStatus(probe({debt:false}).client,'other',scope());assert.equal(other.reservationState,'NOT_IN_SCOPE');assert.equal(other.subjectInScope,false);});


