import {test} from 'node:test';import {strict as assert} from 'node:assert';import {createHash} from 'node:crypto';import type {Pool} from 'pg';import type {AppConfig} from '../src/config/config';import {canonicalize} from '../src/supply/content-hash';import {createNativeWithdrawalScope} from '../src/finance/native-withdrawal-resource';import {localWithdrawalRequestKey} from '../src/finance/controlled-withdrawal';import {readControlledWithdrawalQuote,createControlledWithdrawal} from '../src/finance/controlled-withdrawal-store';
function fixture(){
 const hash=(s:string)=>createHash('sha256').update(s).digest('hex'),key=localWithdrawalRequestKey('admission','1','destination','1'),id='wd_'+hash(canonicalize(['user',key])).slice(0,40),payoutKey='controlled-withdrawal-'+hash(id),now=new Date('2026-10-05T01:00:00.000Z');
 const resource={oid:869754,name:'zzsh_test_order_personal_finance',role:'zzsh_order_personal_finance_r',marker:'zzsh:order-reservation-test:v1',rolsuper:false,rolbypassrls:false,complete:true},config={profile:'test',provider:'fake',testOperationsEnabled:true,database:{target:'local-compose',host:'127.0.0.1',port:55432,name:resource.name,user:resource.role}} as AppConfig,scope=createNativeWithdrawalScope({config,resourceSet:'personal_finance',resourceOid:869754,bindings:[{userId:'user',admissionId:'admission',destinationId:'destination',intentId:id,payoutKey}]}),actor={userId:'user',sessionId:'session',requestId:'request'},body={amountCents:'200',destinationId:'destination',policyVersion:'OWNER_LOCAL_RESTORED_20261003_v1_BANK_CARD',expectedWalletVersion:'9'};
 const destination:any={id:'destination',user_id:'user',admission_id:'admission',revision:'1',cohort_revision:'1',per_intent_cents:'200',max_intents:1,max_gross_cents:'200',admitted_at:new Date('2026-10-05T00:00:00Z'),expires_at:new Date('2026-10-05T02:00:00Z'),resource_oid:869754,resource_name:resource.name,resource_marker:resource.marker,cohort_active:true,active:true,mode:'LOCAL_CONTROLLED',kind:'BANK_CARD',display_mask:'LOCAL_TEST_ONLY'},sqls:string[]=[],ledger:any[][]=[];let row:any=null;
 const pool={connect:async()=>({release(){},query:async(sql:string,args:any[]=[])=>{sqls.push(sql);
  if(sql.includes('FROM pg_database d JOIN pg_roles'))return{rows:[resource]};if(sql.startsWith('SELECT "suspended"'))return{rows:[{suspended:false}],rowCount:1};if(sql.includes('FROM "zzsh_iam"."user_identity_state"'))return{rows:[{accountStatus:'ACTIVE'}]};if(sql.includes('FROM "zzsh_auth_user"."session"'))return{rows:[{}],rowCount:1};if(sql.includes("to_regclass('zzsh_order.rental_referral_earning')"))return{rows:[{installed:true}]};if(sql.includes('recovery_required_cents'))return{rows:[{count:'0',amount:'0',invalid:0}]};if(sql.includes('SELECT d.*,a.id AS cohort_id'))return{rows:[destination]};if(sql.startsWith('SELECT date_trunc'))return{rows:[{now}]};
  if(sql.includes("to_regclass('zzsh_order.wallet_coverage')"))return{rows:[{ready:true}]};if(sql.startsWith('SELECT id FROM zzsh_auth_user'))return{rows:[{id:'user'}],rowCount:1};if(sql.startsWith('SELECT c.origin,b.source_cutoff'))return{rows:[{origin:'NATIVE_GENESIS',coverageVersion:'1'}]};if(sql.startsWith('SELECT c.origin,b.source_kind'))return{rows:[{origin:'NATIVE_GENESIS',source_kind:'NATIVE_GENESIS',opening_amount:'0',covered_count:0}]};if(sql.startsWith('SELECT ledger_revision'))return{rows:[{ledgerRevision:'9',readRevision:'10',version:'9'}]};if(sql.includes('AS available'))return{rows:[{available:'1000',reserved:'0',pending:'0',refund:'0'}]};
  if(sql.startsWith('SELECT state,accepted_at')||sql.startsWith('SELECT 1 FROM zzsh_order.withdrawal_intent WHERE destination_id'))return{rows:[],rowCount:0};if(sql.includes('count(*)::int AS n,COALESCE(sum(gross_cents)'))return{rows:[{n:0,gross:'0'}]};if(sql.includes('FROM "zzsh_supply"."idempotency_record"'))return{rows:[]};
  if(sql.startsWith('INSERT INTO zzsh_order.withdrawal_intent')){row={id:args[0],user_id:args[1],admission_id:args[2],destination_id:args[3],policy_version:args[5],expected_ledger_revision:args[10],accepted_at:new Date(args[11]),gross_cents:args[7],net_cents:args[8],fee_cents:args[9],payout_key:args[12],economic_root_id:args[13],state:'RESERVED',operation_version:'1',funds_disposition:'RESERVED',terminal:null,lease_token_hash:null,conflict_digest:null};return{rows:[row]};}
  if(sql.startsWith('SELECT id,user_id,admission_id'))return{rows:row?[row]:[]};if(sql.startsWith('INSERT INTO zzsh_order.settlement_ledger_entry'))ledger.push(args);
  if(['BEGIN','COMMIT','ROLLBACK','SET CONSTRAINTS ALL IMMEDIATE'].includes(sql)||sql.startsWith('SELECT pg_advisory_xact_lock')||sql.startsWith('INSERT'))return{rows:[]};throw Error('Unexpected native reserve SQL: '+sql);
 }})} as unknown as Pool;return{pool,scope,actor,body,key,id,payoutKey,destination,sqls,ledger,get row(){return row;}};
}
test('valid native quote and fresh reserve reuse original fee, identity and ledger rules',async()=>{const f=fixture(),q=await readControlledWithdrawalQuote(f.pool,f.actor,f.body,f.scope);assert.equal(q.quote.requestKey,f.key);assert.equal(q.quote.feeCents,'100');assert.equal(q.quote.netCents,'100');assert.equal(q.quote.globalWithdrawable,'UNKNOWN');const r=await createControlledWithdrawal(f.pool,f.actor,f.body,f.key,f.scope);assert.equal(r.replayed,false);assert.equal(f.row.id,f.id);assert.equal(f.row.payout_key,f.payoutKey);assert.deepEqual(f.ledger.map(v=>[v[3],v[4],v[5]]),[['WALLET_AVAILABLE','200','0'],['WALLET_RESERVED','0','200']]);});
test('allowed subject does not authorize a different destination/cohort tuple',async()=>{const f=fixture();f.destination.admission_id='foreign';await assert.rejects(readControlledWithdrawalQuote(f.pool,f.actor,f.body,f.scope),/DESTINATION_NOT_ADMITTED/);assert(!f.sqls.some(s=>s.startsWith('INSERT')));});
test('native quote rejects wrong live cohort resource despite a matching configured id',async()=>{const f=fixture();f.destination.resource_oid=833000;await assert.rejects(readControlledWithdrawalQuote(f.pool,f.actor,f.body,f.scope),/CONTROLLED_LOCAL_ADMISSION_UNAVAILABLE/);assert(!f.sqls.some(s=>s.startsWith('INSERT')));});


