import {test} from "node:test";import assert from "node:assert/strict";import {createHash} from 'node:crypto';import {canonicalize} from '../src/supply/content-hash';
import {sourceYuanToCents,exactCents,prepareHistoricalObservation,parseFinanceQuery,encodeFinanceCursor,decodeFinanceCursor,readPersonalWallet,readPersonalFinanceEntry,readPersonalFinanceEntries} from "../src/finance/personal-finance-read";
import {mountPersonalFinanceRead} from '../src/finance/personal-finance-routes';
import {authorizeFinanceMaintenance,importReviewedFinanceOpeningBatch} from '../src/finance/personal-finance-maintenance';
test('wallet money remains exact and rejects invalid source precision',()=>{assert.equal(sourceYuanToCents('99999999999999.99'),'9999999999999999');assert.equal(exactCents('-123'),'-123');for(const n of [1,'1.001','01.00','-1.00'])assert.throws(()=>sourceYuanToCents(n));for(const n of [1,'01','-0','1.1'])assert.throws(()=>exactCents(n));});
test('historical verifier requires exact frozen admission, valid direction and snapshot time',()=>{
 const row={kind:'earningsLog',sourceId:1,sourceUserId:7,amount:'1.23',leftAmount:'0.00',action:1,createdAt:1790990000};
 const mapping={userId:'stable-7',legacyUserId:'7',sourceSystem:'FIXTURE_NOT_HISTORY',basisId:'basis-7'};
 const bind=(r:Record<string,unknown>,included=true)=>({...mapping,openingAdmission:{sourceDigest:createHash('sha256').update(canonicalize(r)).digest('hex'),included,cutoff:'2026-10-03T02:31:22.516Z'}});
 const result=prepareHistoricalObservation(row,bind(row));assert.equal(result.includedInOpening,true);assert.equal(result.sourceId,'1');
 for(const action of [undefined,0,3,'1']){const r={...row,action};assert.throws(()=>prepareHistoricalObservation(r,bind(r)));}
 for(const action of [1,2]){const r={...row,amount:'0.00',action};assert.equal(prepareHistoricalObservation(r,bind(r)).sourceEventAt,new Date(row.createdAt*1000).toISOString());}
 assert.throws(()=>prepareHistoricalObservation(row,mapping));assert.throws(()=>prepareHistoricalObservation({...row,sourceUserId:8},bind(row)));assert.throws(()=>prepareHistoricalObservation({...row,leftAmount:'1.001'},bind(row)));
 const late={...row,createdAt:1791000000};assert.throws(()=>prepareHistoricalObservation(late,bind(late)));
 const pending={...row,kind:'historicalDistribution',sourceStatus:1,sourceUpdatedAt:row.createdAt};assert.equal(prepareHistoricalObservation(pending,bind(pending,false)).includedInOpening,false);
});
test('ALL keeps available and refund liability net changes in separate buckets',async()=>{
 const at='2026-10-03T00:00:00.000000Z';const base={at,imported_at:at,kind:'POSTED',included:false,source_kind:'NATIVE_SETTLEMENT',source_type:'NATIVE',source_system:'zzsh',source_entity:'settlement_posting',source_id:'same-id',balance_after:null,business_type:'RENTAL_ORDER',business_id:'order-id',business_no:null,sort_at:at};
 const totals=[{bucket:'AVAILABLE',count:'1',postedNetCents:'100',coveredHistoricalNetCents:'0',uncoveredHistoricalNetCents:'0',coveredCount:'0',uncoveredCount:'0'},{bucket:'REFUND_PAYABLE',count:'1',postedNetCents:'80',coveredHistoricalNetCents:'0',uncoveredHistoricalNetCents:'0',coveredCount:'0',uncoveredCount:'0'}];
 const client={query:async(sql:string)=>sql.includes('to_regclass')?{rows:[{ready:true}]}:sql.includes('FOR SHARE')?{rowCount:1,rows:[]}:sql.includes('AS available')?{rows:[{available:'100'}]}:sql.includes('GROUP BY bucket')?{rows:totals}:sql.includes('WITH entries')?{rows:[{...base,id:'ledger:a',bucket:'AVAILABLE',delta:'100'},{...base,id:'ledger:b',bucket:'REFUND_PAYABLE',delta:'80'}]}:sql.includes('clock_timestamp() AT TIME ZONE')?{rows:[{at}]}:{rows:[]}};
 const result=await readPersonalFinanceEntries(client as any,{userId:'u1',sessionId:'s1'},{limit:20,cursor:null,bucket:'ALL'},undefined);assert.equal(result.totals.byBucket.length,2);assert.equal((result.totals as any).postedNetCents,undefined);assert.equal(result.totals.byBucket[0]!.postedNetCents,'100');assert.equal(result.totals.byBucket[1]!.postedNetCents,'80');assert.equal(result.items[0]!.source.entity,'settlement_posting');
});
test('private cursor cannot be reused for another subject, session, filter or snapshot',()=>{const key={keyId:'fixture',secret:'controlled-fixture-secret-not-production-0001'},binding={userId:'u1',sessionHash:'h1',snapshotVersion:'1:1:1',bucket:'ALL'},at='2026-10-03T00:00:00.000000Z';const token=encodeFinanceCursor({at,id:'history:a'},at,binding,key);assert.equal(decodeFinanceCursor(token,binding,key).position.id,'history:a');for(const patch of [{userId:'u2'},{sessionHash:'h2'},{snapshotVersion:'2:2:1'},{bucket:'AVAILABLE'}])assert.throws(()=>decodeFinanceCursor(token,{...binding,...patch},key),(e:any)=>e.status===409);assert.throws(()=>decodeFinanceCursor(token+'a',binding,key));assert.throws(()=>parseFinanceQuery(new URLSearchParams('userId=u2')));assert.throws(()=>parseFinanceQuery(new URLSearchParams('limit=101')));});
test('missing schema is a controlled 503 and unadmitted subjects do not get zero balances',async()=>{await assert.rejects(readPersonalWallet({query:async()=>({rows:[{ready:false}]})} as any,'u1'),(e:any)=>e.status===503);const client={query:async(sql:string)=>sql.includes('to_regclass')?{rows:[{ready:true}]}:sql.includes('FOR SHARE')?{rowCount:1,rows:[]}:sql.includes('AS available')?{rows:[{available:'12345'}]}:{rows:[]}};const result=await readPersonalWallet(client as any,'u1');assert.equal(result.buckets.available.amountCents,null);assert.equal(result.coverage.knowledge,'UNKNOWN');assert.equal(result.withdrawable.amountCents,null);});
test('foreign finance detail has no fallback or foreign amount',async()=>{const client={query:async(sql:string)=>sql.includes('to_regclass')?{rows:[{ready:true}]}:sql.includes('FOR SHARE')?{rowCount:1,rows:[]}:sql.includes('AS available')?{rows:[{available:'0'}]}:({rows:[]})};await assert.rejects(readPersonalFinanceEntry(client as any,'u1','history:other'),(e:any)=>e.status===404);});
test('historical coverage and equal source IDs retain distinct entity and detail context',async()=>{
 const at='2026-10-03T00:00:00.000000Z';
 const rows=[{id:'ledger:native',at,imported_at:at,bucket:'AVAILABLE',delta:'100',kind:'POSTED',included:false,source_kind:'NATIVE_SETTLEMENT',source_id:'1',balance_after:null,source_type:'NATIVE',source_system:'zzsh',source_entity:'settlement_posting',business_id:'order-1',business_no:null,business_type:'RENTAL_ORDER',sort_at:at},
 {id:'history:legacy',at,imported_at:at,bucket:'AVAILABLE',delta:'-20',kind:'HISTORICAL',included:false,source_kind:'HISTORICAL_EARNINGS_LOG',source_id:'1',balance_after:'80',source_type:'LEGACY_MYSQL',source_system:'fixture',source_entity:'la_log_earnings',business_id:'1',business_no:'legacy-sn',business_type:'LEGACY_UNRESOLVED',sort_at:at}];
 const client={query:async(sql:string,args:any[])=>sql.includes('to_regclass')?{rows:[{ready:true}]}:sql.includes('FOR SHARE')?{rowCount:1,rows:[]}:sql.includes('AS available')?{rows:[{available:'100'}]}:sql.includes('GROUP BY bucket')?{rows:[{bucket:'AVAILABLE',count:'2',postedNetCents:'100',coveredHistoricalNetCents:'0',uncoveredHistoricalNetCents:'-20',coveredCount:'0',uncoveredCount:'1'}]}:sql.includes('WITH entries')?{rows:sql.includes('WHERE id=$2')?rows.filter(r=>r.id===args[1]):rows}:sql.includes('clock_timestamp() AT TIME ZONE')?{rows:[{at}]}:{rows:[]}};
 const page=await readPersonalFinanceEntries(client as any,{userId:'u1',sessionId:'s1'},{limit:20,cursor:null,bucket:'ALL'},undefined);
 assert.equal(page.totals.historicalCoverage,'NOT_INCLUDED');assert.equal(page.totals.byBucket[0]!.postedNetCents,'100');assert.equal(page.totals.byBucket[0]!.uncoveredHistoricalNetCents,'-20');assert.equal(page.items[0]!.source.id,page.items[1]!.source.id);assert.notEqual(page.items[0]!.source.entity,page.items[1]!.source.entity);
 const detail=await readPersonalFinanceEntry(client as any,'u1','history:legacy');assert.equal(detail.contractVersion,'personal-finance.read.v1');assert.equal(detail.subjectId,'u1');assert.equal(detail.snapshotVersion,'0:0:0');assert.equal(detail.coverage.knowledge,'UNKNOWN');assert.equal(detail.entry.schemaVersion,1);assert.equal(detail.entry.businessReference.number,'legacy-sn');assert.equal(detail.entry.includedInOpening,false);
});
test('opening maintenance rechecks active Boss and live unlocked two-factor session',async()=>{
 const actor={userId:'boss',sessionId:'session',requestId:'request'};
 for(const scenario of [{expired:true,status:401},{locked:true,status:423},{twoFactorEnabled:false,status:403},{security:'FROZEN',status:401},{isBoss:false,status:403},{suspended:true,status:403},{passwordChangeRequired:true,status:403}]){
  const client={query:async(sql:string)=>sql.includes('SELECT suspended')?{rows:[{suspended:'suspended'in scenario}]}:sql.includes('zzsh_auth_admin')?{rows:'expired'in scenario?[]:[{locked:'locked'in scenario,twoFactorEnabled:!('twoFactorEnabled'in scenario)}]}:{rows:[{status:'security'in scenario?scenario.security:'ACTIVE',isBoss:!('isBoss'in scenario),passwordChangeRequired:'passwordChangeRequired'in scenario}]}};
  await assert.rejects(authorizeFinanceMaintenance(client as any,actor),(e:any)=>e.status===scenario.status);
 }
});
test('reviewed opening batch rejects changed or duplicate bodies before opening a transaction',async()=>{
 const pool={connect:async()=>{throw Error('UNREVIEWED_BODY_MUST_NOT_CONNECT');}},actor={userId:'boss',sessionId:'s',requestId:'r'};
 const inputs=['a','b','c'].map(userId=>({proof:{userId}}));
 await assert.rejects(importReviewedFinanceOpeningBatch(pool as any,actor,inputs as any,['a'.repeat(64),'b'.repeat(64),'c'.repeat(64)]),(e:any)=>e.status===400);
 await assert.rejects(importReviewedFinanceOpeningBatch(pool as any,actor,[...inputs.slice(0,2),inputs[0]] as any,['a'.repeat(64),'b'.repeat(64),'c'.repeat(64)]),(e:any)=>e.status===400);
});
test('wallet route authenticates first and never accepts a client subject header',async()=>{
 let handler:any,authenticated=false;const seen:any[]=[];
 const query=async(sql:string,args?:unknown[])=>{seen.push({sql,args});if(sql.includes('to_regclass'))return {rows:[{ready:true}],rowCount:1};if(sql.includes('AS available'))return {rows:[{available:'0'}],rowCount:1};if(sql.includes('wallet_coverage')||sql.includes('wallet_revision')||sql.includes('WITH entries'))return {rows:[],rowCount:0};return {rows:[{suspended:false,accountStatus:'ACTIVE'}],rowCount:1};};
 const client={query,release(){}},pool={query,connect:async()=>client};
 mountPersonalFinanceRead({getHttpAdapter:()=>({getInstance:()=>({use:(_path:string,h:any)=>{handler=h;}})})} as any,{pool,userAuth:{api:{getSession:async()=>authenticated?{user:{id:'trusted-user'},session:{id:'trusted-session'}}:null}},apiOrigin:'http://127.0.0.1:3102',userOrigin:'http://127.0.0.1:3100'} as any);
 const call=async(path:string)=>{const r:any={headers:new Map(),statusCode:0,status(n:number){this.statusCode=n;return this;},setHeader(k:string,v:string){this.headers.set(k,v);return this;},json(b:any){this.body=b;this.headersSent=true;}};await handler({method:'GET',originalUrl:path,headers:{'x-user-id':'foreign',origin:'http://127.0.0.1:3100'}},r);return r;};
 assert.equal((await call('/api/v1/users/me/wallet')).statusCode,401);assert.equal(seen.length,0);authenticated=true;
 const own=await call('/api/v1/users/me/wallet');assert.equal(own.statusCode,200);assert.equal(own.body.wallet.subjectId,'trusted-user');assert.equal(own.body.wallet.buckets.available.amountCents,null);assert.equal(own.headers.get('Cache-Control'),'no-store');
 assert.equal((await call('/api/v1/users/me/wallet/entries/history:foreign')).statusCode,404);
 assert(seen.filter(r=>r.args?.[0]).every(r=>r.args[0]==='trusted-user'||r.args[0]==='trusted-session'));
});
