import {randomUUID} from 'node:crypto';import {isHttpOrigin,userCookies,readBoundedBody,BodyTooLargeError} from './user-proxy.ts';
const api=process.env.ZZSH_API_ORIGIN??'',web=process.env.ZZSH_WEB_ORIGIN??'';
const fail=(status:number,code:string,id:string)=>Response.json({error:{code,message:'提现状态暂不可用，请查询原申请。',requestId:id}},{status,headers:{'cache-control':'no-store','x-request-id':id}});
const obj=(v:any)=>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error();return v;};const cents=(v:any)=>{if(typeof v!=='string'||!/^(0|[1-9]\d{0,23})$/.test(v))throw Error();return v;};
function intent(value:any){const i=obj(value);if(i.scope!=='LOCAL_CONTROLLED'||typeof i.id!=='string'||!['RESERVED','SUBMITTING','PROCESSING','UNKNOWN','SUCCEEDED','FAILED','RECONCILIATION_REQUIRED'].includes(i.state)||!['RESERVED','PAYOUT_POSTED','RELEASE_POSTED'].includes(i.fundsDisposition))throw Error();const amount=cents(i.amountCents),net=cents(i.netCents),fee=cents(i.feeCents);if(BigInt(net)<=0n||BigInt(amount)!==BigInt(net)+BigInt(fee))throw Error();return{id:i.id,scope:'LOCAL_CONTROLLED',userId:i.userId,state:i.state,operationVersion:i.operationVersion,fundsDisposition:i.fundsDisposition,amountCents:amount,netCents:net,feeCents:fee,destinationId:i.destinationId,policyVersion:i.policyVersion,acceptedAt:i.acceptedAt,evidenceLevel:'LOCAL_CONTROLLED',terminal:i.terminal?{state:i.terminal.state,reference:i.terminal.reference}:null};}
function project(body:any){const b=obj(body);
 if(b.quote){const q=obj(b.quote);if(q.scope!=='LOCAL_CONTROLLED'||q.mode!=='LOCAL_CONTROLLED'||q.identityMeaning!=='EXPLICIT_LOCAL_TEST_ADMISSION_NOT_REAL_KYC'||q.globalWithdrawable!=='UNKNOWN'||typeof q.requestKey!=='string'||!/^[A-Za-z0-9._:-]{1,128}$/.test(q.requestKey))throw Error();const amount=cents(q.grossCents),net=cents(q.netCents),fee=cents(q.feeCents);if(BigInt(net)<=0n||BigInt(amount)!==BigInt(net)+BigInt(fee))throw Error();return{quote:{requestKey:q.requestKey,scope:q.scope,userId:q.userId,destinationId:q.destinationId,destination:{id:q.destination.id,kind:q.destination.kind,mask:q.destination.mask},policyVersion:q.policyVersion,ledgerRevision:q.ledgerRevision,acceptedAt:q.acceptedAt,currency:'CNY',grossCents:amount,netCents:net,feeCents:fee,admissionRevision:q.admissionRevision,identityMeaning:q.identityMeaning,globalWithdrawable:'UNKNOWN'}};}
 if(b.intent)return{scope:'LOCAL_CONTROLLED',intent:intent(b.intent)};
 if(b.knowledge){if(b.scope!=='LOCAL_CONTROLLED'||!['KNOWN','UNKNOWN'].includes(b.knowledge)||(b.knowledge==='KNOWN')!==(b.receipt!==null))throw Error();return{scope:b.scope,knowledge:b.knowledge,receipt:b.receipt?{intent:intent(b.receipt.intent)}:null};}
 if(b.scope!=='LOCAL_CONTROLLED'||b.globalReserved!=='UNKNOWN'||b.coverage?.knowledge!=='KNOWN'||!Array.isArray(b.items)||!Array.isArray(b.destinations)||!Array.isArray(b.coverage.cohorts))throw Error();return{scope:b.scope,subjectId:b.subjectId,coverage:{knowledge:'KNOWN',meaning:'EXPLICIT_LOCAL_INTENTS_ONLY_NOT_TOTAL_HISTORICAL_WALLET',cohorts:b.coverage.cohorts.map((c:any)=>({id:c.id,revision:c.revision,start:c.start,end:c.end}))},items:b.items.map(intent),destinations:b.destinations.map((d:any)=>({id:d.id,kind:d.kind,mask:d.mask,policyVersion:typeof d.policyVersion==='string'?d.policyVersion:null,perIntentCents:d.perIntentCents===undefined?null:cents(d.perIntentCents),canQuote:d.canQuote===true})),totals:{reservedCents:cents(b.totals.reservedCents),payoutCents:cents(b.totals.payoutCents),feeCents:cents(b.totals.feeCents)},globalReserved:'UNKNOWN'};
}
async function proxy(request:Request,{params}:{params:Promise<{path?:string[]}>}){const id='req_controlled_'+randomUUID().replaceAll('-','');if(!isHttpOrigin(api)||!isHttpOrigin(web))return fail(503,'EVIDENCE_UNAVAILABLE',id);if(request.headers.has('authorization'))return fail(403,'FORBIDDEN',id);const parts=(await params).path??[],method=request.method;
 if(parts.length>1||parts.some(p=>!/^[A-Za-z0-9_-]{1,128}$/.test(p)))return fail(404,'NOT_FOUND',id);if(!['GET','POST'].includes(method))return fail(404,'NOT_FOUND',id);
 const query=new URL(request.url).searchParams;if(method==='GET'&&parts[0]==='receipt'){if([...query.keys()].some(k=>k!=='key')||!query.get('key')||query.get('key')!.length>128)return fail(400,'INVALID_ARGUMENT',id);}else if(query.size)return fail(400,'INVALID_ARGUMENT',id);
 if(method==='POST'&&parts.length&&parts[0]!=='quote')return fail(404,'NOT_FOUND',id);if(method==='GET'&&parts[0]==='quote')return fail(404,'NOT_FOUND',id);
 const headers=new Headers({origin:web,'x-request-id':id});const cookie=userCookies(request.headers.get('cookie'));if(cookie)headers.set('cookie',cookie);let bytes:string|undefined;
 if(method==='POST'){if(request.headers.get('origin')!==web||request.headers.get('content-type')?.split(';')[0]?.trim()!=='application/json')return fail(403,'FORBIDDEN',id);try{const body=JSON.parse(new TextDecoder().decode(await readBoundedBody(request,4096)));obj(body);if(Object.keys(body).some(k=>!['amountCents','destinationId','policyVersion','expectedWalletVersion'].includes(k))||Object.keys(body).length!==4)throw Error();cents(body.amountCents);if(['destinationId','policyVersion','expectedWalletVersion'].some(k=>typeof body[k]!=='string'||body[k].length<1||body[k].length>128))throw Error();bytes=JSON.stringify(body);}catch(e){return fail(e instanceof BodyTooLargeError?413:400,'INVALID_ARGUMENT',id);}headers.set('content-type','application/json');if(!parts.length){const key=request.headers.get('idempotency-key');if(!key||!/^[A-Za-z0-9._:-]{1,128}$/.test(key))return fail(400,'INVALID_ARGUMENT',id);headers.set('idempotency-key',key);}}
 const url=new URL('/api/v1/users/me/withdrawals'+(parts[0]?'/'+encodeURIComponent(parts[0]):''),api);url.search=query.toString();
 try{const deadline=AbortSignal.timeout(15000),upstream=await fetch(url,{method,headers,body:bytes,cache:'no-store',redirect:'error',signal:deadline}),body=JSON.parse(new TextDecoder().decode(await readBoundedBody(upstream,128*1024,deadline)));if(!upstream.ok)return fail(upstream.status,typeof body.error?.code==='string'?body.error.code:'INTERNAL_ERROR',id);return Response.json(project(body),{headers:{'cache-control':'no-store','x-request-id':id,'x-content-type-options':'nosniff'}});}catch{return fail(502,method==='POST'&&!parts.length?'WRITE_OUTCOME_UNKNOWN':'EVIDENCE_UNAVAILABLE',id);}
}
export const GET=proxy;export const POST=proxy;
