import {WalletRequestError,parseNativeReservation,type NativeReservation} from './personal-wallet-client.ts';
export type WithdrawalBody={amountCents:string;destinationId:string;policyVersion:string;expectedWalletVersion:string};
export type LocalWithdrawal={id:string;userId:string;state:'RESERVED'|'SUBMITTING'|'PROCESSING'|'UNKNOWN'|'SUCCEEDED'|'FAILED'|'RECONCILIATION_REQUIRED';operationVersion:string;fundsDisposition:'RESERVED'|'PAYOUT_POSTED'|'RELEASE_POSTED';amountCents:string;netCents:string;feeCents:string;destinationId:string;policyVersion:string;acceptedAt:string;terminal:{state:'SUCCEEDED'|'FAILED';reference:string}|null};
export type LocalWithdrawalScope={nativeWithdrawal?:NativeReservation;items:LocalWithdrawal[];destinations:{id:string;kind:'BANK_CARD'|'PAYMENT_CODE';mask:string;policyVersion:string|null;perIntentCents:string|null;canQuote:boolean}[];totals:{reservedCents:string;payoutCents:string;feeCents:string};cohorts:{id:string;revision:string;start:string;end:string}[]};
export type WithdrawalQuote=WithdrawalBody&{requestKey:string;netCents:string;feeCents:string;destinationMask:string;acceptedAt:string};
type Pending={version:1;userId:string;key:string;body:WithdrawalBody};
const bad=()=>new WalletRequestError(502,'WITHDRAWAL_CONTRACT_REQUIRED');
const object=(v:any)=>{if(!v||typeof v!=='object'||Array.isArray(v))throw bad();return v;};
const text=(v:any,max=128):string=>{if(typeof v!=='string'||!v||v.length>max)throw bad();return v;};
const cents=(v:any):string=>{const s=text(v,24);if(!/^(0|[1-9]\d{0,23})$/.test(s))throw bad();return s;};
const time=(v:any):string=>{const s=text(v,40);if(!Number.isFinite(Date.parse(s)))throw bad();return s;};
function intent(v:any,userId:string,id?:string):LocalWithdrawal{const i=object(v);if(i.scope!=='LOCAL_CONTROLLED'||i.evidenceLevel!=='LOCAL_CONTROLLED'||id&&i.id!==id)throw bad();if(i.userId!==userId)throw new WalletRequestError(401,'IDENTITY_CHANGED');if(!['RESERVED','SUBMITTING','PROCESSING','UNKNOWN','SUCCEEDED','FAILED','RECONCILIATION_REQUIRED'].includes(i.state)||!['RESERVED','PAYOUT_POSTED','RELEASE_POSTED'].includes(i.fundsDisposition))throw bad();const amount=cents(i.amountCents),net=cents(i.netCents),fee=cents(i.feeCents);if(BigInt(net)<=0n||BigInt(amount)!==BigInt(net)+BigInt(fee))throw bad();const terminal=i.terminal===null?null:object(i.terminal);if(terminal&&(!['SUCCEEDED','FAILED'].includes(terminal.state)||terminal.state==='SUCCEEDED'&&i.fundsDisposition!=='PAYOUT_POSTED'||terminal.state==='FAILED'&&i.fundsDisposition!=='RELEASE_POSTED')||!terminal&&i.fundsDisposition!=='RESERVED')throw bad();return{id:text(i.id),userId,state:i.state,operationVersion:cents(i.operationVersion),fundsDisposition:i.fundsDisposition,amountCents:amount,netCents:net,feeCents:fee,destinationId:text(i.destinationId),policyVersion:text(i.policyVersion),acceptedAt:time(i.acceptedAt),terminal:terminal?{state:terminal.state,reference:text(terminal.reference)}:null};}
async function request(path:string,body?:WithdrawalBody,key?:string,signal?:AbortSignal){let r:Response;try{r=await fetch('/api/account/withdrawals'+path,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',signal,...(body?{headers:{'content-type':'application/json',...(key?{'idempotency-key':key}:{})},body:JSON.stringify(body)}:{})});}catch{throw new WalletRequestError(0,'NETWORK_ERROR');}const b=await r.json().catch(()=>null);if(!r.ok)throw new WalletRequestError(r.status,typeof b?.error?.code==='string'?b.error.code:'INTERNAL_ERROR');return object(b);}
export async function readLocalWithdrawals(userId:string,signal?:AbortSignal):Promise<LocalWithdrawalScope>{const b=await request('',undefined,undefined,signal),c=object(b.coverage),t=object(b.totals);if(b.subjectId!==userId)throw new WalletRequestError(401,'IDENTITY_CHANGED');if(b.scope!=='LOCAL_CONTROLLED'||b.globalReserved!=='UNKNOWN'||c.knowledge!=='KNOWN'||c.meaning!=='EXPLICIT_LOCAL_INTENTS_ONLY_NOT_TOTAL_HISTORICAL_WALLET'||!Array.isArray(b.items)||!Array.isArray(b.destinations)||!Array.isArray(c.cohorts))throw bad();return{nativeWithdrawal:parseNativeReservation(b.nativeWithdrawal),items:b.items.map((i:any)=>intent(i,userId)),destinations:b.destinations.map((d:any)=>{if(!['BANK_CARD','PAYMENT_CODE'].includes(d.kind))throw bad();return{id:text(d.id),kind:d.kind,mask:text(d.mask,100),policyVersion:d.policyVersion===undefined||d.policyVersion===null?null:text(d.policyVersion),perIntentCents:d.perIntentCents===null||d.perIntentCents===undefined?null:cents(d.perIntentCents),canQuote:d.canQuote===true};}),totals:{reservedCents:cents(t.reservedCents),payoutCents:cents(t.payoutCents),feeCents:cents(t.feeCents)},cohorts:c.cohorts.map((x:any)=>({id:text(x.id),revision:cents(x.revision),start:time(x.start),end:time(x.end)}))};}
export async function readLocalWithdrawal(userId:string,id:string){const b=await request('/'+encodeURIComponent(id));return intent(b.intent,userId,id);}
export async function quoteLocalWithdrawal(userId:string,body:WithdrawalBody):Promise<WithdrawalQuote>{const q=object((await request('/quote',body)).quote);if(q.scope!=='LOCAL_CONTROLLED'||q.globalWithdrawable!=='UNKNOWN'||q.identityMeaning!=='EXPLICIT_LOCAL_TEST_ADMISSION_NOT_REAL_KYC')throw bad();if(q.userId!==userId)throw new WalletRequestError(401,'IDENTITY_CHANGED');if(q.grossCents!==body.amountCents||q.destinationId!==body.destinationId||q.policyVersion!==body.policyVersion||q.ledgerRevision!==body.expectedWalletVersion||q.destination?.id!==body.destinationId)throw bad();const net=cents(q.netCents),fee=cents(q.feeCents);if(BigInt(body.amountCents)!==BigInt(net)+BigInt(fee)||BigInt(net)<=0n)throw bad();const key=text(q.requestKey);if(!/^[A-Za-z0-9._:-]{1,128}$/.test(key))throw bad();return{...body,requestKey:key,netCents:net,feeCents:fee,destinationMask:text(q.destination.mask,100),acceptedAt:time(q.acceptedAt)};}
const markerKey=(userId:string)=>'zzsh.withdrawal.pending.v1:'+userId;
export function pendingLocalWithdrawal(userId:string):Pending|null{const raw=localStorage.getItem(markerKey(userId));if(raw===null)return null;let p;try{p=object(JSON.parse(raw));if(p.version!==1||p.userId!==userId)throw bad();text(p.key);object(p.body);for(const k of ['amountCents','destinationId','policyVersion','expectedWalletVersion'])text(p.body[k]);cents(p.body.amountCents);}catch{throw new WalletRequestError(409,'PENDING_MARKER_UNREADABLE');}return p;}
function sameBody(i:LocalWithdrawal,b:WithdrawalBody){if(i.amountCents!==b.amountCents||i.destinationId!==b.destinationId||i.policyVersion!==b.policyVersion)throw bad();}
/** Persist before POST; an uncertain write can only be queried by this original key. */
export async function submitLocalWithdrawal(userId:string,quote:WithdrawalQuote,canAct:()=>boolean){if(!navigator.locks)throw new WalletRequestError(409,'WRITE_LOCK_UNAVAILABLE');return navigator.locks.request(markerKey(userId),{ifAvailable:true},async lock=>{if(!lock||pendingLocalWithdrawal(userId))throw new WalletRequestError(409,'WITHDRAWAL_UNRESOLVED');if(!canAct())throw new WalletRequestError(401,'IDENTITY_CHANGED');const body:WithdrawalBody={amountCents:quote.amountCents,destinationId:quote.destinationId,policyVersion:quote.policyVersion,expectedWalletVersion:quote.expectedWalletVersion},p:Pending={version:1,userId,key:quote.requestKey,body};localStorage.setItem(markerKey(userId),JSON.stringify(p));if(pendingLocalWithdrawal(userId)?.key!==p.key)throw new WalletRequestError(409,'WRITE_MARKER_UNAVAILABLE');let accepted=false;try{const created=intent((await request('',body,p.key)).intent,userId);accepted=true;sameBody(created,body);if(created.netCents!==quote.netCents||created.feeCents!==quote.feeCents)throw bad();if(!canAct())throw new WalletRequestError(401,'IDENTITY_CHANGED');const read=await readLocalWithdrawal(userId,created.id);sameBody(read,body);if(!canAct())throw new WalletRequestError(401,'IDENTITY_CHANGED');localStorage.removeItem(markerKey(userId));return read;}catch(e){if(!accepted&&e instanceof WalletRequestError&&[400,403,404,409,413,422].includes(e.status))localStorage.removeItem(markerKey(userId));throw e;}});}
export async function recoverLocalWithdrawal(userId:string,canAct:()=>boolean){const p=pendingLocalWithdrawal(userId);if(!p||!canAct())return null;const b=await request('/receipt?key='+encodeURIComponent(p.key));if(b.scope!=='LOCAL_CONTROLLED'||!['KNOWN','UNKNOWN'].includes(b.knowledge)||(b.knowledge==='KNOWN')!==(b.receipt!==null))throw bad();if(b.knowledge==='UNKNOWN')return null;const original=intent(object(b.receipt).intent,userId);sameBody(original,p.body);const current=await readLocalWithdrawal(userId,original.id);sameBody(current,p.body);if(!canAct())throw new WalletRequestError(401,'IDENTITY_CHANGED');if(pendingLocalWithdrawal(userId)?.key!==p.key)throw new WalletRequestError(409,'WRITE_MARKER_CHANGED');localStorage.removeItem(markerKey(userId));return current;}
export function yuanToCents(value:string):string{if(!/^(0|[1-9]\d{0,20})(\.\d{1,2})?$/.test(value))throw new WalletRequestError(400,'INVALID_AMOUNT');const [whole,fraction='']=value.split('.');return(BigInt(whole!)*100n+BigInt(fraction.padEnd(2,'0'))).toString();}
