export type WalletBucket = "available" | "reserved" | "restricted" | "pendingEarnings" | "refundPayable";
export type EntryBucket = "AVAILABLE" | "REFUND_PAYABLE" | "ALL";
export type KnowledgeMoney = { currency: "CNY"; unit: "cent"; knowledge: "KNOWN" | "UNKNOWN"; amountCents: string | null };
export type FinanceCoverage = { knowledge: "KNOWN" | "UNKNOWN"; origin?: string; cutoff?: string; coverageVersion?: string; reason?: string };
export type NativeReservation = {scope:'NATIVE_REFERRAL_OBLIGATIONS_ONLY';subjectInScope:boolean;globalWithdrawable:'UNKNOWN';reservationState:'NOT_IN_SCOPE'|'UNKNOWN'|'BLOCKED_BY_RECOVERY'|'REQUIRES_CURRENT_QUOTE';recovery:{knowledge:'KNOWN';outstandingCents:string;earningCount:string;scope:'NATIVE_REFERRAL_OBLIGATIONS_ONLY'}|{knowledge:'UNKNOWN';outstandingCents:null;earningCount:null;reason:string}};
export type WalletRead = { contractVersion: string; subjectId: string; asOf: string; coverage: FinanceCoverage; ledgerRevision: string; readRevision: string; snapshotVersion: string; buckets: Record<WalletBucket, KnowledgeMoney>; withdrawable: KnowledgeMoney & { reasonCodes: string[] };nativeWithdrawal?:NativeReservation };
export type WalletEntry = { schemaVersion: 1; id: string; occurredAt: string; importedAt: string; bucket: "AVAILABLE" | "REFUND_PAYABLE"; deltaCents: string; kind: "POSTED" | "HISTORICAL"; includedInOpening: boolean; sourceKind: string; source: { type: string; system: string | null; entity: string | null; id: string | null }; businessReference: { type: string; id: string | null; number: string | null }; balanceAfterCents: string | null };
export type FinanceContext = { contractVersion: string; subjectId: string; asOf: string; snapshotVersion: string; coverage: FinanceCoverage };
export type WalletEntryPage = FinanceContext & { bucket: EntryBucket; items: WalletEntry[]; nextCursor: string | null; totals: { count: string; historicalCoverage: string; meaning: string; byBucket: { bucket: "AVAILABLE" | "REFUND_PAYABLE"; count: string; postedNetCents: string; coveredHistoricalNetCents: string; uncoveredHistoricalNetCents: string; coveredCount: string; uncoveredCount: string }[] } };
export type WalletEntryDetail = FinanceContext & { entry: WalletEntry };
export class WalletRequestError extends Error {
  readonly status: number;
  readonly code: string;
  constructor(status: number, code: string) { super(code); this.status = status; this.code = code; }
}
const buckets: WalletBucket[] = ["available", "reserved", "restricted", "pendingEarnings", "refundPayable"];
const object = (v: unknown): Record<string, any> => { if (!v || typeof v !== "object" || Array.isArray(v)) throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return v as Record<string, any>; };
const text = (v: unknown, max = 256): string => { if (typeof v !== "string" || !v || v.length > max) throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return v; };
const cents = (v: unknown): string => { const s = text(v, 25); if (!/^-?(0|[1-9]\d{0,23})$/.test(s) || s === "-0") throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return s; };
const count = (v: unknown): string => { const s = text(v, 24); if (!/^(0|[1-9]\d{0,23})$/.test(s)) throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return s; };
export function parseNativeReservation(value:unknown):NativeReservation|undefined{
 if(value===undefined)return undefined;
 const n=object(value),r=object(n.recovery),bad=()=>new WalletRequestError(502,'FINANCE_CONTRACT_REQUIRED');
 if(n.scope!=='NATIVE_REFERRAL_OBLIGATIONS_ONLY'||n.globalWithdrawable!=='UNKNOWN'||typeof n.subjectInScope!=='boolean')throw bad();
 let recovery:NativeReservation['recovery'];
 if(r.knowledge==='KNOWN'){const amount=count(r.outstandingCents),items=count(r.earningCount);if(r.scope!==n.scope||(amount==='0')!==(items==='0'))throw bad();recovery={knowledge:'KNOWN',outstandingCents:amount,earningCount:items,scope:n.scope};}
 else if(r.knowledge==='UNKNOWN'&&r.outstandingCents===null&&r.earningCount===null)recovery={knowledge:'UNKNOWN',outstandingCents:null,earningCount:null,reason:text(r.reason)};
 else throw bad();
 const state=!n.subjectInScope?'NOT_IN_SCOPE':recovery.knowledge==='UNKNOWN'?'UNKNOWN':recovery.outstandingCents!=='0'?'BLOCKED_BY_RECOVERY':'REQUIRES_CURRENT_QUOTE';if(n.reservationState!==state)throw bad();
 return{scope:n.scope,subjectInScope:n.subjectInScope,globalWithdrawable:'UNKNOWN',reservationState:state,recovery};
}
const time = (v: unknown): string => { const s = text(v, 40); if (!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,6})?Z$/.test(s) || !Number.isFinite(Date.parse(s))) throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return s; };
const nullable = (v: unknown) => v === null ? null : text(v);
function coverage(v: unknown): FinanceCoverage { const c = object(v); if (c.knowledge !== "KNOWN" && c.knowledge !== "UNKNOWN") throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return { knowledge: c.knowledge, origin: c.origin, cutoff: c.cutoff, coverageVersion: c.coverageVersion, reason: c.reason }; }
function context(v: unknown, expectedUserId: string): FinanceContext { const b = object(v); if (b.subjectId !== expectedUserId) throw new WalletRequestError(401, "IDENTITY_CHANGED"); if (b.contractVersion !== "personal-finance.read.v1") throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return { contractVersion: b.contractVersion, subjectId: b.subjectId, asOf: time(b.asOf), snapshotVersion: text(b.snapshotVersion), coverage: coverage(b.coverage) }; }
function money(v: unknown): KnowledgeMoney { const m = object(v); if (m.currency !== "CNY" || m.unit !== "cent" || !["KNOWN", "UNKNOWN"].includes(m.knowledge) || (m.knowledge === "KNOWN") !== (m.amountCents !== null)) throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); const n = m.amountCents === null ? null : cents(m.amountCents); if (n !== null && BigInt(n) < 0n) throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return { currency: "CNY", unit: "cent", knowledge: m.knowledge, amountCents: n }; }
function entry(v: unknown): WalletEntry { const e = object(v), source = object(e.source), ref = object(e.businessReference); if (e.schemaVersion !== 1 || !["AVAILABLE", "REFUND_PAYABLE"].includes(e.bucket) || !["POSTED", "HISTORICAL"].includes(e.kind) || typeof e.includedInOpening !== "boolean") throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return { schemaVersion: 1, id: text(e.id), occurredAt: time(e.occurredAt), importedAt: time(e.importedAt), bucket: e.bucket, deltaCents: cents(e.deltaCents), kind: e.kind, includedInOpening: e.includedInOpening, sourceKind: text(e.sourceKind), source: { type: text(source.type), system: nullable(source.system), entity: nullable(source.entity), id: nullable(source.id) }, businessReference: { type: text(ref.type), id: nullable(ref.id), number: nullable(ref.number) }, balanceAfterCents: e.balanceAfterCents === null ? null : cents(e.balanceAfterCents) }; }
async function get(path: string, signal?: AbortSignal): Promise<unknown> { let r: Response; try { r = await fetch("/api/account/wallet" + path, { credentials: "same-origin", cache: "no-store", signal }); } catch (e) { if (signal?.aborted) throw e; throw new WalletRequestError(0, "NETWORK_ERROR"); } const b = await r.json().catch(() => null); if (signal?.aborted) throw new DOMException("Aborted", "AbortError"); if (!r.ok) throw new WalletRequestError(r.status, typeof b?.error?.code === "string" ? b.error.code : "INTERNAL_ERROR"); if (!b) throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return b; }
export async function readMyWallet(userId: string, signal?: AbortSignal): Promise<WalletRead> { const b = object(await get("", signal)), w = object(b.wallet), base = context(w, userId), amounts = object(w.buckets), withdrawable = object(w.withdrawable); if (!Array.isArray(withdrawable.reasonCodes) || withdrawable.reasonCodes.some((v: unknown) => typeof v !== "string")) throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return { ...base, nativeWithdrawal:parseNativeReservation(w.nativeWithdrawal), ledgerRevision: count(w.ledgerRevision), readRevision: count(w.readRevision), buckets: Object.fromEntries(buckets.map(k => [k, money(amounts[k])])) as Record<WalletBucket, KnowledgeMoney>, withdrawable: { ...money(withdrawable), reasonCodes: withdrawable.reasonCodes } }; }
export async function readMyWalletEntries(userId: string, bucket: EntryBucket, cursor: string | null, signal?: AbortSignal): Promise<WalletEntryPage> { const q = new URLSearchParams({ bucket, limit: "20" }); if (cursor) q.set("cursor", cursor); const b = object(await get("/entries?" + q, signal)), base = context(b, userId), totals = object(b.totals); if (b.bucket !== bucket || !Array.isArray(b.items) || b.items.length > 20 || !Array.isArray(totals.byBucket)) throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return { ...base, bucket, items: b.items.map(entry), nextCursor: b.nextCursor === null ? null : text(b.nextCursor, 4096), totals: { count: count(totals.count), historicalCoverage: text(totals.historicalCoverage), meaning: text(totals.meaning, 500), byBucket: totals.byBucket.map((value: unknown) => { const t = object(value); if (!["AVAILABLE", "REFUND_PAYABLE"].includes(t.bucket)) throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return { bucket: t.bucket, count: count(t.count), postedNetCents: cents(t.postedNetCents), coveredHistoricalNetCents: cents(t.coveredHistoricalNetCents), uncoveredHistoricalNetCents: cents(t.uncoveredHistoricalNetCents), coveredCount: count(t.coveredCount), uncoveredCount: count(t.uncoveredCount) }; }) } }; }
export async function readMyWalletEntry(userId: string, id: string, signal?: AbortSignal): Promise<WalletEntryDetail> { const b = object(await get("/entries/" + encodeURIComponent(id), signal)), base = context(b, userId), item = entry(b.entry); if (item.id !== id) throw new WalletRequestError(502, "FINANCE_CONTRACT_REQUIRED"); return { ...base, entry: item }; }
/** No Number conversion: 24-digit accounting integers remain exact on screen. */
export function walletMoney(c: string | null, signed = false): string { if (c === null) return "待确认"; const n = BigInt(cents(c)), abs = n < 0n ? -n : n; return (n < 0n ? "− " : signed && n > 0n ? "+ " : "") + "¥" + (abs / 100n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "." + (abs % 100n).toString().padStart(2, "0"); }
export function financeEntryLabel(e: WalletEntry): string { return e.sourceKind === "OPENING" ? "期初余额" : e.kind === "HISTORICAL" ? "旧平台余额记录" : e.sourceKind === "CONTROLLED_WITHDRAWAL_RESERVE" ? "提现资金冻结" : e.sourceKind === "CONTROLLED_WITHDRAWAL_RELEASE" ? "提现资金释放" : e.bucket === "REFUND_PAYABLE" ? "订单应退款" : e.sourceKind === "NATIVE_SETTLEMENT" ? "出租结算" : "资金记录"; }
