import { useEffect, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { AdminApiError } from '@/api';
import { Message, errorText, time, useDirectoryRequest, type UserDirectoryData } from './user-directory-shared';
import { CREDIT_GUARANTEE_PERMISSION, PERMISSION, type User } from './user-directory-data';

const eventLabels:Record<string,string>={INITIALIZED:'初始信用',BREACH_CONFIRMED:'确认违约',BREACH_REVERSED:'撤销误判',RECOVERY_APPROVED:'审核恢复'};
const stateLabels:Record<string,string>={NOT_REQUIRED:'免缴',REQUIRED:'待补保证金',PAYMENT_PENDING:'支付待确认',SATISFIED:'已覆盖',REFUND_REQUESTED:'退款申请待处理',REFUND_PROCESSING:'原路退款处理中',REFUNDED:'已原路退还',FAILED:'失败待核',UNKNOWN:'未知'};
type Intent={subject:string;path:string;body:Record<string,unknown>;key:string;generation:number;persisted:boolean;phase:'unknown'|'readback'};
const intentMemory=new Map<string,Intent>();
const intentGenerations=new Map<string,number>();
const intentKey=(subject:string)=>`zzsh.admin.credit.${encodeURIComponent(subject)}`;
function remember(intent:Intent):boolean{const current=intentMemory.get(intent.subject);const differs=Boolean(current&&(current.key!==intent.key||current.generation!==intent.generation||current.path!==intent.path||JSON.stringify(current.body)!==JSON.stringify(intent.body)));if(differs&&intent.persisted)return false;if(current?.key===intent.key&&current.generation===intent.generation&&current.persisted)return true;try{intent.persisted=true;intentMemory.set(intent.subject,intent);sessionStorage.setItem(intentKey(intent.subject),JSON.stringify(intent));return true;}catch{intent.persisted=false;return false;}}
function restore(subject:string):Intent|null{const memory=intentMemory.get(subject);if(memory?.persisted)return memory;try{const value=JSON.parse(sessionStorage.getItem(intentKey(subject))??'null') as Intent|null;if(value?.persisted===true&&Number.isSafeInteger(value.generation)&&['unknown','readback'].includes(value.phase)&&value.subject===subject&&typeof value.key==='string'&&typeof value.path==='string'){intentMemory.set(subject,value);intentGenerations.set(subject,Math.max(intentGenerations.get(subject)??0,value.generation));return value;}}catch{/* storage is optional */}return null;}
function forget(intent:Intent){const current=intentMemory.get(intent.subject);if(current&&(current.key!==intent.key||current.generation!==intent.generation||current.path!==intent.path||JSON.stringify(current.body)!==JSON.stringify(intent.body)))return;try{const value=JSON.parse(sessionStorage.getItem(intentKey(intent.subject))??'null') as Intent|null;if(value&&(value.key!==intent.key||value.generation!==intent.generation||value.path!==intent.path||JSON.stringify(value.body)!==JSON.stringify(intent.body)))return;sessionStorage.removeItem(intentKey(intent.subject));}catch{if(intent.persisted)return;}if(!current||current.key===intent.key&&current.generation===intent.generation)intentMemory.delete(intent.subject);}
function phase(intent:Intent,value:'unknown'|'readback'):boolean{const current=intentMemory.get(intent.subject);if(!current||current.key!==intent.key||current.generation!==intent.generation||current.path!==intent.path||JSON.stringify(current.body)!==JSON.stringify(intent.body))return false;intent.phase=value;current.phase=value;try{const stored=JSON.parse(sessionStorage.getItem(intentKey(intent.subject))??'null') as Intent|null;if(stored&&(stored.key!==intent.key||stored.generation!==intent.generation||stored.path!==intent.path||JSON.stringify(stored.body)!==JSON.stringify(intent.body)))return false;sessionStorage.setItem(intentKey(intent.subject),JSON.stringify({...current,persisted:true}));return true;}catch{return false;}}
function unknownWrite(error:unknown){return error instanceof AdminApiError&&(error.status===0||error.status>=500);}

export function CreditPanel({adapter,user,refreshNonce}:{adapter:UserDirectoryData;user:User;refreshNonce:number}) {
  const [revision,setRevision]=useState(0); const [sourceType,setSourceType]=useState('ORDER'); const [sourceId,setSourceId]=useState(''); const [role,setRole]=useState('OWNER'); const [visibleReason,setVisibleReason]=useState(''); const [internalBasis,setInternalBasis]=useState(''); const [reverseReason,setReverseReason]=useState(''); const [reverseBasis,setReverseBasis]=useState(''); const [decisionReasons,setDecisionReasons]=useState<Record<string,string>>({}); const [releaseReasons,setReleaseReasons]=useState<Record<string,string>>({}); const [busy,setBusy]=useState(''); const [notice,setNotice]=useState('');
  const subject=`${adapter.snapshot.adminUserId}:${adapter.snapshot.session.id}:${user.id}`;
  const [pending,setPending]=useState<Intent|null>(()=>restore(subject));
  const {result,retry}=useDirectoryRequest(`${user.id}:credit:${refreshNonce}:${revision}`,signal=>adapter.credit(user.id,signal));
  useEffect(()=>{const restored=restore(subject);setPending(restored);setBusy(restored?(restored.phase==='readback'?'readback':'pending'):'');},[subject]);
  if(!adapter.has(PERMISSION.credit))return <Message title="信用处置读取受限">当前管理员没有信用读取权限。</Message>;
  if(result.state==='loading')return <Message title="正在读取信用与保证金"/>;
  if(result.state==='error')return <Message kind="error" title="信用与保证金读取失败" retry={retry}>{errorText(result.error)}</Message>;
  const data=result.data; const credit=data.credit; const canGuaranteeRead=adapter.hasCreditGuaranteeRead();
  const readback=async(intent:Intent,success:string)=>{try{await adapter.credit(user.id,new AbortController().signal);forget(intent);setPending(null);setBusy('');setRevision(v=>v+1);setNotice(success);}catch(error){setPending(intent);setBusy('readback');setRevision(v=>v+1);setNotice(`${success} 已接受，但当前投影未确认；只重读，不重复提交。${errorText(error)}`);}};
  const execute=async(intent:Intent,success:string)=>{if(intent.subject!==subject)return;if(!remember(intent)){setPending(null);setBusy('');setNotice('当前浏览器无法保存原操作意图，未提交任何写请求；请恢复站点存储后重试。');return;}setPending(intent);setBusy('pending');setNotice('');try{await adapter.creditDecide(intent.path,intent.body,new AbortController().signal,intent.key);const phasePersisted=phase(intent,'readback');setBusy('readback');if(!phasePersisted)setNotice('写入已接受，但当前浏览器无法持久化回读阶段；请保持此页打开并先恢复站点存储，不会自动重提。');await readback(intent,success);}catch(error){if(unknownWrite(error)||error instanceof AdminApiError&&(error.status===401||error.status===423)){phase(intent,'unknown');setPending(intent);setBusy('pending');setRevision(v=>v+1);setNotice(error instanceof AdminApiError&&error.status===401?'会话已变化；原主体、对象和幂等键已保留，请重新确认身份后核对。':error instanceof AdminApiError&&error.status===423?'当前写入被锁定；私有投影已刷新，原责任仍保留。':'请求结果未知；只使用原请求核对，不换键。');return;}forget(intent);setPending(null);setBusy('');setNotice(errorText(error));}};
  const submit=(path:string,body:Record<string,unknown>,success:string)=>{if(pending||busy)return;const generation=(intentGenerations.get(subject)??0)+1;intentGenerations.set(subject,generation);const intent:Intent={subject,path,body,key:`idem_${(globalThis.crypto?.randomUUID?.()??`${Date.now()}_${Math.random()}`).replaceAll('-','')}`,generation,persisted:false,phase:'unknown'};void execute(intent,success);};
  const retryPending=()=>{if(pending&&busy==='pending')void execute(pending,'原操作已重试，正在读取结果。');};
  const retryReadback=()=>{if(!pending||busy!=='readback')return;void readback(pending,'原操作状态已核对。');};
  const submitBreach=()=>{if(!sourceId.trim()||visibleReason.trim().length<2||internalBasis.trim().length<2)return;submit('breaches',{userId:user.id,sourceType,sourceId:sourceId.trim(),subjectRole:role,visibleReason:visibleReason.trim(),internalBasis:internalBasis.trim()},'违约确认已记录，请核对当前信用投影。');};
  return <div className="ud-credit-panel">
    {notice?<Message kind="info" title="信用处置提示">{notice}</Message>:null}
    {pending&&busy==='pending'?<Message kind="info" title="原操作结果待确认"><span>保持原主体、正文和幂等键；不会自动换键。</span><Button variant="outline" size="sm" onClick={retryPending}>用原请求核对</Button></Message>:null}
    {pending&&busy==='readback'?<Message kind="info" title="写入已接受，状态待读取"><Button variant="outline" size="sm" onClick={retryReadback}>重新读取</Button></Message>:null}
    <div className="ud-credit-summary"><div><span className="ud-muted">当前信用分</span><strong>{credit?.score??'未知'}</strong><small>{credit?'版本 '+credit.revision:'缺少可追溯初始化记录，不能按100分处理'}</small></div><div><span className="ud-muted">保证金读取</span><strong>{canGuaranteeRead?data.guarantees.length:'—'}</strong><small>{canGuaranteeRead?'按用户 → 出租账号逐笔核对':'缺少 credit.guarantee.read'}</small></div></div>
    <section className="ud-credit-section"><div className="ud-section-heading"><h3>确认违约</h3><span className="ud-muted">不根据取消、退款或提前结束自动扣分</span></div><div className="ud-credit-form"><label>来源类型<select value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value="ORDER">订单</option><option value="ACCOUNT">出租账号</option></select></label><label>来源编号<Input value={sourceId} onChange={e=>setSourceId(e.target.value)} placeholder="订单或账号 ID"/></label><label>主体角色<select value={role} onChange={e=>setRole(e.target.value)}><option value="OWNER">号主</option><option value="RENTER">租客</option></select></label><label>用户可见原因<textarea value={visibleReason} maxLength={500} onChange={e=>setVisibleReason(e.target.value)} placeholder="必填，用户会看到"/></label><label>内部依据<textarea value={internalBasis} maxLength={500} onChange={e=>setInternalBasis(e.target.value)} placeholder="内部调查依据，不向用户展示"/></label><Button disabled={!adapter.has(PERMISSION.creditDecide)||Boolean(busy)||!sourceId.trim()||visibleReason.trim().length<2||internalBasis.trim().length<2} onClick={submitBreach}>{busy==='pending'?'处理中…':'确认扣 10 分'}</Button></div></section>
    <section className="ud-credit-section"><div className="ud-section-heading"><h3>信用事件</h3><span className="ud-muted">只追加反向记录，不删除历史</span></div>{credit?.events?.length?<ul className="ud-credit-events">{credit.events.map((item:any)=><li key={item.id}><div><strong>{eventLabels[item.eventType]??item.eventType}</strong><span>{item.visibleReason} · {item.sourceType}:{item.sourceId}</span><small>{time(item.createdAt)} · {item.scoreBefore} → {item.scoreAfter}</small></div><Badge variant="outline">{item.reversed?'已撤销':'已记录'}</Badge>{item.eventType==='BREACH_CONFIRMED'&&!item.reversed?<><textarea aria-label={`撤销 ${item.id} 的用户可见原因`} value={reverseReason} placeholder="填写撤销理由" onChange={e=>setReverseReason(e.target.value)}/><textarea aria-label={`撤销 ${item.id} 的内部依据`} value={reverseBasis} placeholder="填写内部复核依据" onChange={e=>setReverseBasis(e.target.value)}/><Button variant="outline" size="sm" disabled={!adapter.has(PERMISSION.creditDecide)||Boolean(busy)||reverseReason.trim().length<2||reverseBasis.trim().length<2} onClick={()=>submit(`events/${item.id}/reverse`,{visibleReason:reverseReason.trim(),internalBasis:reverseBasis.trim()},'误判撤销已记录，请核对信用分。')}>撤销</Button></>:null}</li>)}</ul>:<Message kind="empty" title="暂无信用事件">初始分或后续处置记录将在有依据时显示。</Message>}</section>
    <section className="ud-credit-section"><div className="ud-section-heading"><h3>恢复申请</h3><span className="ud-muted">每7天最多一次，批准才会加分</span></div>{data.recoveryRequests?.length?<ul className="ud-credit-events">{data.recoveryRequests.map((item:any)=><li key={item.id}><div><strong>{item.status}</strong><span>{item.reason}</span><small>{time(item.createdAt)}</small></div>{item.status==='PENDING'?<><textarea aria-label={`恢复申请 ${item.id} 的复核理由`} value={decisionReasons[item.id]??''} placeholder="填写本次审核理由" onChange={e=>setDecisionReasons(current=>({...current,[item.id]:e.target.value}))}/><span className="ud-credit-actions"><Button variant="outline" size="sm" disabled={!adapter.has(PERMISSION.creditDecide)||Boolean(busy)||!decisionReasons[item.id]?.trim()} onClick={()=>submit(`recovery-requests/${item.id}/decision`,{decision:'APPROVE',reason:decisionReasons[item.id]!.trim()},'恢复已批准，请核对信用投影。')}>批准 +10</Button><Button variant="outline" size="sm" disabled={!adapter.has(PERMISSION.creditDecide)||Boolean(busy)||!decisionReasons[item.id]?.trim()} onClick={()=>submit(`recovery-requests/${item.id}/decision`,{decision:'REJECT',reason:decisionReasons[item.id]!.trim()},'恢复申请已驳回，请核对当前状态。')}>驳回</Button></span></>:null}</li>)}</ul>:<Message kind="empty" title="暂无恢复申请"/>}</section>
    {canGuaranteeRead?<section className="ud-credit-section"><div className="ud-section-heading"><h3>号主保证金</h3><span className="ud-muted">收款、退款与账务状态分开读取</span></div>{data.guarantees?.length?<div className="ud-guarantee-table">{data.guarantees.map((item:any)=><div key={`${item.accountId}:${item.priceVersionId}:${item.versionId}`}><strong>{item.displayNo??item.accountId}</strong><span>{stateLabels[item.state]??'未知'} · 计算基数 {item.baseCents===null?'未知':item.baseCents+'分'} · 应缴 {item.requiredCents+'分'}</span><small>收款依据：{item.reference??'无已确认依据'}；支付账务：{item.paymentFinanceEventId??'未形成'}；退款账务：{item.refundFinanceEventId??'未形成'}</small>{item.refundId&&item.refundPolicyState==='OWNER_DECISION_REQUIRED'&&adapter.hasCreditGuaranteeManage()?<><textarea aria-label={`退款 ${item.refundId} 的责任核证理由`} value={releaseReasons[item.refundId]??''} placeholder="填写实际责任核证理由" onChange={e=>setReleaseReasons(current=>({...current,[item.refundId]:e.target.value}))}/><Button variant="outline" size="sm" disabled={Boolean(busy)||!releaseReasons[item.refundId]?.trim()} onClick={()=>submit(`guarantees/${item.refundId}/release-decision`,{decision:'APPROVE',reason:releaseReasons[item.refundId]!.trim()},'退款释放决定已记录，请核对退款状态。')}>允许原路退还</Button></>:null}</div>)}</div>:<Message kind="empty" title="暂无保证金记录">信用达到免缴条件或尚未形成按账号的收款依据。</Message>}</section>:<Message title="保证金读取受限">当前管理员没有 credit.guarantee.read；信用处置与保证金读取分开授权。</Message>}
    {canGuaranteeRead&&data.transactions?.length?<section className="ud-credit-section"><div className="ud-section-heading"><h3>收款 / 退款 / 账务引用</h3><span className="ud-muted">原始交易状态不等于本地到账成功；范围按游戏权限过滤</span></div><div className="ud-guarantee-table">{data.transactions.map((item:any)=><div key={item.requirementId}><strong>{item.accountId}</strong><span>最近状态：收款 {item.paymentStatus??'未创建'} · 退款 {item.refundStatus??'未申请'}</span><small>商户单：{item.merchantOrderNo??'未生成'} · 收款账务：{item.paymentFinanceEventId??'未形成'} · 退款账务：{item.refundFinanceEventId??'未形成'}</small>{item.paymentHistory?.length?<details><summary>支付尝试 {item.paymentHistory.length} 笔</summary><ul>{item.paymentHistory.map((attempt:any)=><li key={attempt.id}><span>{attempt.status} · {attempt.observedAmountCents??attempt.amountCents} 分</span><small>支付单：{attempt.id} · 商户单：{attempt.merchantOrderNo} · 原交易：{attempt.providerTransactionId??'未形成'} · 账务：{attempt.financeEventId??'未形成'} · 分录：{attempt.ledgerEntryRef??'未形成'}</small></li>)}</ul></details>:null}{item.refundHistory?.length?<details><summary>退款尝试 {item.refundHistory.length} 笔</summary><ul>{item.refundHistory.map((attempt:any)=><li key={attempt.id}><span>{attempt.status} · {attempt.amountCents} 分</span><small>退款单：{attempt.id} · 原支付：{attempt.paymentId} · 原路单：{attempt.providerRefundId??'未形成'} · 账务：{attempt.financeEventId??'未形成'} · 分录：{attempt.ledgerEntryRef??'未形成'}</small></li>)}</ul></details>:null}</div>)}</div></section>:null}
  </div>;
}
